### ISSUE TITLE
Install and run SSH Server

### ISSUE THREAD

**Issue by jrseliga** [jetpack-io/devbox#1002]
There are a few use cases where this could be useful but the primary driver for this request is to workaround the current devbox VS Code extension limitations as outlined in this [feature request](https://github.com/jetpack-io/devbox/issues/1001).

This would allow devbox users to leverage the official [Remote - SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) to achieve a seamless developer experience using VS Code and devbox.

Is it possible to install / run OpenSSH Server in devbox? Can multiple devbox environments have OpenSSH Server running (on different ports)?

**Comment by mohsenari** [comment]
Do you mean installing open ssh server locally in devbox, and using vscode ssh extension to "ssh" into localhost but on the port that open ssh is running in your devbox environment?
If that's the case, it's a very interesting approach. We haven't tested it yet, but we'll give it a try and let you know if it's a viable approach.

**Comment by jrseliga** [comment]
@mohsenari yup, thanks for considering the idea!

I'm happy to help test, just not sure how to get OpenSSH Server up and running in devbox (or Nix).

**Comment by jrseliga** [comment]
Closing this as it was only a workaround to this [feature request](https://github.com/jetpack-io/devbox/issues/1001). A [simpler alternative](https://github.com/jetpack-io/devbox/issues/1001#issuecomment-1553771358) to was provided by the Nix community.

**Comment by mohsenari** [comment]
@jrseliga sounds good. 
If you want you can also try `devbox generate devcontainer` and run connect your vscode to a local container.
It isn't the same as remote SSH but it makes vscode to connect to a remote environment (your local docker container).

**Comment by MikeBosw** [comment]
This approach would be useful for IntelliJ as well.
