### ISSUE TITLE
[Bug]: telemetry makes the cli tool very slow

### ISSUE THREAD

**Issue by letmutx** [jetpack-io/devbox#1003]
**Current Behavior (bug)**

```zsh
gelus ➜  ~ REPORTTIME=1
gelus ➜  ~ devbox global shellenv
export PATH="${XDG_DATA_HOME:-$HOME/.local/share}/devbox/global/current/bin${PATH+:$PATH}";
hash -r
devbox global shellenv  10.39s user 0.65s system 128% cpu 8.575 total
gelus ➜  ~ DO_NOT_TRACK=1 devbox global shellenv     # executes instantly
export PATH="${XDG_DATA_HOME:-$HOME/.local/share}/devbox/global/current/bin${PATH+:$PATH}";
hash -r
```

**Expected Behavior (fix)**
Telemetry doesn't slowdown the tool.

From the source code, looks like an event is sent to segment for every invocation of the command line tool, `cd`-ing with direnv and opening a new shell are unusably slow. Thanks for keeping the DO_NOT_TRACK flag to disable it!

**Additional context**
```
gelus ➜  ~ devbox version -v
Version:     0.4.9
Platform:    linux_amd64
Commit:      b03f0d26da3df4318f2a8d70c0531c0c77d0d33c
Commit Time: 2023-05-02T23:26:52Z
Go Version:  go1.20.3
Launcher:    0.2.0
```

**Comment by Lagoja** [comment]
Tagging @gcurtis for visibility
Hey @letmutx, tank you for reporting! I think we are planning to batch some of these requests together so that it doesn't interfere with CLI commands. Let me check on if we can include that in an upcoming release.

**Comment by dnkmmr69420** [comment]
yeah I am not having that shell env command because the shell is slow to start up and it gives errors (but still works) on RHEL and its clones. instead I am having `export PATH="$HOME/.local/share/devbox/global/current/.devbox/nix/profile/default/bin:$PATH"` in ~/.bashrc

**Comment by joshbode** [comment]
I'm doing this in my `.profile` to source the global shellenv lazily:

```bash
DEVBOX_PROJECT=${XDG_DATA_HOME}/devbox/global/default
DEVBOX_PROFILE=${DEVBOX_PROJECT}/.devbox/nix/profile/default
export PATH=${PATH}:${DEVBOX_PROFILE}/bin:${DEVBOX_PROFILE}/sbin

devbox() {
  (
    if [ "$1" = global ] && [ "$2" != shellenv ]; then
      eval "$(command $0 global shellenv)"
    fi
    command "$0" "$@"
  )
}
```

no side-effects that I've noticed so far :)

**Comment by ibuildthecloud** [comment]
When you have crappy wifi, devbox become so annoying because of this. I use devbox with direnv integration so this becomes a huge pain when I cd in and out of devbox dirs.  Just devbox version seems to make a network call

```bash
$ time devbox version
0.5.5

real	0m5.013s
user	0m0.103s
sys	0m0.045s
```
