### ISSUE TITLE
[Bug]: Devbox environment in dev container not integrating with VS Code processes

### ISSUE THREAD

**Issue by apgrucza** [jetpack-io/devbox#1028]
**Current Behavior (bug)**

Running `devbox generate devcontainer` produces a dev container that includes the Devbox environment, but it does not integrate with all VS Code processes (as noted in #1001). For example, if I have a Devbox environment with Terraform installed and I configure this task in `.vscode/tasks.json`:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "terraform version",
            "type": "shell",
            "command": "terraform version"
        }
    ]
}
```

Running it with `Tasks: Run Task` gives this:

```
 *  Executing task: terraform version 

/bin/bash: line 1: terraform: command not found

 *  The terminal process "/bin/bash '-c', 'terraform version'" failed to launch (exit code: 127). 
```

Accessing the Devbox environment requires `devbox shell` to be run first. Although the [Devbox VS Code extension](https://marketplace.visualstudio.com/items?itemName=jetpack-io.devbox) does this for you automatically when opening a terminal, it does not help with other VS Code features such as tasks and extensions.

**Expected Behavior (fix)**

When connecting to the dev container, the Devbox environment should be immediately available. A proposed solution is to simply replace the `CMD ["devbox", "shell"]` line in the `Dockerfile` with this:

```dockerfile
RUN devbox shellenv --init-hook >> ~/.profile
```

This persists the Devbox environment to `~/.profile`, including the all-important `PATH` environment variable. Assuming `userEnvProbe` is left at its default value, dev container tooling will "probe" this file and pass the environment into the container. I've tried this and it allows tasks, debugging and extensions to work correctly.

The `devbox.autoShellOnTerminal` behaviour provided by the Devbox extension then becomes unnecessary and should be disabled in `devcontainer.json`:

```json
  "customizations": {
    "vscode": {
      "settings": {
        "devbox.autoShellOnTerminal": false
      },
      "extensions": [
        "jetpack-io.devbox"
      ]
    }
  },
```

**Additional context**
`devbox version -v` gives:

```
Version:     0.5.2
Platform:    linux_amd64
Commit:      8f579b2c45c730742cbf9b7c400f247abf902775
Commit Time: 2023-05-18T16:18:52Z
Go Version:  go1.20.4
Launcher:    0.2.0
```

**Comment by Lagoja** [comment]
@mohsenari for visibility

@apgrucza I think the `devbox shellenv --init-hook >> ~/.profile` is pretty clever. I'm going to test that to verify if it works. Thank you for reporting this and providing the suggestion!
