### ISSUE TITLE
[Bug]: Symlink error message when starting a new terminal window

### ISSUE THREAD

**Issue by rbelem** [jetpack-io/devbox#1073]
**Current Behavior (bug)**
Getting the following error message when starting a new terminal window. Devbox shellenv is sourced.
```
Error: symlink /home/rodrigo/.local/share/devbox/global/default/.devbox/nix/profile/default/include /home/rodrigo/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/include: file exists
```

**Expected Behavior (fix)**
No error message

**Additional context**
https://raw.githubusercontent.com/rbelem/devbox-global/main/devbox.json

**Comment by bketelsen** [comment]
i don't get this error when running from `main`, though.

**Comment by Lagoja** [comment]
@mikeland86, looks like an error with Devbox global sourcing

**Comment by bketelsen** [comment]
to reproduce it, do something that modifies your global devbox, which will trigger this error handling path.

**Comment by bketelsen** [comment]
> @rbelem I'm having trouble repro-ing this. My best guess is a race condition. Is there any package in your global that may might run on every command? When I delete the `include` symlink it reappears right away which makes me thing there's something under the hood calling `devbox global shellenv`. This can happen because the binaries are wrapped with `devbox global shellenv`.

There certainly is in mine... most of them.  direnv, starship, atuin, etc.

**Comment by bketelsen** [comment]
but maybe i'm mis-understanding the code. I'm not sure why running those apps would trigger a new shellenv call.

**Comment by rbelem** [comment]
I can't reproduce the error when building from main.

**Comment by mikeland86** [comment]
@rbelem it's a race condition so may not always repro. Here's the fix https://github.com/jetpack-io/devbox/pull/1082 

We may do a quick release to get this in.

**Comment by rbelem** [comment]
@mikeland86 #1082 resolved the issue. Another issue I noticed was that `ensurePackagesAreInstalled` was being called three times every new prompt. Is it related to #1082?
