### ISSUE TITLE
Feature Request: disable '(devbox)' hint

### ISSUE THREAD

**Issue by paletteOvO** [jetpack-io/devbox#108]
I have my starship config that hints I am in devbox shell which is more consistent but duplicated with devbox's hint.
![圖片](https://user-images.githubusercontent.com/16734391/189528658-440bfce7-c108-4ab9-8063-dc4b1875ac70.png)
![圖片](https://user-images.githubusercontent.com/16734391/189528684-31ab4704-713d-40b7-8a12-70e07dda0c58.png)

**Comment by gcurtis** [comment]
Thanks for the feedback! This is something we're planning on fixing for the next release. Work is being tracked in #74, so I'm going to close this out as a duplicate.
