### ISSUE TITLE
[Bug]: Unable to `devbox shell` with a local flake that exports more than 1 package as of 0.5.0

### ISSUE THREAD

**Issue by quekshuy** [jetpack-io/devbox#1085]
**Current Behavior (bug)**
Unable to `devbox shell` when `devbox.json` uses a local flake that outputs more than 1 package. This error message is displayed:

```
Error: Package "path:/Users/quekshuy/devbox-proj/my-php-flake" is ambiguous. It has the following possible outputs:
packages.aarch64-darwin.php, packages.aarch64-darwin.hello
```

**Expected Behavior (fix)**
Should be able to use the local flake that outputs more than 1 package, as demonstrated [here in devbox's example](https://github.com/jetpack-io/devbox/tree/main/examples/flakes/php).

**Additional context**
Please include the output of `devbox version -v` and
a copy of your `devbox.json` file.

```
❯ devbox version -v
Version:     0.5.3
Platform:    darwin_arm64
Commit:      2ffe94fd2c71ad607c3f002d50fbe867002c4468
Commit Time: 2023-05-30T21:36:27Z
Go Version:  go1.20.4
Launcher:    0.2.0
```

`devbox.json`:
```
 {
   "packages": [
     "path:my-php-flake#php",
     "path:my-php-flake#hello"
   ],
   "shell": {
     "init_hook": null
   },
   "nixpkgs": {
     "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
   }
 }
```

`flake.nix` ([as taken from devbox's examples/php folder](https://github.com/jetpack-io/devbox/blob/main/examples/flakes/php/my-php-flake/flake.nix)):
```
{
  description = "A flake that outputs PHP with memcached and ds extension and hello pkg.";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        packages = {
          # Flakes can export multiple packages. To include specific packages in
          # devbox.json you can use url fragments (e.g. path:my-flake#my-package)
          php = pkgs.php.withExtensions ({ enabled, all }: enabled ++ (with all; [ ds ]));
          hello = pkgs.hello;

          # If you only want to export a single package, you can name it default which allows
          # installation without using url fragment (.e.g. "path:my-flake")
          # default = pkgs.php.withExtensions ({ enabled, all }: enabled ++ (with all; [ ds memcached ]));
        };
      });
}
```

It works though if I use devbox 0.4.9. So that's the version I'm sticking with for now.

**Comment by Lagoja** [comment]
Hey @quekshuy, this issue should be addressed in 0.5.3, but it looks like there was an issue in the release that did not pick up the fix. We'll look into addressing tomorrow morning.

**Comment by savil** [comment]
@quekshuy using the new `0.5.4` I am able to `devbox shell` within the folder `devbox/examples/flakes/php` that has the example. Could you confirm if it works for you?

**Comment by quekshuy** [comment]
It works for me. Thank you!
