### ISSUE TITLE
Feature request to support .Net

### ISSUE THREAD

**Issue by BryanEddy5** [jetpack-io/devbox#11]
Awesome project. I’d love to leverage it with .Net 6.

**Comment by robrich** [comment]
You can add [`dotnet-sdk`(https://search.nixos.org/packages?query=dotnet) package to your Devbox shell, and then `dotnet run` inside Devbox.  We do need to build the .NET detection when you generate an image though.  Thanks for the feature request.

**Comment by Lagoja** [comment]
We now have language support for .Net projects! Documentation for our autodetection is here: https://www.jetpack.io/devbox/docs/language_support/csharp/
