### ISSUE TITLE
Devbox Add Throwing Strange Error

### ISSUE THREAD

**Issue by gfleetwood** [jetpack-io/devbox#110]
I'm on Ubuntu 20.04 and updated about three times in the last week. When I do `devbox add PKG` I get:

```
$ devbox add xournal
Error: invalid character '"' after array element
Usage:
  devbox add <pkg>... [flags]

Flags:
  -h, --help   help for add
```

Contents of devbox.json:

```
{
  "packages": [
    "pdfsandwich",
    "rustup",
    "python",
    "R",
    "pdftk"
    "git-lfs",
    "blender",
    "godot",
    "keepassxc",
    "python39Packages.PyGithub",
    "dropbox",
    "python310Packages.pip"
  ]
}
```
Result from `devbox version`:

```
$ devbox version
0.0.4
segment 2022/09/12 11:25:02 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp: lookup api.segment.io on 100.64.0.7:53: no such host
segment 2022/09/12 11:25:02 ERROR: 1 messages dropped because they failed to be sent and the client was closed
```

**Comment by loreto** [comment]
@gfleetwood to help use debug, could you send the contents of your `devbox.json` and let us know the output of `devbox version`?

**Comment by gfleetwood** [comment]
@loreto Sorry. Added.

**Comment by loreto** [comment]
@gfleetwood I believe this error is happening because we fail to parse your `devbox.json` since there's a comma `,` missing after `"pdftk"`

We'll add better error messaging so it's more obvious what's causing the error.

**Comment by gfleetwood** [comment]
Ah, should have checked that. Next time I'll use devbox rm instead of hand editing the file.
