### ISSUE TITLE
[Bug]: Issue with Nix flake

### ISSUE THREAD

**Issue by trickster** [jetpack-io/devbox#1100]
**Current Behavior (bug)**
Using a custom flake that downloads spanner emulator (which is not statically linked) but GLIBC not found in the `devbox shell` environment. 

**Expected Behavior (fix)**
No errors

**Additional context**
Please include the output of `devbox version -v` and
a copy of your `devbox.json` file.

```
Version:     0.5.4
Platform:    linux_amd64
Commit:      92bb293af46fe6869648c20e4a6476dc83df0092
Commit Time: 2023-06-01T21:35:06Z
Go Version:  go1.20.4
Launcher:    0.2.0
```

```
{
  "packages": [
    "path:emulator"
  ],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
```

Complete repro is available here https://github.com/trickster/devbox-flake-issue/. You can look at the `emulator` folder.

**Comment by Lagoja** [comment]
Hey @trickster, working on reproducing this. Can you share some more details on the error? Does it occur when you run `devbox shell`? Or at some other time?

**Comment by pergraa-celonis** [comment]
> Finally made it work perfectly with these [trickster/devbox-flake-issue@`working`/emulator/flake.nix#L29-L35](https://github.com/trickster/devbox-flake-issue/blob/working/emulator/flake.nix?rgh-link-date=2023-06-06T08%3A53%3A56Z#L29-L35)

Hi @trickster, repo is 404, would you mind sharing your solution directly here? Thanks!

**Comment by trickster** [comment]
@pergraa-celonis I just did
