### ISSUE TITLE
Enable PHP extensions in php planner

### ISSUE THREAD

**Issue by ebauger** [jetpack-io/devbox#111]
Hi!

I want to install a php project with Composer to install a dependency (require or dev-require) using the imap extension.

I figured out the [php80Extensions.imap ](https://search.nixos.org/packages?channel=22.05&show=php80Extensions.imap&from=0&size=50&sort=relevance&type=packages&query=imap) is not installable.

I opened an [issue at NixOS repo ](https://github.com/NixOS/nixpkgs/issues/190514#issuecomment-1242276154)and I got a solution for the nix shell. 

How is it possible to enable/install php extensions with devbox? It's a new feature for PHP?

Thank you @[drupol](https://github.com/drupol) from nixpkgs team at NixOS for the answer.

**Comment by drupol** [comment]
Hi @ebauger ,

What are you trying to achieve?

**Comment by mikeland86** [comment]
@ebauger devbox currently doesn't support php extensions, but I can add it to roadmap. We can use this issue to track it

**Comment by mikeland86** [comment]
@ebauger PR is out, so likely will be released next week. One caveat is that the `imap` extension is [not supported on darwin (mac)](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/php/8.1.nix#L51).

**Comment by ebauger** [comment]
> Hi @ebauger ,
> 
> What are you trying to achieve?

Hi @drupol 

I want to make an isolate environment for a PHP 8.0 [Mautic 4.4.2](https://github.com/mautic/mautic/releases/tag/4.4.2)

 I will share a example repo tomorrow.

@mikeland86 It can be a practical example

**Comment by ebauger** [comment]
> @ebauger PR is out, so likely will be released next week. One caveat is that the `imap` extension is [not supported on darwin (mac)](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/php/8.1.nix#L51). 

I don't know how the layer/container on dev and production build work with devbox.

It possible to produce a container image with NixOS @mikeland86 ?

Why imap don't work on Darwin @drupol ?

**Comment by mikeland86** [comment]
@ebauger yep! 

if you do `devbox build` it will create an image with your nix environment. 

you can then run the development server 

`docker run -p 8080:8080 devbox`

or you can shell in: 

`docker run -it --entrypoint="" devbox /busybox/sh`

**Comment by ebauger** [comment]
> @ebauger yep! 
> 
> if you do `devbox build` it will create an image with your nix environment. 
> 
> you can then run the development server 
> 
> `docker run -p 8080:8080 devbox`
> 
> or you can shell in: 
> 
> `docker run -it --entrypoint="" devbox /busybox/sh`

Good to know. @mikeland86 

If we do devbox init && devbox shell. 

What system nix packages will use? My own system with darwin version packages (for MacOS) or a nixOS base image container?

**Comment by mikeland86** [comment]
`devbox shell` uses `nix-shell` under the hood, so you'll get your own system.

**Comment by ebauger** [comment]
Here the example repo @mikeland86 and @drupol  : https://github.com/ebauger/mautic-container

**Comment by drupol** [comment]
This repository is empty.

**Comment by drupol** [comment]
I see what you're trying to achieve.

Basically you'd like to have the `imap` extension inside your container which is built using devbox.

I don't know devbox, but maybe there's a way to configure the PHP derivation used in devbox? To be investigated.

Basically what you would need is to inject a custom version of PHP with the `imap` extension enabled:

```nix
(pkgs.php.buildEnv {
    extensions = ({ enabled, all }: enabled ++ (with all; [
      imap
    ]));
  })
```

I'm thinking out loud, but have you tried to replace `php` in [here](https://github.com/ebauger/mautic-container/blob/main/devbox.json#L3) with `php.buildEnv { extensions = ({ enabled, all }: enabled ++ (with all; [ imap ]));})` ?

**Comment by ebauger** [comment]
@drupol,

If you use devbox, it will create a hidden tree here `.devbox/gen/shell.nix` mine look:
```
let
  pkgs = import (fetchTarball {
    # Commit hash as of 2022-08-16
    # `git ls-remote https://github.com/nixos/nixpkgs nixos-unstable`
    url = "https://github.com/nixos/nixpkgs/archive/af9e00071d0971eb292fd5abef334e66eda3cb69.tar.gz";
    sha256 = "1mdwy0419m5i9ss6s5frbhgzgyccbwycxm5nal40c8486bai0hwy";
  }) {};
in with pkgs;
mkShell {
  shellHook =
    ''
      echo "Starting a devbox shell..."
      export name="devbox"
      export IN_NIX_SHELL=0
      export DEVBOX_SHELL_ENABLED=1

      # We set PURE_NIX_PATH in case the user's init files in the devbox shell
      # end up modifying PATH.
      export PURE_NIX_PATH="$PATH"

      # Make sure we include a basic path for the devbox shell. Otherwise it may
      # fail to start.
      export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

      
    '';
  packages = [
    php
  
    php80Extensions.mbstring
  
    php80Extensions.xml
  
    php80Extensions.ctype
  
    php80Extensions.iconv
  
    php80Extensions.intl
  
    php80Extensions.pdo_sqlite
  
    php80Extensions.mysqli
  
    php80Extensions.pdo_mysql
  
    php80Packages.composer
  
    git
  ];
}
```
With the actual release, we have to manually change the generated file with your suggestion.

I don't know if devbox use this string expression `php.buildEnv { extensions = ({ enabled, all }: enabled ++ (with all; [ imap ]));})` and put to shell.nix

`devbox add php`

`devbox add phpExtensions.imap~ should detect this kind of package and create the right expression in the nix file.

It's a specific use case for PHP, but a don't know if Python for example of the same kind of behaviour.


@mikeland86 explained is not a feature now, but it'll be on the roadmap. See the PR #113

**Comment by drupol** [comment]
Ok I got it.

Have you tried to just replace `php` with the expression I gave you already ?

**Comment by ebauger** [comment]
I did the test on shell.nix and fire devbox shell.
No error, but the package is not working on darwin. 

and I can't test with the build image with NixOS.
with `devbox build` don't work on 0.0.4 here my issue https://github.com/jetpack-io/devbox/pull/53#issuecomment-1245628122

Any advice @mikeland86 ?

**Comment by drupol** [comment]
Can you test on a linux box maybe ?

**Comment by mikeland86** [comment]
Hi @ebauger  that issue is fixed on [0.0.5](https://github.com/jetpack-io/devbox/releases/tag/0.0.5) which we just released. Give it a try!

**Comment by ebauger** [comment]
> @ebauger yep!
> 
> if you do `devbox build` it will create an image with your nix environment.
> 
> you can then run the development server
> 
> `docker run -p 8080:8080 devbox`
> 
> or you can shell in:
> 
> `docker run -it --entrypoint="" devbox /busybox/sh`

From my repo

I did : 
```
> docker run -it --entrypoint="" devbox /busybox/sh
/app # php -v
PHP 8.1.9 (cli) (built: Aug  2 2022 13:02:24) (ZTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
/app # php -m | grep imap
imap
```
It work, but the package php is not 8.0 has expected. Maybe is more about a Nix package issue @drupol ?

**Comment by drupol** [comment]
Hi,

Replace `php` by `php80` and it should be ok.
