### ISSUE TITLE
[Bug]: Dev Containers - Python virtual environment not activated when `postCreateCommand` runs

### ISSUE THREAD

**Issue by apgrucza** [jetpack-io/devbox#1122]
**Current Behavior (bug)**

The Python virtual environment is not activated by the time that VS Code runs the `postCreateCommand` action. This is because the Python virtual environment is created on demand, rather than during the Docker build phase.

To reproduce:

1. Run `devbox create --template python-pip`
2. Run `cd python-pip`
3. Run `devbox generate devcontainer`
4. Add the following to `.devcontainer/devcontainer.json`: `"postCreateCommand": "which python"`
5. Run `code .`
6. In the popup window, click **Reopen in Container**

When the **Configuring...** terminal window appears, the path shown is not to the Python virtual environment:
`/code/.devbox/virtenv/.wrappers/bin/python`

**Expected Behavior (fix)**

The terminal window should show this path:
`/home/devbox/.local/state/devbox/v-933c2/python310Packages.pip/.venv/bin/python`

Currently `devbox install` does not create the Python virtual environment, but `devbox run` does. So, a workaround is to modify the Dockerfile by changing
```dockerfile
RUN devbox install
```
to
````dockerfile
RUN devbox run -- echo "Installing packages"
````

A proper solution would be to change `devbox install` to (optionally?) do the extra initialisation required, or to provide a separate `devbox` command to do this.

**Additional context**
Output of `devbox version -v`:
```
Version:     0.5.4
Platform:    linux_amd64
Commit:      92bb293af46fe6869648c20e4a6476dc83df0092
Commit Time: 2023-06-01T21:35:06Z
Go Version:  go1.20.4
Launcher:    0.2.0
```

**Comment by mohsenari** [comment]
Apologies for late response on this and thanks for reporing it. This is an interesting case. I think the fix can be as simple as changing what happens in the CLI when `devbox install` is called to make sure the python plugin that sets up virtualenv gets called as well. 
But that might defeat the purpose of an "install" command. I'll try reproducing this and will make a PR to fix the use case.

**Comment by mohsenari** [comment]
with the release of 0.5.10 I think this fix is in, and the template is changes to `devbox run -- "installed package"` instead of `devbox install`
