### ISSUE TITLE
[Feature Request] Generate Makefile for scripts

### ISSUE THREAD

**Issue by ibuildthecloud** [jetpack-io/devbox#1136]
Make is so common as the entrypoint to projects that it would be nice if I could generate a Makefile from devbox that just adds targets for `scripts`.  So basically `devbox generate scripts-makefile` would create/add to makefile the following

```makefile
foo:
     devbox run foo
```
Where foo is a script defined.  You could obvioulsy make this fancier and just put in some make-fu so that targets are dynamically generated from devbox so that you don't have to keep adding them.  I'll personally try to figure that out for myself.
```[tasklist]
### Tasks
- [ ] https://github.com/jetpack-io/devbox/issues/1141
```

**Comment by ibuildthecloud** [comment]
So I got the following working
```makefile
devboxtargets := $(shell devbox run targets)

.PHONY: $(devboxtargets)
.DEFAULT_GOAL := targets
    

$(devboxtargets):
    devbox run $@
```

So the interesting thing that came from this fun exercise is that it would be a lot easier if there was a devbox command to just list the available scripts.  Right now I'm just doing
```json
"scripts": {
      "targets": "jq -r '.shell.scripts | keys | join(\" \")' devbox.json"
    }
```

**Comment by ibuildthecloud** [comment]
I could be convinced that this is easy enough to do that it doesn't need to be a feature, but conceptually it's the same as the `.envrc` integration which is almost as trivial under the hood.

**Comment by Lagoja** [comment]
Listing the scripts would be very helpful, and it is implemented for `devbox global run`, so it should be fairly easy to do. We could have them list if you run `devbox run` without passing an argument

**Comment by ibuildthecloud** [comment]
Oh I guess that sorta is there already
 ```$ devbox run
Available scripts:
* run
* targets
* dev
```
The only thing is I need a raw output that is just the list, no other test.  Maybe `-q` could be abused for that `devbox run -q`
