### ISSUE TITLE
[Bug]: Invalid shell escaping with `devbox run`

### ISSUE THREAD

**Issue by ibuildthecloud** [jetpack-io/devbox#1137]
**Current Behavior (bug)**
The following command fails

`devbox run -- jq -r '.shell.scripts | keys | join(" ")' devbox.json`

You get the following output

```
$ devbox run -- jq -r '.shell.scripts | keys | join(" ")' devbox.json
/home/darren/src/acorn-identity/.devbox/gen/scripts/.cmd.sh: eval: line 3: syntax error near unexpected token `" "'
/home/darren/src/acorn-identity/.devbox/gen/scripts/.cmd.sh: eval: line 3: `jq -r .shell.scripts | keys | join(" ") devbox.json'
```

**Expected Behavior (fix)**
You know, not fail :)

I'm guessing this issue is related to the fact that I have `"` nested in `'`. I haven't debugged it further.

**Additional context**
```$ devbox version -v
Version:     0.5.4
Platform:    linux_amd64
Commit:      92bb293af46fe6869648c20e4a6476dc83df0092
Commit Time: 2023-06-01T21:35:06Z
Go Version:  go1.20.4
Launcher:    0.2.0
```

**Comment by gcurtis** [comment]
@savil it looks like this is because we eval the command passed to `devbox run` without re-quoting the arguments. So `jq -r '.shell.scripts | keys | join(" ")' devbox.json` is becoming `jq -r .shell.scripts | keys | join(" ") devbox.json` (without the single quotes).
