### ISSUE TITLE
Versioning devbox config

### ISSUE THREAD

**Issue by JoyceBabu** [jetpack-io/devbox#1155]
In case of `apacheHttpd`, the [documentation](https://www.jetpack.io/devbox/docs/devbox_examples/servers/apache/) says

We recommend copying your `httpd.conf` file to a new directory and updating HTTPD_CONFDIR if you decide to modify it.

But in case `php` plugin, the `php-fpm.conf` path is hard coded to {{ .DevboxDir }}/php-fpm.conf.

Is the devbox.d directory managed by the project, or by devbox? To be more specific, are we allowed to add / modify files within the devbox.d directory, or should we ignore the entire directory from version control? Will devbox try update the files in devbox.d, even if they are modified?

Also, the apache plugin documentation says:

> Note that by default, Apache is configured with ./devbox.d/web as the DocumentRoot. To change this, you should copy and modify the default ./devbox.d/Apache/Apache.conf

The default file is `./devbox.d/apacheHttpd/httpd.conf`.

**Comment by ipince** [comment]
Hi @JoyceBabu 

As mentioned in the other issue (#894 ), the stuff in `devbox.d` gets generated by the plugin, but then you're free to edit as you see fit, and commit it to version control.

Also, you can have your configuration file somewhere else if you want, and then point `HTTPD_CONFDIR` to that place. The plugins are just meant to make things "just work" out-of-the-box, so they create files and set environment variables in a reasonable way, but you're free to change them however you want afterwards.

--

> The default file is ./devbox.d/apacheHttpd/httpd.conf.

Thank you, that's a typo in the docs. I'll send a fix.

**Comment by ipince** [comment]
> but you're free to change them however you want afterwards.

You can override a variable that is set by a plugin by putting it in `devbox.json`:

https://www.jetpack.io/devbox/docs/configuration/#env

**Comment by JoyceBabu** [comment]
@ipince 

In that case is is safe to say that we are free to modify the default `httpd.conf` in place, without copying it to another location? If so, the documentation should probably be updated to remove the copying part.

> Note that by default, Apache is configured with `./devbox.d/web` as the DocumentRoot. To change this, you should modify the default `./devbox.d/apache/httpd.conf`.

Also, will devbox try update the files in `devbox.d`, even if they are modified?

**Comment by ipince** [comment]
@JoyceBabu yes, you can modify in place.

Devbox will not overwrite.

Please see this section in the docs:
https://www.jetpack.io/devbox/docs/guides/plugins/#helper-files
