### ISSUE TITLE
Package Management: Support Global Package Installs for NPM + Bundler

### ISSUE THREAD

**Issue by Lagoja** [jetpack-io/devbox#116]

**Comment by abdullahdevrel** [comment]
This was the response I got from the devs. I haven't tried the solution yet, but I think it should work.

> Nix is pretty restrictive about installing packages globally. But you can install global node packages using: 
> ```devbox add nodePackages.<package_name>```
> For example, if you need yalc:
> ```devbox add nodePackages.yalc```

Because it is built on top of Nix, I think many concepts are interchangeable.

**Comment by Lagoja** [comment]
Supportable with the workflow described above for nodePackages and some other package managers. For tools like Bundler, there are some workarounds that can be found in our examples Repo (https://github.com/jetpack-io/jetpack-examples). We're planning some work to make this configuration easier for developers to setup.

**Comment by abdullahdevrel** [comment]
@Lagoja Oh geez, I didn't realize that you were a contributor yourself, I thought it was a question from a user haha. So wanted to help. :)

**Comment by justinTM** [comment]
```console
% devbox add nodePackages.gitlab-ci-local   

Error: Package nodePackages.gitlab-ci-local not found
```
