### ISSUE TITLE
[Bug]: Bash prompt not colored in pure mode

### ISSUE THREAD

**Issue by apgrucza** [jetpack-io/devbox#1200]
**Current Behavior (bug)**
When using Bash as a shell and running `devbox shell`, the prompt is colored (green and blue). But when running `devbox shell --pure`, the prompt is not colored (white).

**Expected Behavior (fix)**
The prompt should be colored in pure mode. This should just be a matter of adding `TERM` to the list of environment variables that are passed through from the parent shell.

**Additional context**
Output of `devbox version -v`:
```
Version:     0.5.5
Platform:    linux_amd64
Commit:      891e8de7a8ab7a3fec42fad069326d68cb84603e
Commit Time: 2023-06-19T19:18:00Z
Go Version:  go1.20.5
Launcher:    0.2.0
```

**Comment by mohsenari** [comment]
This issue should be fixed in v0.5.6
