### ISSUE TITLE
[Bug]:  whoa, do not "devbox global add devbox"

### ISSUE THREAD

**Issue by ibuildthecloud** [jetpack-io/devbox#1216]
**Current Behavior (bug)**

I hit some weird issue where a program was calling `git` which was installed with `devbox global` and then the shell wrapper was failing because it couldn't find devbox.  In retrospect I assume it was because `/usr/local/bin` was not in the path.  But stupidly I did `devbox global add devbox`.  First off, that installs devbox 0.4.8 (and it seems like nix only has 0.5.2 of devbox as of writing) but then I think I proceeded to fork bomb myself.  Everything just went to crap until I ` sudo rm -f /home/darren/.local/share/devbox/global/default/.devbox/nix/profile/default/bin/devbox`.  The system was so unusable that I couldn't get a output of `ps` to see if it was really stuck in a forkbomb.

**Additional context**
devbox 0.5.5 on the host and 0.4.8 inside the global devbox.

**Comment by Lagoja** [comment]
Affects `devbox add devbox` as well, as I just learned 🤦

It would be pretty cool if devbox could be managed by devbox global, so it could eb worth figuring out how to avoid the fork bomb

**Comment by Lagoja** [comment]
This is related to https://github.com/jetpack-io/devbox/pull/1260. I tested on 0.5.7, and the fork bomb seems to now be resolved. I'm not sure if this will call some other unexpected behavior though 🤔
