### ISSUE TITLE
[Feature]: Add trailing newline to Devbox files

### ISSUE THREAD

**Issue by maxdeviant** [jetpack-io/devbox#1248]
**Is your feature request related to a problem you're trying to solve? Please describe.**

Currently Devbox does not write trailing newlines to its various files (`devbox.json`, `devbox.lock`, etc).

This results in a visual indicator in Git diffs showing the lack of a trailing newline:

<img width="564" alt="Screenshot 2023-07-03 at 5 19 01 PM" src="https://github.com/jetpack-io/devbox/assets/1486634/377b3602-ce64-4f4a-86d6-97768a5030b2">

<img width="851" alt="Screenshot 2023-07-03 at 5 19 08 PM" src="https://github.com/jetpack-io/devbox/assets/1486634/af4a3f56-3006-4ac1-ad79-77469ecaad59">

**Describe the solution you'd like**

I would like it if Devbox did any one of the following:
1. Wrote trailing newlines by default
2. Had a flag/setting to write trailing newlines
3. Retained trailing newlines added by hand

**Describe alternatives you've considered**

I don't see a reason why Devbox shouldn't support trailing newlines.

**Comment by savil** [comment]
@maxdeviant thanks for filing this!

**Comment by Lagoja** [comment]
Hey @maxdeviant, this should be in the latest 0.5.7 Release. Please let us know if this is not resolved for you

**Comment by maxdeviant** [comment]
> Hey @maxdeviant, this should be in the latest 0.5.7 Release. Please let us know if this is not resolved for you

Thanks so much!
