### ISSUE TITLE
[Bug]: Wrong package version on Mac

### ISSUE THREAD

**Issue by Allsimon** [jetpack-io/devbox#1283]
**Current Behavior (bug)**

On a Mac M1, when running this:
```shell
➜ mkdir testdevbox && cd testdevbox && devbox init
➜ devbox add jdk@17.0.7+7
➜ devbox shell
➜ java --version
openjdk 17.0.3 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)
➜ which java
/Users/foo/dev/testdevbox/.devbox/virtenv/.wrappers/bin/java
➜ cat devbox.lock
{
  "lockfile_version": "1",
  "packages": {
    "jdk@17.0.7+7": {
      "last_modified": "2023-06-29T16:20:38Z",
      "resolved": "github:NixOS/nixpkgs/3c614fbc76fc152f3e1bc4b2263da6d90adf80fb#jdk17",
      "source": "devbox-search",
      "version": "17.0.7+7"
    }
  }
}
```
I'm getting an unexpected version `openjdk 17.0.3 2022-04-19 LTS`
On a Linux box, I get the expected version `openjdk 17.0.7 2023-04-18` with the same devbox.lock

**Expected Behavior (fix)**

I'm expecting a consistent version across Mac/Linux. Is this an expected behaviour for ARM mac ? 

**Additional context**
```shell
➜ cat devbox.json
{
  "packages": [
    "jdk@17.0.7+7"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```
On the M1 Mac:
```
➜ devbox version -v
Version:     0.5.7
Platform:    darwin_arm64
Commit:      95ee45715bd2d5a7e60cd58093f2a87a88a4564d
Commit Time: 2023-07-12T22:28:00Z
Go Version:  go1.20.5
Launcher:    0.2.0
```
On the Linux box:
```
➜ devbox version -v
Version:     0.5.7
Platform:    linux_amd64
Commit:      95ee45715bd2d5a7e60cd58093f2a87a88a4564d
Commit Time: 2023-07-12T22:28:00Z
Go Version:  go1.20.5
Launcher:    0.2.0
```

**Comment by Allsimon** [comment]
Nevermind, it's not an issue with devbox but with nixpkgs: https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/compilers/openjdk/darwin/17.nix

**Comment by Lagoja** [comment]
I think this is something we should fix or communicate more effectively -- it's possible that a given nixpkg revision could have different versions of a package for each platform, so Devbox should pick a commit that actually contains the version you requested for the platform you're building on

In scenarios like this one, we should probably warn or indicate that the version is not available on all platforms, so the developer can make the right decision when choosing packages
