### ISSUE TITLE
[Bug]: Why is there no "How to uninstall devbox"

### ISSUE THREAD

**Issue by MuchHustle** [jetpack-io/devbox#1287]
All I could find was the suggestion to "uninstall all of Nix" with a link to a nix site on same. I don't want to uninstall nix I want to uninstall devbox. I had nix before devbox, so are you saying it is invasive parasite that has infested all of my nix? OK, so how? Thank you.

**Current Behavior (bug)**

**Expected Behavior (fix)**

**Additional context**
Please include the output of `devbox version -v` and
a copy of your `devbox.json` file.

**Comment by fangzhengjin** [comment]
According to the installation script `https://get.jetpack.io/devbox`, in fact devbox only installs a binary file `/ usr/local/bin/ devbox`

**Comment by MuchHustle** [comment]
Thanks! Still actually using it for now. I was going thru a frustrating patch of too many new things at once...didn't mean to take it out on devbox.

**Comment by dcd-arnold** [comment]
I would like to point out, that the point is still valid. It should be documented how `devbox` shall be uninstalled in the readme.
