### ISSUE TITLE
Deno package displayed in Nixhub is out of date

### ISSUE THREAD

**Issue by khaled** [jetpack-io/devbox#1293]
**Are you requesting a new package or reporting an issue on an existing one?**
Existing

**If reporting an issue on an existing one, what is the name of the package?**
Deno

**What changes are you requesting?**
Noticed for the past few days that the latest version being displayed is 1.34.2.  Current unstable is 1.35.1.

**Comment by Lagoja** [comment]
Index is now up to date, and updating on a daily cadence. This means we should have the latest versions in Nixpkgs no more than 24hrs after they are published. 

Thanks for reporting this!
