### ISSUE TITLE
[Feature]: Conditionally install a package depending on the platform

### ISSUE THREAD

**Issue by dax** [jetpack-io/devbox#1298]
**Is your feature request related to a problem you're trying to solve? Please describe.**
I would like to use the same Devbox configuration for different OS: MacOS and Linux in my case but could be other.
For the Rust project I am working on, it requires `darwin.apple_sdk.frameworks.SystemConfiguration` to compile some dependencies on MacOS whereas this package does not exist on Linux.
The build of the Devbox environment thus fails on Linux.

**Describe the solution you'd like**
I would be useful to be able to exclude some package depending on the current platform (Linux in my example).

**Describe alternatives you've considered**
As an alternative, I am using 2 differents configuration files: 1 for MacOS and another for Linux. It requires to maintain both in sync (excluding the problematic dependency)

**Comment by Lagoja** [comment]
This feature was added in Devbox 0.5.12 or later. See the docs below for how to add system specific packages to your devbox.json:

https://www.jetpack.io/devbox/docs/guides/platform_specific_packages/
