### ISSUE TITLE
what's difference compare with docker

### ISSUE THREAD

**Issue by jinfagang** [jetpack-io/devbox#13]
hi, devbox looks awesome. but any behind principle explnation of it?

**Comment by Lagoja** [comment]
Hey @jinfagang, We added some context in the [README](https://github.com/jetpack-io/devbox#readme)  about how Devbox is different from Docker.

Devbox uses Nix to create isolated development environments with your dependencies on your local machine, so you can develop your application in a consistent environment without polluting your laptop environment, or sacrificing speed + resources to build a Docker container. 

When you need to deploy your application to cloud, Devbox can be used to generate a Docker container with all your packages installed. 

Some context on why we built Devbox can be found [in this thread](https://twitter.com/DanielLoreto/status/1562954153181163523)

Hope this helps! Feel free to message me on our Discord Server if you'd like to discuss more.

**Comment by jinfagang** [comment]
@Lagoja Hi, if so, what if direclty using devbox packaged env to server for deploy to cloud? Why still need export to docker container?
