### ISSUE TITLE
[Feature]: publish the extension on open-vsx 

### ISSUE THREAD

**Issue by mrhyperbit** [jetpack-io/devbox#1340]
**Is your feature request related to a problem you're trying to solve? Please describe.**
Currently [VSCodium](https://github.com/VSCodium/vscodium), [Eclipse Theia](http://theia-ide.org/), [Code - OSS]( https://wiki.archlinux.org/title/Visual_Studio_Code) by default uses [openvsx](https://open-vsx.org/), for the users of those product including me can use this extension.

**Describe the solution you'd like**
Publish the extension on [openvsx](https://open-vsx.org/)

**Describe alternatives you've considered**
I am more than happy to make a pull request. 

More details at :-
- https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
- https://www.eclipse.org/legal/open-vsx-registry-faq/

**Comment by mohsenari** [comment]
thanks @mrhyperbit for mentioning this. We created an account and namespace in open-vsx and I made a PR that's linked here to publish to openvsx registry. Once done I'll ping you here so that you can install and try the extension

**Comment by mohsenari** [comment]
@mrhyperbit we published the same version (0.1.2) of vscode extension on open vsx. 
you can download it here: https://open-vsx.org/extension/jetpack-io/devbox

I haven't put a lot of time to setup vscodium and test the extension, please give it a try and if you encounter any bugs feel free to open an issue.
