### ISSUE TITLE
[Feature]: Less logging on shell startup

### ISSUE THREAD

**Issue by altano** [jetpack-io/devbox#1347]
When I launch a devbox shell (automatically through direnv) I get a ton of output. It looks like this:

> ➜  src cd my-project
> direnv: loading ~/src/my-project/.envrc
> direnv: using devbox
> direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +DEVBOX_LATEST_VERSION +DEVBOX_OG_PATH_9bde7310c0965a4fb5fd92fc95311eea5b47c497c43a22b6ffbf50463280ab89 +HOST_PATH +IN_NIX_SHELL +LAUNCHER_PATH +LAUNCHER_VERSION +LD +LD_DYLD_PATH +LD_LIBRARY_PATH +LIBRARY_PATH +MACOSX_DEPLOYMENT_TARGET +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_aarch64_apple_darwin +NIX_BUILD_CORES +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_aarch64_apple_darwin +NIX_CFLAGS_COMPILE +NIX_DONT_SET_RPATH +NIX_DONT_SET_RPATH_FOR_BUILD +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_IGNORE_LD_THROUGH_GCC +NIX_LDFLAGS +NIX_NO_SELF_RPATH +NIX_STORE +NM +NODE_PATH +PATH_LOCALE +RANLIB +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +XDG_DATA_DIRS +__DEVBOX_SHELLENV_HASH_9bde7310c0965a4fb5fd92fc95311eea5b47c497c43a22b6ffbf50463280ab89 +__ETC_PROFILE_NIX_SOURCED +__darwinAllowLocalNetworking +__impureHostDeps +__propagatedImpureHostDeps +__propagatedSandboxProfile +__sandboxProfile +__structuredAttrs +buildInputs +buildPhase +builder +cmakeFlags +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +dontAddDisableDepTrack +mesonFlags +name +nativeBuildInputs +out +outputs +patches +phases +preferLocalBuild +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH
> ➜  my-project git:(main)

I may have enabled some form of debug logging that I can't find a setting for, so this might just be my setup, but that seems like a bit much.

**Describe the solution you'd like**
Ideally the output would be something much simpler, like:

> ➜  src cd my-project
> direnv: loading ~/src/my-project/.envrc
> direnv: using devbox
> ➜  my-project git:(main)

**Describe alternatives you've considered**
I'd be happy to flip a config on to get this behavior, if it can't be the default?

**Additional context**
n/a

**Comment by mohsenari** [comment]
@altano this is a Direnv issue. See [related thread]( https://github.com/direnv/direnv/issues/68 ) for discussion and possible workarounds
