### ISSUE TITLE
[Bug]:  using coreutils package is slow

### ISSUE THREAD

**Issue by savil** [jetpack-io/devbox#1350]
**Current Behavior (bug)**
When using `coreutils` with `devbox global`, all the related operations seems slow.

**Expected Behavior (fix)**
Using `coreutils` should be fast.

**Additional context**

Likely cause: 
Devbox wraps installed binaries in a shell script to ensure the environment is always correct for them. However, this may lead to slowness if the binary is used a *lot* like coreutils binaries might be.

cc @mstruebing

**Comment by alvarogonzalez-packlink** [comment]
Probably this is related to #1586 . I've seen this is deeply aggravated if you have one of those "enterprise security posture vulnerability scan something something" applications. In my case, the Crowdstrike agent.

**Comment by gcurtis** [comment]
Wrappers are gone as of 0.8.2, so this should be fixed.
