### ISSUE TITLE
Go planner prints obscure error when install stage fails

### ISSUE THREAD

**Issue by gcurtis** [jetpack-io/devbox#137]
We should print a more helpful error message if the `install_stage` for a Go project (and possibly other languages/stages) exits with an error.

This is the error right now:

```
executor failed running [/bin/sh -eux -o pipefail -c go get]: exit code: 1
segment 2022/09/16 12:46:34 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp: lookup api.segment.io on 10.0.254.2:53: no such host
segment 2022/09/16 12:46:34 ERROR: 1 messages dropped because they failed to be sent and the client was closed
```

The segment error should be suppressed and we should show the `go get` combined output along with the exit code. We should also include the steps on how to fix it.

**Comment by Lagoja** [comment]
Related to #70

**Comment by LucilleH** [comment]
@loreto I think we can close this? Should be addressed by both your segment PR and my golang ones?

**Comment by loreto** [comment]
Yes. The segment one is #197. Closing.
