### ISSUE TITLE
[Bug]: invalid Discord invite link

### ISSUE THREAD

**Issue by paulochf** [jetpack-io/devbox#1372]
**Current Behavior (bug)**
I tried the Discord invite link to join the community to ask some questions, but all of them were broken.

**Expected Behavior (fix)**
I would be able to join the Discord channel.

**Additional context**
Tried: Github's link, 3-4-ish links in https://www.jetpack.io/devbox page.

**Comment by loreto** [comment]
@paulochf Thanks for reporting. Is this the url that's broken if you click on it? https://discord.gg/jetpack-io

(trying to figure out if the problem is on the discord side, or on our frontend)

**Comment by paulochf** [comment]
> @paulochf Thanks for reporting. Is this the url that's broken if you click on it? https://discord.gg/jetpack-io
> 
> (trying to figure out if the problem is on the discord side, or on our frontend)

Hey! Thanks! Yours worked.
