### ISSUE TITLE
Implement Podman support

### ISSUE THREAD

**Issue by orowith2os** [jetpack-io/devbox#14]
Podman can be used as a (rootless and rootfull) drop-in replacement for Docker. Some users would like to take advantage of this, mainly on systems where the root filesystem is immutable and/or it is not beneficial to have both Docker and Podman installed.

All that would be required to support Podman *afaik* would be checking for a `podman` command and then using that if available (and possibly configurable in a configuration file and/or the CLI.)

Users can additionally work around this limitation of devbox by making either 1. an alias for Docker to pass to Podman, or 2. make a file in `/usr/bin/` named `docker` that redirects to Podman. However, this isn't ideal, and it would most likely be trivial to implement support for Podman in the program itself.

I would love to help to implement this myself, however, I am inexperienced in Go, so I don't want to go tinkering where I shouldn't.

**Comment by croqaz** [comment]
I use Podman instead of Docker for a couple of years without issues. I would love to see it here!

Wonderful tool!!

**Comment by penyuan** [comment]
Strongly support Podman support by devbox, can't wait to see it.

Also AFAIK there are also security benefits to using Podman which is a nice plus.

**Comment by loreto** [comment]
Thank you for the suggestion! Closing this issue in favor of https://github.com/jetpack-io/devbox/issues/18. That one is worded more generally to include not just `podman`, but options like `lima` or `krunvm` as well. Feel free to follow that issue to track updates/progress.

**Comment by penyuan** [comment]
Thanks @loreto, support for more tools sounds even better! Will follow #18.
