### ISSUE TITLE
Programs installed with `devbox global` print an update message

### ISSUE THREAD

**Issue by gcurtis** [jetpack-io/devbox#1420]
**Current Behavior (bug)**

```
$ go                   
Info: New devbox available: 0.5.10 -> v0.5.11. Please run `devbox version update`.
Go is a tool for managing Go source code.
$ zsh -c "echo hi"
Info: New devbox available: 0.5.10 -> v0.5.11. Please run `devbox version update`.
hi
```

**Expected Behavior (fix)**

Devbox wrappers never print anything.

**Comment by mohsenari** [comment]
my guess is that the wrapper for these binaries run a devbox command and that command runs a version check. Or the devbox command we have in zshrc/bashrc runs a version check.

**Comment by savil** [comment]
fixed
