### ISSUE TITLE
[Bug]: starship prompt initialization goofed up

### ISSUE THREAD

**Issue by gregwebs** [jetpack-io/devbox#1426]
**Current Behavior (bug)**

```
devbox shell
Starting a devbox shell...
_zimfw_source_zimrc:source:3: no such file or directory: /var/folders/kj/6g7rq7fj67n2tgctd9291w140000gn/T/nix-shell.XXXXXX.w9jz0Xd5/devbox2244932488/.zimrc
Failed to source /var/folders/kj/6g7rq7fj67n2tgctd9291w140000gn/T/nix-shell.XXXXXX.w9jz0Xd5/devbox2244932488/.zimrc
_zimfw_source_zimrc:source:3: no such file or directory: /var/folders/kj/6g7rq7fj67n2tgctd9291w140000gn/T/nix-shell.XXXXXX.w9jz0Xd5/devbox2244932488/.zimrc
Failed to source /var/folders/kj/6g7rq7fj67n2tgctd9291w140000gn/T/nix-shell.XXXXXX.w9jz0Xd5/devbox2244932488/.zimrc
/Users/gregweber/.zshrc:source:112: no such file or directory: /var/folders/kj/6g7rq7fj67n2tgctd9291w140000gn/T/nix-shell.XXXXXX.w9jz0Xd5/devbox2244932488/.zim/init.zsh
(devbox)
\[\]bravo2\[\] on \[\] \[\]\[\]main\[\] \[\][\[\]\[\]\$\[\]\[\]?\[\]\[\]]\[\] via \[\]🐹 \[\]\[\]v1.21.0\[\]\[\]
```

**Expected Behavior (fix)**
Normal shell prompt. In devenv I set the following and I get a nice starship prompt:

```
  # https://github.com/cachix/devenv/blob/main/examples/starship/devenv.nix
  starship.enable = true;
  starship.config.enable = true;
```

**Additional context**
Please include the output of `devbox version -v` and
a copy of your `devbox.json` file.

```
devbox version -v
Version:     0.5.11
Platform:    darwin_arm64
Commit:      1052c4e37c16ce0df5d60afb8c82076cd290eee8
Commit Time: 2023-08-10T23:32:09Z
Go Version:  go1.20.7
Launcher:    0.2.0
```

**Comment by savil** [comment]
@gregwebs it appears that you have some code in your zshrc to setup starship? Could you share that so I can try to repro this?

**Comment by savil** [comment]
Starship should work if you do `eval "$(starship init zsh)"`

**Comment by gregwebs** [comment]
```
command -v starship >/dev/null && eval "$(starship init zsh)"
```

yeah, running the eval in the devbox shell does work.
I can run it in the init_hook if I install the starship package in devbox- so that seems like a pretty good workaround!
It does still first print out the errors in the ticket description.

**Comment by gregwebs** [comment]
oh, my dotfiles are public here: https://github.com/gregwebs/dotfiles

**Comment by savil** [comment]
@gregwebs great, thanks for linking to the dotfiles. I think we needed to support Zim via ensuring the .zimrc is also read by `devbox shell`.  I've sent a PR for the fix, which should come out in the next release -- I believe there's one scheduled for this week.
