### ISSUE TITLE
[Package Issue Report]: prometheus does not provide promtool

### ISSUE THREAD

**Issue by wrdls** [jetpack-io/devbox#1431]
**If reporting an issue on an existing one, what is the name of the package?**

`prometheus`

**What changes are you requesting?**

Installing the `prometheus`  package should also provide the `promtool` binary.

This seems to be defined as a postinstall action (as far as my nix knowledge goes): https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/servers/monitoring/prometheus/default.nix#L119C19-L121

I tried Installing with `nix-env` as shown on the [nixos website](https://search.nixos.org/packages?channel=23.05&show=prometheus&from=0&size=50&sort=relevance&type=packages&query=promtool) to see if that would work and it does seem to give me the appropriate binaries:

```
$ nix-env -iA nixpkgs.prometheus
installing 'prometheus-2.38.0'
these 4 paths will be fetched (65.92 MiB download, 206.48 MiB unpacked):
  /nix/store/2ax1jq6jhqh826l62zz8sc1qrm8bsbx3-iana-etc-20220915
  /nix/store/fsxr40h41zb9s2g8rhz7b88fccz951za-mailcap-2.1.53
  /nix/store/msj01lbvcqwx62z7rz7bm5wwv5y0z622-prometheus-2.38.0
  /nix/store/yy7gb4g266l61kmwmc57q6jp7ls5yqvc-tzdata-2022e
copying path '/nix/store/2ax1jq6jhqh826l62zz8sc1qrm8bsbx3-iana-etc-20220915' from 'https://cache.nixos.org'...
copying path '/nix/store/fsxr40h41zb9s2g8rhz7b88fccz951za-mailcap-2.1.53' from 'https://cache.nixos.org'...
copying path '/nix/store/yy7gb4g266l61kmwmc57q6jp7ls5yqvc-tzdata-2022e' from 'https://cache.nixos.org'...
copying path '/nix/store/msj01lbvcqwx62z7rz7bm5wwv5y0z622-prometheus-2.38.0' from 'https://cache.nixos.org'...
building '/nix/store/mp31nc3pz9grpd7qc74bhwmbdcilzqd6-user-environment.drv'...

$ ls -l /nix/var/nix/profiles/per-user/wardloos/profile/bin/
total 462336
-r-xr-xr-x  1 root  nixbld  110703424 Jan  1  1970 prometheus
-r-xr-xr-x  1 root  nixbld  102550768 Jan  1  1970 promtool
```

**Comment by savil** [comment]
@wrdls from inspecting the output you pasted (i.e. `/nix/store/msj01lbvcqwx62z7rz7bm5wwv5y0z622-prometheus-2.38.0`), it seems that the nixpkg you were looking at was version 2.38. Indeed, if you do `devbox add prometheus@2.38` you'll also get promtools.

When you add `devbox add prometheus`, this is adding the latest version of prometheus, which is 2.46. Will look into why its missing promtools...

**Comment by gcurtis** [comment]
@wrdls thanks for reporting this. I think this is happening because Devbox currently only installs the default output path for a package, but the Prometheus CLI tools are under a separate `cli` output:

```json5
// nix derivation show nixpkgs#prometheus | jq
{
  "/nix/store/08040fdfq9cl6dky5rhnz5wl27rxzvh0-prometheus-2.46.0.drv": {
    // ...
    "name": "prometheus-2.46.0",
    "outputs": {
      "cli": {
        "path": "/nix/store/fca1bikkqjm0rzy7md1vz7rk47f02xi4-prometheus-2.46.0-cli"
      },
      "doc": {
        "path": "/nix/store/innz16ja56fw18sjy8yg4q7zxn3javli-prometheus-2.46.0-doc"
      },
      // Devbox is only installing this
      "out": {
        "path": "/nix/store/47zq7k8ka0hgfjxzh6sjd5d587fm80b6-prometheus-2.46.0"
      }
    },
    "system": "aarch64-darwin"
  }
}
```

@mikeland73 do you remember how we handled multiple outputs for `curl`? I'm wondering if we should just be installing all outputs instead of the default one.

**Comment by wrdls** [comment]
> @wrdls from inspecting the output you pasted (i.e. `/nix/store/msj01lbvcqwx62z7rz7bm5wwv5y0z622-prometheus-2.38.0`), it seems that the prometheus you were looking at was version 2.38. Indeed, if you do `devbox add prometheus@2.38` you'll also get promtools.

Thanks, that indeed seems to work.

**Comment by wrdls** [comment]
@gcurtis Should I consider this issue closed after https://github.com/jetpack-io/devbox/pull/1630?

Is the syntax final?

```diff
- devbox add prometheus
+ devbox add flake:nixpkgs#prometheus^out,cli
```

Is quite a big change and changes the command too much (i.e. selecting an output should be additive to the original command).

I was more thinking something like `devbox add prometheus` is equivalent to `devbox add prometheus[*]` and `devbox add prometheus[out,cli,doc]`

Or to keep it closer to `nix-shell -p`: `devbox add prometheus.all`

I also don't like that this exposes more of nix.
The way I see it is that you you'd use tools like Devbox and Fleek to hide some of the internals and complexity of nix. If they don't, they start to lose their value.

**Comment by savil** [comment]
@wrdls that is good feedback. I agree that we could further simplify this by having other means of expressing the output. For example: `devbox add <package> --outputs=out,cli` or `devbox add <package> --outputs=all`. 

In general, its hard to fully avoid some of the nix-ness, since these packages are from `nix`. The very concept of `outputs` here is a nix-ism bleeding through. That said, I'd rather avoid coming up with out own syntax for outputs in the package name (like `devbox add prometheus[out,cli,doc]`) and instead rely on more explicit command flags. WDYT?

**Comment by wrdls** [comment]
@savil A flag like that works as well. 👍 (assuming you can only add one package at a time)

I understand it's difficult to fully hide nix, and you probably shouldn't for certain more complex functionality.
But selecting an output in my opinion doesn't fall into this category.

I'm looking at this from the viewpoint of an SRE who's evaluating nix and it's ecosystem to see if this can replace tools like asdf for developers. Having to drop into more complex syntax and having to explain flakes is a tough sell.
