### ISSUE TITLE
[Feature]: Stop scripts executions on error

### ISSUE THREAD

**Issue by Akiyamka** [jetpack-io/devbox#1457]
Let's consider a simple case
```json
{
  "packages": [ "..."],
  "env": { "...": "..." },
  "shell": {
    "scripts": {
      "start": [
        "bash ./check_something.sh",
        "bash ./do_some_long_and_verbose_task.sh"
      ]
    }
  }
}

```
Right now if `check_something.sh` exit with error, script `do_some_long_task.sh` executed despite that.
If `do_some_long_task` generate a lot of debug info in stdout, developer even not have a chance to see error from first script in terminal

## Possible solution:
I expect that devbox check exit code of every script and stop execution on first exit with error.
In simple words - it would be cool if it will work like `./check_something.sh && ./do_some_long_task.sh` syntax.
(that can be used as workaround right now, but it less readable and not cross platform)

**Comment by savil** [comment]
@Akiyamka try running it with `export DEVBOX_FEATURE_SCRIPT_EXIT_ON_ERROR=1` set in your shell environment.

Like:  `DEVBOX_FEATURE_SCRIPT_EXIT_ON_ERROR=1 devbox run run-my-script`.

Does that do what you want?

**Comment by Akiyamka** [comment]
@savil, Yes! This variable just switches to the behavior that I need.
Unfortunately it has no effect if declared in the env section of devbox.json, so now I think how to set it on other developers machines

**Comment by savil** [comment]
@Akiyamka cool, thanks for confirming. 

This is a feature we need to productize so its easy for any devbox user to switch on -- that env-var flag is intended for our development purposes only. Let me discuss with the team, and circle back on how/when we can do it.

**Comment by Akiyamka** [comment]
I think the easiest option is to make this the default behavior. Seems like terminating on error is a very basic expectation. And in case we want to ignore an error, we usually write explicitly add `|| true` or even  `2> /dev/null`. So both cases work fine
