### ISSUE TITLE
[Feature]: support comments

### ISSUE THREAD

**Issue by pinage404** [jetpack-io/devbox#1464]
**Is your feature request related to a problem you're trying to solve? Please describe.**
Sometimes, i have dependencies that are not obvious why they are needed ; in that case, i like to explain in comments why the dependency is necessary

**Describe the solution you'd like**
I would like to be able to have a `devbox.yml` or a `devbox.jsonc` to have JSON with Comments

**Describe alternatives you've considered**
Not using DevBox and keeping the complicated Nix files

**Comment by savil** [comment]
Thanks for the suggestion. We've also wanted this for a while, and even have a prototype config format called tyson that we'd considered https://github.com/jetpack-io/tyson

cc @loreto

**Comment by pinage404** [comment]
Is there a feature flag on DevBox to test it ?

**Comment by savil** [comment]
@pinage404 no, tyson isn't integrated for now.

**Comment by loreto** [comment]
Before moving forwards w/ tyson, we could enable json w/ comments. @Lagoja to think about where we could prioritize this.

**Comment by jcrben** [comment]
don't like the sound of tyson, why not just build upon the existing support for json with comments, which is ubiquitous since that's what VSCode uses for its configuration files

**Comment by jcrben** [comment]
@gcurtis looks like this was addressed by https://github.com/jetpack-io/devbox/pull/1539

**Comment by gcurtis** [comment]
It was! Closing this out.
