### ISSUE TITLE
[Package Issue Report]: typst

### ISSUE THREAD

**Issue by satoqz** [jetpack-io/devbox#1472]
Typst (https://www.nixhub.io/packages/typst) has two different versioning schemes in its release history. While Typst now uses SemVer (e.g. 0.7.0), earlier this year releases were still tagged by date (e.g. 23-03-28).

Nixhub does not seem to handle this well - the older versioning scheme is treated with higher priority and thus the very outdated version 23-03-28 is chosen as the latest version, while it should be the current 0.7.0.

To illustrate:

```sh
devbox add typst
```

will install `typst-23-03-28`, while it should install `typst-0.7.0`.

**Comment by gcurtis** [comment]
Thanks for reporting. We have a few packages right now that aren't sorting correctly. We're aiming to get a fix out this week to handle inconsistent version strings better.

Related to #1466.

**Comment by Lagoja** [comment]
Search results for `typst` are now sorted correctly in `devbox search`: 

```
* typst  (0.8.0, 0.7.0, 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.0, 0.1.0, 0.1, 23-03-28)
```

Installing `typst@latest` with devbox now installs version 0.8.0
