### ISSUE TITLE
[Feature]: Don't default to @latest

### ISSUE THREAD

**Issue by altano** [jetpack-io/devbox#1476]
_(This is not really a feature request but more of a discussion request.)_

I love the ideals of nix and I love the ease of interfacing it through devbox on my development machine. But, the default `devbox add` behavior of installing a package pinned to `@latest` seems very antithetical to the nix philosophy. In other words, the devbox default is 0% reproducible. If I start a project, add a bunch of packages to it, and come back a year later, all my packages will be different versions and things probably won't work.

Back when devbox didn't have package versions in devbox.json it had the nixpkgs hash, so in a sense the default was to pin to a specific version of a package (transitively through the hash). But now that we have versions instead of a nixpkgs hash, NOTHING is really pinned by default.

Because of this my workflow is to never start with `devbox add` and instead to always `devbox search` and manually `devbox add` the package pinned to the latest version. I sometimes pin to major version numbers depending on exactly what I'm doing, but I always pin to _a_ version.

What does everyone think? Is `@latest` and intentional design decision with benefits I'm not seeing?

**Comment by Akiyamka** [comment]
> In other words, the devbox default is 0% reproducible.
devbox also creates `devbox.lock` file with exact version and hash, so it's perfectly reproducible, until this packages available.

**Comment by altano** [comment]
Oh, hey, wait... my test was flawed. I was misunderstanding the devbox.lock format.

If I do this:

1. devbox add nodejs@18
2. manually modify devbox.json to have nodejs@latest
3. MANUALLY change the key in devbox.lock from `"nodejs@18"` to `"nodejs@latest"`
4. devbox install

Devbox STAYS at node 18, and does not upgrade to node 20.

Okay, so this all makes sense to me now:
* devbox by default will just record @latest in devbox.json, because that's what you asked for
* devbox will record the actual version and nixpkgs hash in devbox.lock, so as long as you don't change `nodejs@latest` in devbox.json, you'll continue getting the exact same version.

That all makes sense to me!

**Comment by Lagoja** [comment]
This is correct, if you use `devbox install`, we will install using the actual versions in the lockfile. so `nodejs@latest` would stay at nodejs 18

If you run `devbox upgrade`, we will regenerate the lockfile based on the versions in your debox.json. In this case, `nodejs@latest`would update to nodejs 20
