### ISSUE TITLE
[Feature]: Allow passing arguments through to scripts

### ISSUE THREAD

**Issue by bbugh** [jetpack-io/devbox#1479]
devbox is great, thanks for doing such a wonderful job taking the miserable suffering out of using nix.

**Is your feature request related to a problem you're trying to solve? Please describe.**

We have a script file that needs to take in additional run-time specified command line arguments, like "--something" but there does not seem to be a way to do this at this time.

**Describe the solution you'd like**

Given a `devbox.json`:

```json
{
  "shell": {
    "scripts": {
      "do_something": "does_something -a -b -c -d"
    }
  }
}
```

Running

```bash
# preferable
devbox run do_something --special-thing
# or less preferable but still functional
devbox run do_something -- --special-thing
```

would pass the rest of the command line arguments on to the script, so that it runs

```bash
do_something -a -b -c -d --special-thing
``` 

in the dev shell.

**Describe alternatives you've considered**

* Not using devbox
* Using some other task runner like Just that allows passing through arguments
* Doing it all manually by hand every time the script is run

**Additional context**

◄:•D

**Comment by Lagoja** [comment]
Devbox scripts are really just bash scripts, so you could set your own flags and then pass any other arguments you want via "$@". For example: 

```
{
  "packages": [
    "cowsay@latest"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "vader": "cowsay -f vader \"$@\""
    }
  }
}
```

Would then let you run `devbox run vader hello` and get the right result: 

```
 _______
< hello >
 -------
        \    ,-^-.
         \   !oYo!
          \ /./=\.\______
               ##        )\/\
                ||-----w||
                ||      ||

               Cowth Vader
```
