### ISSUE TITLE
[Feature]: How to deal with non-canonical library locations

### ISSUE THREAD

**Issue by mvgijssel** [jetpack-io/devbox#1481]
**Is your feature request related to a problem you're trying to solve? Please describe.**
I'm running into this problem https://discourse.nixos.org/t/any-ideas-to-marry-libxml2-pip-and-nix-shell/277 where I'm trying to install lxml within the devbox shell using pip. The pip installer cannot find `libxml/xpath.h`

This is at

```
/nix/store/7hykkzqzc4qyq2xhmndj5sivmwmyb9lw-libxml2+py-2.11.4/include/libxml2/libxml/xpath.h
```

instead of the canonical

```
/nix/store/7hykkzqzc4qyq2xhmndj5sivmwmyb9lw-libxml2+py-2.11.4/include/libxml/xpath.h
```

**Describe the solution you'd like**
As a hacky workaround I now have the following in my `devbox.json`

```
  "env": {
    "C_INCLUDE_PATH": "/nix/store/7hykkzqzc4qyq2xhmndj5sivmwmyb9lw-libxml2+py-2.11.4/include/libxml2"
  },
```

but for obvious reasons I don't want to hardcode the nix store path. 

**Describe alternatives you've considered**
No

**Additional context**
Similar problem https://discourse.nixos.org/t/any-ideas-to-marry-libxml2-pip-and-nix-shell/277

**Comment by Lagoja** [comment]
Hey @mvgijssel, can you share your `devbox.json` so we can try to replicate the issue?

Something that might help is that when you install packages with `devbox`, we symlink the packages' outputs in the `.devbox/virtenv/.wrappers` directory. For example, if I add `libxml2.dev`, I can see the following in that dir:

```
.devbox/virtenv/.wrappers/include
└── libxml2
    └── libxml
        ├── HTMLparser.h
        ├── HTMLtree.h
        ├── SAX.h
<snip>
        ├── xpath.h
        ├── xpathInternals.h
        └── xpointer.h
```

Which means you could try something like: 
```json
  "env": {
    "C_INCLUDE_PATH": "$PWD/.devbox/virtenv/.wrappers/include/libxml2/xpath.h"
  },
```

**Comment by mvgijssel** [comment]
Thanks for the `.devbox/virtenv/.wrappers` tip, works like a charm! Smallest reproducible example is:

```json
{
  "packages": [
    "python310Packages.pip@23.2.1"
  ],
  "shell": {
    "init_hook": [
      "source $VENV_DIR/bin/activate",
      "pip install lxml"
    ]
  }
}
```

Running `devbox shell` on macOS M1 consistently fails with

```
fatal error: 'libxml/xpath.h' file not found
```

**Comment by Lagoja** [comment]
Just as a quick extra note: We recently added a `DEVBOX_PACKAGES_DIR` variable in devbox shell, which is aliased to `${project_root}/.devbox/virtenv/.wrappers`. Which means you could further simplify the example above to read: 

```json
  "env": {
    "C_INCLUDE_PATH": "$DEVBOX_PACKAGES_DIR/include/libxml2"
  },
```

Thanks again for reporting! closing this now
