### ISSUE TITLE
[Question] Support for `google-cloud-sdk` `withExtraComponents` option?

### ISSUE THREAD

**Issue by gdahia** [jetpack-io/devbox#1498]
I tried many ways to obtain the result of installing `google-cloud-sdk.withExtraComponents [google-cloud-sdk.components.gke-gcloud-auth-plugin]`, including manually editing the `devbox.json` file, to no avail.

It seems like the only way to properly use [`google-cloud-sdk` and `kubectl` as of today](https://github.com/NixOS/nixpkgs/issues/182856).

Is there a way to achieve this using `devbox`? Thanks!

**Comment by Lagoja** [comment]
Hey @gdahia 

Currently, this can be done using our [Flake Support](https://www.jetpack.io/devbox/docs/guides/using_flakes/#using-a-local-flake). The steps to do this are: 

1. Create a subdirectory called `gcloud` in your project
2. Within that subdirectory, create a `flake.nix` file and add the following: 

```nix
{
  description = "Google Cloud SDK with GKE auth plugin";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils}:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };
      in {
        packages = {
          google-cloud-sdk = pkgs.google-cloud-sdk.withExtraComponents [pkgs.google-cloud-sdk.components.gke-gcloud-auth-plugin];
        };
      }
    );
}
```
3. Add the flake package to your `devbox.json` by running `devbox add path:gcloud#google-cloud-sdk`, or adding the following to your `devbox.json`: 
```json
"packages": [
    "<other packages>"
    "path:gcloud#google-cloud-sdk"
]
```
4. Now when you run `devbox shell`, Devbox will install the SDK with the extra components.

---

Let me know if this works for you. We should look into making this easier, or finding a way to better customize packages in your `devbox.json`

**Comment by gdahia** [comment]
Thanks for the reply. For my particular setup, I wanted this for `devbox global`. How could I adapt these instructions for that setting?

Also, I would be willing to help to implement this in my free time. Unfortunately, I have zero experience with the project and would need some light guidance to do that.

**Comment by Lagoja** [comment]
@gdahia This can be added to `devbox global` by adding the subdirecory and flake in your Devbox global path (print this out by running `devbox global path` in your terminal) as described above. 

You can then add the flake to your global profile using `devbox global add path:gcloud#google-cloud-sdk`

**Comment by gdahia** [comment]
Thanks, this worked perfectly!

**Comment by seanpoulter** [comment]
Thanks for the solution @Lagoja.

Any suggestion on how to pin the version? I'm sorry I haven't researched a solution yet. I'm using `devbox` to avoid Flakes. Would we need to return additional attributes pkgs?

```
"packages": [
    "<other packages>"
    "path:gcloud@467.0.0#google-cloud-sdk@467.0.0"
]
```

```
Error: error installing package path:./gcloud#google-cloud-sdk@467.0.0
source: nix path-info exit code: 1, output: error: flake 'path:/Users/work/Development/GitHub/PHACDataHub/sci-portal/gcloud' does not provide attribute 'packages.aarch64-darwin.google-cloud-sdk@467.0.0', 'legacyPackages.aarch64-darwin.google-cloud-sdk@467.0.0' or 'google-cloud-sdk@467.0.0'
, err: exit status 1
```

**Comment by ovitente** [comment]
@Lagoja 's solution worked for me. Thank you !
There are another person who also used this solution - https://github.com/vfarcic/crossplane-kubernetes/blob/main/devbox.json

**Comment by gberche-orange** [comment]
@seanpoulter or anyone else found a syntax to pin the google-cloud-sdk version ?
