### ISSUE TITLE
[Bug]: suspected plugin field documented but not implemented

### ISSUE THREAD

**Issue by jay-aye-see-kay** [jetpack-io/devbox#1556]
**Background**
I was trying to understand the behaviour of the [match field when creating a plugin](https://www.jetpack.io/devbox/docs/guides/creating_plugins/#match-string), specifically what exactly it matched against. The documentation was brief and I couldn't find any existing plugins using this field so looked through the source code and it [appears this field isn't actually read](https://github.com/jetpack-io/devbox/blob/2d8c4ff11ca1063ef036040615ae89f6458f8d7c/internal/plugin/plugin.go#L39-L54).

I was creating a mongodb plugin which I no longer need as I've found the supplied one in this other repo https://github.com/jetpack-io/devbox-plugins/tree/main/mongodb. (side note the discoverability of the other repo is bad, any reason why these plugins aren't part of this repo?) So I don't need this `match` field implemented, it would be reasonable IMO to just remove it from the docs.

**Current Behavior (bug)**
The `match` field doesn't appear to be used/implemented.

**Expected Behavior (fix)**
The docs should match the implementation (if they don't already I'm not 100% this is a bug).

**Comment by Lagoja** [comment]
Hey @jay-aye-see-kay, thanks for reporting this, have a PR to remove this field now.
