### ISSUE TITLE
[Bug]: Repo with poetry submodule failing since 0.7

### ISSUE THREAD

**Issue by rabelenda** [jetpack-io/devbox#1563]
**Current Behavior (bug)**
I have a project with 2 submodules, one is a python project for a rest api backend and the other a pnpm project for the frontend SPA.

I created the project with following structure:

```
+ myproject
  + devbox.json
  +- service
  |  + pyproject.toml
  |  + ...
  +- frontend
     +- package.json
     +- ...
```

My devbox.json:

```
{
  "packages": [
    "nodejs@latest",
    "poetry@latest",
    "python3@latest",
    "nodePackages.pnpm@latest",
    "redis@latest"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "agent": [
        "cd service && poetry run uvicorn service:app --reload"
      ],
      "frontend": [
        "pnpm --dir frontend dev"
      ],
      "install": [
        "pnpm --dir frontend install",
        "cd service",
        "poetry install"
      ],
      "test": [
        "cd service && poetry run pytest -vv"
      ]
    }
  }
}
```

This was working fine in 0.5.13 but when I updated to 0.7.0 I started getting this error and can't use any of defined scripts:

```
Poetry could not find a pyproject.toml file in /Users/user/myproject or its parents
```

Can you provide a fix? Or alternate project structure, configuration, or workaround we should use when having a mono repo (a repo with multiple sub "environments") like this example?

Regards

**Comment by savil** [comment]
@rabelenda sorry about that. We'll circle back about fixing it. To unblock you, just wanted to suggest using `DEVBOX_USE_VERSION=0.5.13` or `DEVBOX_USE_VERSION=0.6.0` until its fixed.

**Comment by rabelenda** [comment]
Hello, thank you!

I have also tested with 0.6.0 and 0.5.14.

0.5.14 works the same way as 0.5.13.
0.6.0 works the same way as 0.7.0.

So, seems that the change in behavior was introduced in 0.6.0.

Regards

**Comment by savil** [comment]
@rabelenda in Devbox 0.7, we enabled `errexit` for the devbox scripts i.e. generates `set -e`. As a result, the Devbox poetry plugin began erroring in your project, since it runs this line:
```
# configures poetry to use the version of python from your devbox.json
poetry env use $(command -v python) no-interaction
```

The attached PR should fix it for your scenario, assuming you have a single poetry project in your devbox-project, if you can add the following to your `devbox.json`:
```
 "env": {
     "DEVBOX_PYPROJECT_DIR": "$PWD/service"
   },
```

**Comment by savil** [comment]
For completeness, in Devbox 0.6, you would see the `Poetry could not find a pyproject.toml file in /Users/user/myproject or its parents` message but it wouldn't enforce the error.
