### ISSUE TITLE
[Bug]: NGINX `envsubst` regression in `0.7.0`

### ISSUE THREAD

**Issue by jrseliga** [jetpack-io/devbox#1565]
## Current Behavior (bug)
After upgrading to `0.7.0`  the variables in the file passed `--env-file` option of `services up` are not replaced by the `envsubst` command

## Expected Behavior (fix)
NGINX plugin `envsubst` respects `--env-file`

### Given
`.env.devbox`
```
NGINX_WEB_PORT=8004
```

`nginx.template`
```
# ..
server {
         # ..
         listen       $NGINX_WEB_PORT;
         # ..
}
# ..
```

### Unexpected outcome on `0.7.0`
`DEVBOX_USE_VERSION=0.7.0 devbox services up --env-file .env.devbox`

Results in (unexpected):
```
# ..
server {
         # ..
         listen       8081;
         # ..
}
# ..
```
### Expected outcome on `0.6.0`
`DEVBOX_USE_VERSION=0.6.0 devbox services up --env-file .env.devbox`

Results in (expected):
```
# ..
server {
         # ..
         listen       8004;
         # ..
}
# ..
```

**Comment by Lagoja** [comment]
Verified that I can repro on my machine. Looking into this now
