### ISSUE TITLE
[Bug]: postgres service won't start if directory longer than 63 chars

### ISSUE THREAD

**Issue by jay-aye-see-kay** [jetpack-io/devbox#1575]
**Current Behavior (bug)**
If the project's directory is longer than 63 characters postgres will fail to start. This is because it will attempt to create a socket path longer than 103 chars which the unix-y OSs don't allow.

**Expected Behavior (fix)**
Postgres should start by default regardless of path length.

**Additional context**
devbox version `0.7.0` on macOS `13.6`

**Repro steps**
```bash
REPRO_DIR="/tmp/code/company/project/subdir/team_name/my_app_v5_final_final_v1" # any path longer than 63 chars
mkdir -p $REPRO_DIR
cd $REPRO_DIR
devbox init
devbox add postgresql
devbox run -- initdb
devbox services up
```

See the error: `Unix-domain socket path "/private/tmp/code/company/project/subdir/team_name/my_app_v5_final_final_v1/.devbox/virtenv/postgresql/.s.PGSQL.5432" is too long (maximum 103 bytes)`

Clean up, `ctrl-c` and remove dir
```bash
cd ~
rm -rf $REPRO_DIR
```

**A potential fix**
My first thought for a fix would be to check if the path is tool long, if it is hash it and truncate it i.e. instead of the socket path being: `/private/tmp/code/company/project/subdir/team_name/my_app_v5_final_final_v1/.devbox/virtenv/postgresql/.s.PGSQL.5432`
you'd have something like this: `544ed7d2a475427192ad469175c78902ad0db4796e8849fcaca010ec5619d0fa-my_app_v5_final_final/.s.PGSQL.5432` (a hash of the whole thing for uniqueness, the standard suffix for familiarity, and a bit of the file name truncated so the whole thing is ~100 chars)

I'm not sure if you could implement this in the postgres plugin or it would have to be in core somewhere? I would be interesting in implementing a fix for this if you want the contribution and you can point me in the right direction.

**Comment by savil** [comment]
We had implemented a fix for this, but reverted it since it led to much complexity, and other downstream bugs. See https://github.com/jetpack-io/devbox/pull/1148

I believe you should be able to set the following for postgres:
```
// devbox.json
"env": {
   "PGHOST": <shorter-path>
}
```
You can see the example projects in that PR for how other plugins handle it.

**Comment by jay-aye-see-kay** [comment]
That seems like a fair trade off. Thanks :D
