### ISSUE TITLE
[Feature]: Publish a json schema for devbox.json

### ISSUE THREAD

**Issue by bbugh** [jetpack-io/devbox#1576]
Thanks for devbox, it's so great.

**Is your feature request related to a problem you're trying to solve? Please describe.**

Yes, having a schema allows for easy command line/CI verification to catch runtime errors before getting to CI, and editors can offer auto complete. 

**Describe the solution you'd like**
I'd love to see an official JSON schema published for the `devbox.json` configuration. 

**Describe alternatives you've considered**
Not having one 😢

**Additional context**

A good example of how to do this is devcontainers/spec. They publish here https://github.com/devcontainers/spec/blob/main/schemas/devContainer.schema.json

and you can reference it in as the schema using the github raw file:

```json
{ 
  "$schema": "https://raw.githubusercontent.com/devcontainers/spec/main/schemas/devContainer.schema.json"
}
```

In the case of devbox, you could also do it by tag so it's tracked alongside the same version of devbox

```json
{
  "$schema": "https://raw.githubusercontent.com/jetpack-io/devbox/0.7.1/schemas/devbox-config.schema.json",
  "packages": [
    "ffmpeg_6@6.0",
  ],
}
```

**Comment by mohsenari** [comment]
Hey @bbugh that's a great suggestion. I'll bring it up with the team and put it in our feature roadmap.

**Comment by airtonix** [comment]
btw this works right now: 

```json
{
  "$schema": "https://raw.githubusercontent.com/jetpack-io/devbox/main/.schema/devbox.schema.json",
  "packages": {
    "nodejs": "18",
    "go": "1.21.3"
  }
}
```

👍🏻

**Comment by mohsenari** [comment]
@airtonix awesome, I'm adding the schema validation to devbox's [vscode extension](https://marketplace.visualstudio.com/items?itemName=jetpack-io.devbox) so that even without the `$schema` field, it should validate if extension is installed.
