### ISSUE TITLE
[Bug]: `devbox generate direnv` fails when profile list is empty.

### ISSUE THREAD

**Issue by vic** [jetpack-io/devbox#1585]
**Current Behavior (bug)**
`devbox generate direnv` fails when `nix profile list` returns an empty string: 

```
$ devbox generate direnv
Ensuring packages are installed.
Error: error parsing "nix profile list" output: %!w(string=Index:              0): %!s(MISSING)
```

**Expected Behavior (fix)**
It should generate an .envrc file without failing.

**Additional context**

```
$ devbox version -v
Version:     0.5.2
Platform:    linux_amd64
Commit:      none
Commit Time: unknown
Go Version:  go1.20.4
Launcher:


$ cat devbox.json
{
  "packages": [
    "hello"
  ],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
```

**Comment by mohsenari** [comment]
Hey @vic I just tried this on an Ubuntu VM and not able to reproduce. I think `nix profile list` showing empty string, means your nix installation may not be correct. This is the output I get:
```bash
(devbox) mohsen@mohsen:~/code/examples/direnv$ nix profile list --extra-experimental-features nix-command
0 - - /nix/store/snsjmpdb8hs4jfp82wiykkbb9667rywr-nix-2.16.1

```

**Comment by mohsenari** [comment]
I'd say check your nix installation and make sure you have nix installed properly. Or remove and reinstall nix and try again. I doubt this is issue is caused by `devbox generate direnv`.

**Comment by vic** [comment]
i'm using NixOS, I do have a system profile but not a per user profiles.

**Comment by vic** [comment]
the error message sounds like it expects to parse something from the output of nix profile list. I believe the program should not fail when that output is empty for my current user.

**Comment by savil** [comment]
> devbox version -v
Version:     0.5.2

@vic this is a pretty old version
We did implement logic to handle two different `nix profile list` formats, since that changed a few months ago. see #1308. That shipped in Devbox 0.5.8 (see [release notes](https://github.com/jetpack-io/devbox/releases/tag/0.5.8))

Can you try updating Devbox and see if that fixes your issue?

**Comment by vic** [comment]
will try with newest version, my NixOS flake is using 23.05 release from nixpkgs and I just included pkgs.devbox from there. so maybe thats why its old. will try using a more recent devbox package.

**Comment by vic** [comment]
Ok, using [devbox 0.6.0](https://github.com/NixOS/nixpkgs/blob/53aa767c849b159cdb8c59dce4a5a44f167fc31b/pkgs/development/tools/devbox/default.nix#L8) from nixpkgs-unstable fixed it and `devbox generate direnv` now works as expected. Thank you! :)
