### ISSUE TITLE
[Bug]: Devbox information messages are fed into Atuin shell history

### ISSUE THREAD

**Issue by alvarogonzalez-packlink** [jetpack-io/devbox#1586]
**Current Behavior (bug)**

When devbox injects certain info messages (new release available, devbox environment needs update...) after a command, they get fed into my shell history. So, next time I try to use that command from the shell history, I get the command AND the info message together.

I use [Atuin](https://github.com/atuinsh/atuin/) as well as the standard zsh history to store my shell history.

Zsh stores the shell history correctly, but Atuin is feeded with devbox info messages.

Although at first one would think the fault could lie in Atuin, I've been using it for months and `devbox` is the only tool that feeds the wrong stuff stuff into my history, so I have to find what's the difference with other stuff.

So lets say I try to do an ssh connection and devbox finds I need to recompute my environment:
```
user@MAC ~ % ssh root@192.168.50.1
Info: Your devbox environment may be out of date. Please run
eval "$(devbox global shellenv --recompute)"
Info: Your devbox environment may be out of date. Please run
eval "$(devbox global shellenv --recompute)"
[...]
```

If now I pull my last command from my shell history, instead of finding the `ssh root@192.168.50.1` command, I'll find the info message has been added at the beginning of it too:
```
user@MAC ~ % Info: Your devbox environment may be out of date. Please run

eval "$(devbox global shellenv --recompute)"

Info: Your devbox environment may be out of date. Please run

eval "$(devbox global shellenv --recompute)"

ssh root@192.168.50.1
```

Another example from my history:
```
user@MAC ~ % Info: New devbox available: 0.5.7 -> v0.5.8. Please run `devbox version update`.
devbox version update
```

**Expected Behavior (fix)**
Only the command I've run is feed to my history

**Additional context**
- Shell: zsh 5.9 (x86_64-apple-darwin23.0)
- Shell history: Atuin 16.0.0
- Devbox: This has happened to me at least with versions 0.5.7 , 0.7.0 and 0.7.1 in darwin_arm64, but currently I have:
  ```
  Version:     0.7.1
  Platform:    darwin_arm64
  Commit:      9444baeabcb69c2ec8d67ce57536a44171843d9d
  Commit Time: 2023-10-19T19:11:54Z
  Go Version:  go1.21.3
  Launcher:    0.2.0
  ```

This is happening at least with my global devbox.json that's:
```
{
  "packages": [
    "tflint@latest",
    "argocd@latest",
    "tfsec@latest",
    "graphviz@latest",
    "httpie@latest",
    "krew@latest",
    "pre-commit@latest",
    "dive@latest",
    "yq-go@latest",
    "yamllint@latest",
    "vault@1.8.4",
    "colima@latest",
    "python@3.9",
    "pipx@latest",
    "kubernetes-helm-wrapped@3.11.3",
    "kubeconform@0.6.1",
    "kube-score@1.16.1",
    "python39Packages.numpy@latest",
    "bat@latest",
    "ripgrep@latest",
    "jq@latest",
    "circleci-cli@latest",
    "kubent@latest",
    "awscli2@latest",
    "mongodb-tools@4.2.0",
    "mongosh@1.4.2",
    "shellcheck@latest",
    "hadolint@latest",
    "kubectl@latest",
    "docker@latest",
    "ipcalc@latest",
    "wget@latest",
    "terraform-docs@latest",
    "gh@latest",
    "oxipng@latest",
    "pngquant@latest",
    "iperf@latest",
    "mysql-client@latest",
    "kustomize@latest",
    "meld@latest",
    "kubectx@latest",
    "github:mohsenari/gce#gce",
    "operator-sdk@latest",
    "htmlhint@latest",
    "ntp@latest",
    "lima@0.17.2",
    "neovim@latest",
    "python39Packages.pynvim@latest",
    "atuin@latest",
    "tshark@latest",
    "terraform@1.4.6",
    "mozjpeg@latest",
    "tcptraceroute@latest"
  ],
  "shell": {},
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
```

**Comment by savil** [comment]
How odd. Thanks for filing this issue. We try to print those to StdErr. I'm a bit confused why it would enter the command history for atuin.

**Comment by alvarogonzalez-packlink** [comment]
@savil Yep, super odd! Let me know anything I can do to debug it for you. I don't know where to begin to pull information on the Atuin side. Maybe I should check the hook it uses for feeding its history. 🤷

**Comment by alvarogonzalez-packlink** [comment]
Oh no @savil , it might have been totally a failure on my side (although there's something funky going on). I'm so sorry, close this if needed. 😢 

I just fund that although I have 0.7.1 installed, per some automation, the `eval "$(devbox global shellenv)"` command was being run with version 0.6.0.

How does running the 0.6.0 shellenv and then using the 0.7.0 version injects stuff on Atuin? I have no idea.

These are Atuin's hooks, by the way, but unless you see something very obvious, I don't think I should waste your time with this.
```sh
_atuin_preexec() {
    local id
    id=$(atuin history start -- "$1")
    export ATUIN_HISTORY_ID="$id"
}

_atuin_precmd() {
    local EXIT="$?"

    [[ -z "${ATUIN_HISTORY_ID:-}" ]] && return

    (RUST_LOG=error atuin history end --exit $EXIT -- $ATUIN_HISTORY_ID &) >/dev/null 2>&1
}
```

**Comment by savil** [comment]
Ah, I don't see how that should quite matter. @lagoja I believe you use atuin as well. Have you experienced this?

**Comment by Lagoja** [comment]
I have seen this before and similarly thought it was an issue with Atuin ... let me try to repro and see what's happening

**Comment by Lagoja** [comment]
So what seems to be happening is: 

1. I start typing a command, then hit the ⬆️ key to start Atuin's autocomplete
2. This displays the Atuin UI, I select the command I want from the history or exit the UI
3. Devbox prints some messages out to STDERR/STDOUT as I exit Atuin, either because my global shell is out of date or because I have DEVBOX_DEBUG=1 enabled
4. Atuin appends the autocompleted command at the end of my prompt, and thus at the end of all this output
5. Now when I hit Enter, it sends all _everything_ to the shell -- both the Devbox output, and the command I was typing. This understandably fails. 

You can repro this by installing atuin globally, and then exporting DEVBOX_DEBUG=1

**Comment by Lagoja** [comment]
@alvarogonzalez-packlink -- We have some work planned this cycle to fix how the binary wrappers in Devbox work, that should address this issue. I'm going to mark it planned. 

For now, Atuin should work correctly as long as DEVBOX_DEBUG is unset, and your environment is recomputed after an update. I'll update this thread once we've released the fix

**Comment by alvarogonzalez-packlink** [comment]
Great! Just ping me if you need any testing.

**Comment by Lagoja** [comment]
Hey @alvarogonzalez-packlink, I think this issue should be resolved in the pre-release version of Devbox 0.8.0. This release removes our binary wrappers from packages installed with Devbox, so Atuin should no longer generate any Devbox related text during use. 

To try out the new pre-release, export the following variable in your shell. I recommend putting it in your rc file: 

```bash
export DEVBOX_USE_VERSION=0.8.0-dev
```

From there, you may need to recompute and update your `devbox global` profile at least once to remove the binwrappers. After this, you should no longer see any Devbox output when using Atuin.

Please let me know if that works!

**Comment by alvarogonzalez-packlink** [comment]
@Lagoja Sorry, I was out traveling. I'll upgrade and test :)

**Comment by alvarogonzalez-packlink** [comment]
@Lagoja : Well, I have to say that although devbox starts more or less in the same time, running apps managed by devbox is now WAY WAY FASTER. That might be probably related to the fact that I have Crowdstrike intercepting a lot of calls...

0.7.1 shell startup (with some "echo debugging" ;) ):
```
Last login: Mon Nov  6 15:24:53 on ttys006
start devbox
240ms
start [internal tool]
53ms
start vars, alias and stuff
24ms
start bashcompinit completion
24ms
start aws completion
26ms
start kube completion
23ms
start atuin
235ms
======
TOTAL TIME: 798ms
```

0.8.0-dev:
```
Last login: Mon Nov  6 16:23:26 on ttys006
start devbox
237ms
start [internal tool]
47ms
start vars, alias and stuff
22ms
start bashcompinit completion
23ms
start aws completion
25ms
start kube completion
22ms
start atuin
38ms
======
TOTAL TIME: 588ms
```
----

Testing some other apps using [this zsh time format](https://superuser.com/a/767491)...

**Hadolint** goes from 140ms to 26ms

hadolint in 0.7.1
```
% time hadolint ./Dockerfile
hadolint ./Dockerfile   0.01s  user 0.01s system 12% cpu 0.140 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                39376 KB
page faults from disk:     3
other page faults:         3315
```
hadolint in 0.8.0-dev
```
% time hadolint ./Dockerfile
hadolint ./Dockerfile   0.01s  user 0.01s system 68% cpu 0.026 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                39344 KB
page faults from disk:     0
other page faults:         2988
```

**yamlfixer** (the python app) running in a folder with lots of yaml files goes from 3 min 43 sec to 1 min 21 sec:

yamlfixer and 0.7.1:
```
time ~/.local/pipx/venvs/yamlfixer-opt-nc/bin/yamlfixer -n -r 5 ./
~/.local/pipx/venvs/yamlfixer-opt-nc/bin/yamlfixer -n -r 5 ./   68.51s  user 20.15s system 39% cpu 3:42.55 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                19808 KB
page faults from disk:     4203
other page faults:         3507284
```

yamlfixer and 0.8.0-dev:
```
% time ~/.local/pipx/venvs/yamlfixer-opt-nc/bin/yamlfixer -n -r 5 ./
~/.local/pipx/venvs/yamlfixer-opt-nc/bin/yamlfixer -n -r 5 ./   60.77s  user 16.21s system 94% cpu 1:21.37 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                19648 KB
page faults from disk:     7
other page faults:         3040663
```

I see the speedup is specially notable when there are lots of calls to dependencies: systems, bash or python scripts. I see also Crowdstrike hitting the CPU significantly less. While running the yamlfixer example, with 0.7.1 I had a +50% CPU use, and with 0.8.0-dev went down in more half to around 20-23%.

Note that the user and system time is quite similar in both, but the CPU use goes up, so there's something else _cough crowdstrike cough_  going on.

**Comment by Lagoja** [comment]
Closing this as complete since the 0.8.2 release. Thank you for reporting!
