### ISSUE TITLE
[Feature]: Use a human friendly format for devbox.json (e.g. devbox.yaml)

### ISSUE THREAD

**Issue by glennpratt** [jetpack-io/devbox#1590]
**Is your feature request related to a problem you're trying to solve? Please describe.**

To me, JSON is not a human developer friendly format. It's certainly fine for APIs, but for a text
file committed to my repo, I would expect comments and flexible comma placement at the minimum.

For a concrete example, I can't describe why some packages are pinned to a SHA and when that
should change.

```
{
  "packages": [
    "argocd@2.8.3",
    "coreutils@latest",
    "jq@latest",
    "kind@0.17",
    "kubectl@1.25",
    "kubernetes-helm@3.9",
    "linode-cli@latest",
    "github:NixOS/nixpkgs/9c9f0e79906beccc02a6a35f41f584fcd1b4c455#pulumi",
    "github:NixOS/nixpkgs/9c9f0e79906beccc02a6a35f41f584fcd1b4c455#pulumiPackages.pulumi-language-python",
    "python311Packages.black@latest",
    "python311Packages.pip@latest",
    "python@3.11",
    "s3cmd@latest",
    "shellcheck@latest",
    "teleport@latest",
    "tilt@latest",
    "yq-go@4.33",
    "age@latest"
  ]
}
```

**Describe the solution you'd like**

YAML seems like an obvious choice, since it's almost entirely compatible with JSON and JSON
support can easily be kept around with little impact.

Support devbox.yaml. YAML version is fairly insignificant.

**Describe alternatives you've considered**

TOML, INI, personally prefer YAML and it's parity with JSON is valuable.

Anybody that wants to keep using JSON can, even if someone wanted to format devbox.yaml like JSON, it would be fine.

**Additional context**
None

**Comment by gcurtis** [comment]
Hey @glennpratt, thanks for the feedback. We're adding support for comments and trailing commas in the upcoming release with #1539. We don't have any immediate plans to add YAML or other config languages right now, but hopefully these JSON changes get you some of what you're looking for.

**Comment by glennpratt** [comment]
Thanks, I see that is far more complicated than I considered!

**Comment by d-enk** [comment]
@glennpratt reopen please

I don't see any so complicated, even if it was on the verge of the impossible

For me personally the main pain is `shell.scripts`

Json require `"` `\` escaping and does not support multiline
So if you need to write one command split into lines, It looks like this
```json
{
  "shell": {
    "scripts": {
      "some": [
        "cd path/to/something && \\",
        "do_something \\",
        "\"$(calculate_args)\" \\",             
        "something_arg_1 \\",
        "something_arg_2",
      ]
    }
  }
}
```

What would look simple in `yaml`
```yaml
shell:
  scripts:
    some: |
      cd path/to/something && \
      do_something \
      "$(calculate_args)" \
      something_arg_1 \
      something_arg_2

```

Currently yaml preferable in any configs
`gitlab-ci.yml`, `.github/workflows`, `k8s` ...

**Comment by justinTM** [comment]
definitely needs to be re-opened. at the very least it should be a user option. JSON is fine for legacy stuff but there's a reason makefiles don't wrap every line in quotes: it goes against the natural essence of sanity.
