### ISSUE TITLE
[Feature]: Dev Dependencies and other (config) Stages

### ISSUE THREAD

**Issue by spe888** [jetpack-io/devbox#1606]
**Is your feature request related to a problem you're trying to solve? Please describe.**
It would be nice to have a option to define default and dev dependencies, or other stages in the devbox.json Otherwise I am forced to create another folder with a devbox.json there and replicate most of the content anyway. 

**Describe the solution you'd like**
Maybe something similar to this (or something entirely different): 

```
{
  "packages": [
    "bun@latest",
    "nodejs@latest",
  ],
  "devPackages": [
    "awscli@latest",
    "awsebcli@latest",
    "rsync@latest",
    "zip@latest",
  ],
  "shell": {
    "init_hook": [
      "if [[ ! -d node_modules ]]; then bun install; fi"
    ],
    "scripts": {},
    "devScripts": {}
  }
}
```

**Describe alternatives you've considered**
A alternative would be to use the --config flag for specifing another devbox json file. E.g.: 
```
devbox --config devbox.stage.json run node --version
devbox --config devbox.stage.json shell
devbox shell # default config
```

**Comment by dephiros** [comment]
This seems similar to https://github.com/jetpack-io/devbox/issues/1227

**Comment by spe888** [comment]
@dephiros True, this seems very similar, I'll close this one in favor of #1227
