### ISSUE TITLE
[Bug]: `devbox run <script>` loses variables

### ISSUE THREAD

**Issue by justinTM** [jetpack-io/devbox#1611]
**Current Behavior (bug)**
1. set variable in `~/.zshrc`, eg. `GITLAB_ACCESS_TOKEN`
2. start a devbox shell, and check the variable came with it:
    ```console
    justin@Justins-MacBook-Pro frontend % devbox shell
    (devbox) justin@otp015347ots frontend % echo GITLAB_ACCESS_TOKEN=$GITLAB_ACCESS_TOKEN
    GITLAB_ACCESS_TOKEN=glpat-XXXXXXXXXXXXXX
    ```
3. now _run a devbox script_ and the variable disappears :(
    ```console
    (devbox) justin@otp015347ots frontend % devbox run plan
    GITLAB_ACCESS_TOKEN=
    ```

**Expected Behavior (fix)**
I assumed if the devbox shell had it, then any devbox script would inherit it? idk

**Additional context**
`devbox version -v`:
```
Version:     0.7.1
Platform:    darwin_arm64
Commit:      9444baeabcb69c2ec8d67ce57536a44171843d9d
Commit Time: 2023-10-19T19:11:54Z
Go Version:  go1.21.3
Launcher:    0.2.0
```
a copy of your `devbox.json` file.
```json
{
  "packages": [
    "git@latest",
    "vim@latest",
    "terraform@1.5.7",
    "docker@latest",
    "go@latest",
    "sass@latest",
    "awscli@latest",
    "act@latest",
    "jq@latest",
    "terragrunt@latest"
  ],
  "shell": {
    "init_hook": [
      "source parameters/dev.env",
      "source parameters/local.env",
      "if [[ -z $AWS_SECRET_ACCESS_KEY ]]; then aws configure; fi"
    ],
    "scripts": {
      "gitinfo": [
        "./.github/scripts/git-info.sh"
      ],
      "tffmt": [
        "(cd terraform && terraform fmt)"
      ],
      "tfplan": [
        "(cd terraform && terraform plan)"
      ],
      "tfvalidate": [
        "(cd terraform && terraform validate)"
      ],
      "plan": [
        "echo GITLAB_ACCESS_TOKEN=$GITLAB_ACCESS_TOKEN",
        "./gitlab-ci-local \"Plan Dev\" --variable CI_PROJECT_ID=$CI_PROJECT_ID --variable CI_JOB_TOKEN=$GITLAB_ACCESS_TOKEN"
      ]
    }
  }
}
```

**Comment by savil** [comment]
@justinTM Thanks for filing this issue.

The difference here is that `devbox shell` runs in your host shell, whereas `devbox run` uses the `sh`. 

The idea is that `devbox shell` is used for interactive work and so engineers would prefer using their shell of choice. Whereas `devbox run` is for scripts that are shared by a team and/or CICD, so would benefit from a standardized shell that they run in, which `sh` provides as its most likely to be available on all systems.

For environment variables, you'd like in both places I'd suggest setting them in the `env` field in `devbox.json` or doing `export NAME=VALUE` in the `init_hooks` field of `devbox.json`.

**Comment by justinTM** [comment]
hey @savil thanks for the prompt reply and the helpful explanation!

question for ya: for something like a token variable -- which shouldn't be committed to code and will change person-to-person -- what would you recommend?

...i obviously don't know shell stuff very well :)

**Comment by Lagoja** [comment]
@justinTM There's a couple options for letting users set variables that shouldn't be committed to code:

1. **For User Specific Variables:** There is a `--env-file` flag that can be used to pass in variables from a local `.env` file. In your case, the user could set the Gitlab token in a `.env` file, and then pass it into their `devbox shell` using `devbox shell --env-file .env`. See (our docs) [https://www.jetpack.io/devbox/docs/guides/scripts/#run-scripts-with-custom-environment-variables] for more details

2. **For Shared Variables:** We're working on a Devbox Secrets service that would let you set per-project secrets, and then have them automatically apply to your Devbox shell or scripts whenever you start it. This would let users access secret variables without having to check them into code. If you're interested, you can reach out to me on our Discord for more details!
