### ISSUE TITLE
Print nix reminder when starting devbox shell

### ISSUE THREAD

**Issue by loreto** [jetpack-io/devbox#162]
Nix prints:
```
---- Reminders -----------------------------------------------------------------
[ 1 ]
Nix won't work in active shell sessions until you restart them.
```

Devbox should print something similar.

**Comment by Lagoja** [comment]
We currently print this after running our Nix installation with `devbox setup nix`, so I think this we can close this. We also now notify developers to restart their shell or source `shellenv` if they add a new package while in a Devbox Shell. 

Will open a separate issue if we need to print additional messages.
