### ISSUE TITLE
[Bug]: Security Issues in generated Dockerfile (Critical+High)

### ISSUE THREAD

**Issue by spe888** [jetpack-io/devbox#1638]
**Current Behavior (bug)**
Running `devbox generate dockerfile` or `devbox generate devcontainer` triggers some security scanning tools (e.g. trivy). Trivy for example classifies some of the issues as critical/high (I've reduced some of the output for the sake of readability): 

```
CRITICAL: Using 'sudo' in Dockerfile should be avoided
Avoid using 'RUN' with 'sudo' commands, as it can lead to unpredictable behavior.
See https://avd.aquasec.com/misconfig/ds010
RUN sudo chown -R "${DEVBOX_USER}:${DEVBOX_USER}" /code
```

```
HIGH: Specify at least 1 USER command in Dockerfile with non-root user as argument
Running containers with 'root' user can lead to a container escape situation. It is a best practice to run containers as non-root users, which can be done by adding a 'USER' statement to the Dockerfile.
See https://avd.aquasec.com/misconfig/ds002
```

**Expected Behavior (fix)**
Security issues with a high and critical need to be fixed. You can reproduce the issue by running: `trivy config .`

The problems could be maybe avoided by generating a Dockerfile like this (not tested yet): 

```
FROM jetpackio/devbox:latest
USER ${DEVBOX_USER}:${DEVBOX_USER}
WORKDIR /code
COPY --chown="${DEVBOX_USER}:${DEVBOX_USER}" devbox.json devbox.json
COPY --chown="${DEVBOX_USER}:${DEVBOX_USER}" devbox.lock devbox.lock
RUN devbox run -- echo "Installed Packages."
CMD ["devbox", "shell"]
```

**Additional context**
Devbox Version: 0.8.2

**Comment by Lagoja** [comment]
Closing this since the PR was merged, thanks for raising and providing a fix for this issue @iocron!
