### ISSUE TITLE
[Bug]: Infinite `init_hook` execution if `devbox services start` is called

### ISSUE THREAD

**Issue by mikenikles** [jetpack-io/devbox#1651]
**Current Behavior (bug)**
If I call `devbox services start` within the `init_hook` array of commands, the shell never starts and instead ends up in an infinite loop.

**Expected Behavior (fix)**
The shell starts and services are up and running.

**Additional context**
`devbox version -v`

```
devbox version -v
Version:     0.8.2
Platform:    darwin_arm64
Commit:      33ea788cb4dbf6958208669c9e4df9c1e858ad2c
Commit Time: 2023-11-15T00:23:52Z
Go Version:  go1.21.3
Launcher:    0.2.0
```

`devbox.json`

```
{
  "packages": [],
  "shell": {
    "init_hook": [
      "echo 'This comes from the init_hook.'",
      "devbox services start"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

**Comment by savil** [comment]
@mikenikles thanks for reporting!

@mikeland73 I think this is a result of the change to start a new "devbox shell" environment with each `devbox services start`. We may need some recursion protection.
