### ISSUE TITLE
[Bug]: Unable to update a nix flake package with devbox global update

### ISSUE THREAD

**Issue by djgoku** [jetpack-io/devbox#1658]
**Current Behavior (bug)**
Running `devbox global update` is failing with `emacs-overlay`:

```
% DEVBOX_DEBUG=1 devbox global update
2023/11/30 18:38:15 findProjectDir: path is 
2023/11/30 18:38:15 finding devbox.json in dir: /Users/dj_goku
2023/11/30 18:38:15 findProjectDir: path is 
2023/11/30 18:38:15 finding devbox.json in dir: /Users/dj_goku
2023/11/30 18:38:15 findProjectDir: path is /Users/dj_goku/.local/share/devbox/global/default
Info: Already up-to-date ripgrep@latest 13.0.0
Info: Already up-to-date git@latest 2.42.0
Info: Attempting to upgrade github:nix-community/emacs-overlay#packages.aarch64-darwin.emacs-git using `nix profile upgrade`
2023/11/30 18:38:15 Failed to resolve store path for x86_64-linux with storeHash 5vvmc3pqbf1s39zw48nvw93yrmj0fr4m. Error is exit status 1.
Info: Already up-to-date awscli2@latest 2.13.33
Info: Already up-to-date cmake@latest 3.27.7
Info: Already up-to-date libtool@latest 2.4.7
Info: Already up-to-date gnupg@2.3.7 2.3.7
2023/11/30 18:38:16 running command: /nix/var/nix/profiles/default/bin/nix search --json github:nix-community/emacs-overlay#packages.aarch64-darwin.emacs-git --extra-experimental-features ca-derivations --option experimental-features nix-command flakes fetch-closure
Info: Running "nix flake update"
Error: error running "nix flake update": warning: Invalid flake input '/Users/dj_goku/.local/share/devbox/global/default/.devbox/gen/flake'. To update a specific flake, use 'nix flake update --flake /Users/dj_goku/.local/share/devbox/global/default/.devbox/gen/flake' instead.
error: invalid flake input path element '.local'
: exit status 1

2023/11/30 18:38:16 Command stderr: 
2023/11/30 18:38:16 
ExecutionID:1a1da338c0f243868266493eade56028
error running "nix flake update": warning: Invalid flake input '/Users/dj_goku/.local/share/devbox/global/default/.devbox/gen/flake'. To update a specific flake, use 'nix flake update --flake /Users/dj_goku/.local/share/devbox/global/default/.devbox/gen/flake' instead.
error: invalid flake input path element '.local'
: exit status 1
go.jetpack.io/devbox/internal/nix.FlakeUpdate
	go.jetpack.io/devbox/internal/nix/upgrade.go:36
go.jetpack.io/devbox/internal/impl.(*Devbox).Update
	go.jetpack.io/devbox/internal/impl/update.go:69
go.jetpack.io/devbox/internal/boxcli.updateCmdFunc
	go.jetpack.io/devbox/internal/boxcli/update.go:76
go.jetpack.io/devbox/internal/boxcli.updateCmd.func1
	go.jetpack.io/devbox/internal/boxcli/update.go:34
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
go.jetpack.io/devbox/internal/boxcli/midcobra.(*midcobraExecutable).Execute
	go.jetpack.io/devbox/internal/boxcli/midcobra/midcobra.go:61
go.jetpack.io/devbox/internal/boxcli.Execute
	go.jetpack.io/devbox/internal/boxcli/root.go:112
go.jetpack.io/devbox/internal/boxcli.Main
	go.jetpack.io/devbox/internal/boxcli/root.go:135
main.main
	./main.go:11
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_arm64.s:1197
2023/11/30 18:38:16 findProjectDir: path is 
2023/11/30 18:38:16 finding devbox.json in dir: /Users/dj_goku
```

**Expected Behavior (fix)**
An updated emacs would be built.

**Additional context**

```
% devbox version
0.8.2
```

devbox.json:
```
{
  "packages": [
    "ripgrep@latest",
    "git@latest",
    "github:nix-community/emacs-overlay#packages.aarch64-darwin.emacs-git",
    "awscli2@latest",
    "cmake@latest",
    "libtool@latest",
    "gnupg@2.3.7"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

**Comment by winderlopezg** [comment]
> **Current Behavior (bug)** Running `devbox global update` is failing with `emacs-overlay`:
> 
> ```
> % DEVBOX_DEBUG=1 devbox global update
> 2023/11/30 18:38:15 findProjectDir: path is 
> 2023/11/30 18:38:15 finding devbox.json in dir: /Users/dj_goku
> 2023/11/30 18:38:15 findProjectDir: path is 
> 2023/11/30 18:38:15 finding devbox.json in dir: /Users/dj_goku
> 2023/11/30 18:38:15 findProjectDir: path is /Users/dj_goku/.local/share/devbox/global/default
> Info: Already up-to-date ripgrep@latest 13.0.0
> Info: Already up-to-date git@latest 2.42.0
> Info: Attempting to upgrade github:nix-community/emacs-overlay#packages.aarch64-darwin.emacs-git using `nix profile upgrade`
> 2023/11/30 18:38:15 Failed to resolve store path for x86_64-linux with storeHash 5vvmc3pqbf1s39zw48nvw93yrmj0fr4m. Error is exit status 1.
> Info: Already up-to-date awscli2@latest 2.13.33
> Info: Already up-to-date cmake@latest 3.27.7
> Info: Already up-to-date libtool@latest 2.4.7
> Info: Already up-to-date gnupg@2.3.7 2.3.7
> 2023/11/30 18:38:16 running command: /nix/var/nix/profiles/default/bin/nix search --json github:nix-community/emacs-overlay#packages.aarch64-darwin.emacs-git --extra-experimental-features ca-derivations --option experimental-features nix-command flakes fetch-closure
> Info: Running "nix flake update"
> Error: error running "nix flake update": warning: Invalid flake input '/Users/dj_goku/.local/share/devbox/global/default/.devbox/gen/flake'. To update a specific flake, use 'nix flake update --flake /Users/dj_goku/.local/share/devbox/global/default/.devbox/gen/flake' instead.
> error: invalid flake input path element '.local'
> : exit status 1
> 
> 2023/11/30 18:38:16 Command stderr: 
> 2023/11/30 18:38:16 
> ExecutionID:1a1da338c0f243868266493eade56028
> error running "nix flake update": warning: Invalid flake input '/Users/dj_goku/.local/share/devbox/global/default/.devbox/gen/flake'. To update a specific flake, use 'nix flake update --flake /Users/dj_goku/.local/share/devbox/global/default/.devbox/gen/flake' instead.
> error: invalid flake input path element '.local'
> : exit status 1
> go.jetpack.io/devbox/internal/nix.FlakeUpdate
> 	go.jetpack.io/devbox/internal/nix/upgrade.go:36
> go.jetpack.io/devbox/internal/impl.(*Devbox).Update
> 	go.jetpack.io/devbox/internal/impl/update.go:69
> go.jetpack.io/devbox/internal/boxcli.updateCmdFunc
> 	go.jetpack.io/devbox/internal/boxcli/update.go:76
> go.jetpack.io/devbox/internal/boxcli.updateCmd.func1
> 	go.jetpack.io/devbox/internal/boxcli/update.go:34
> github.com/spf13/cobra.(*Command).execute
> 	github.com/spf13/cobra@v1.7.0/command.go:940
> github.com/spf13/cobra.(*Command).ExecuteC
> 	github.com/spf13/cobra@v1.7.0/command.go:1068
> github.com/spf13/cobra.(*Command).Execute
> 	github.com/spf13/cobra@v1.7.0/command.go:992
> go.jetpack.io/devbox/internal/boxcli/midcobra.(*midcobraExecutable).Execute
> 	go.jetpack.io/devbox/internal/boxcli/midcobra/midcobra.go:61
> go.jetpack.io/devbox/internal/boxcli.Execute
> 	go.jetpack.io/devbox/internal/boxcli/root.go:112
> go.jetpack.io/devbox/internal/boxcli.Main
> 	go.jetpack.io/devbox/internal/boxcli/root.go:135
> main.main
> 	./main.go:11
> runtime.main
> 	runtime/proc.go:267
> runtime.goexit
> 	runtime/asm_arm64.s:1197
> 2023/11/30 18:38:16 findProjectDir: path is 
> 2023/11/30 18:38:16 finding devbox.json in dir: /Users/dj_goku
> ```
> 
> **Expected Behavior (fix)** An updated emacs would be built.
> 
> **Additional context**
> 
> ```
> % devbox version
> 0.8.2
> ```
> 
> devbox.json:
> 
> ```
> {
>   "packages": [
>     "ripgrep@latest",
>     "git@latest",
>     "github:nix-community/emacs-overlay#packages.aarch64-darwin.emacs-git",
>     "awscli2@latest",
>     "cmake@latest",
>     "libtool@latest",
>     "gnupg@2.3.7"
>   ],
>   "shell": {
>     "init_hook": [
>       "echo 'Welcome to devbox!' > /dev/null"
>     ],
>     "scripts": {
>       "test": [
>         "echo \"Error: no test specified\" && exit 1"
>       ]
>     }
>   }
> }
> ```
confirmed seems to be the nix version, I solved it in the following way with 
```shell
 devbox global add nix
```

**Comment by Lagoja** [comment]
Hey @djgoku @winderlopezg, We confirmed this is an issue with Nix 2.19. This version of Nix made a breaking change to how flakes are updated. We have a new release slotted for today which should have a fix for this issue

**Comment by djgoku** [comment]
@Lagoja Thanks devbox 0.8.3 fixed my issues!
