### ISSUE TITLE
[Bug]: internal error

### ISSUE THREAD

**Issue by yinqinghe** [jetpack-io/devbox#1684]
![image](https://github.com/jetpack-io/devbox/assets/70678389/9e1c5daf-7e39-42a3-b042-01e9b0239138)

**Comment by savil** [comment]
@yinqinghe thanks for reporting the bug. As suggested in the output shared, could you re-run it with `DEVBOX_DEBUG=1` and share the more detailed output?

**Comment by savil** [comment]
Closing since its not actionable for now
