### ISSUE TITLE
[Package Issue Report]: libcap

### ISSUE THREAD

**Issue by carlotm** [jetpack-io/devbox#1697]
**Are you requesting a new package or reporting an issue on an existing one?**

I am reporting an issue on an existing package

**If reporting an issue on an existing one, what is the name of the package?**

libcap

**What changes are you requesting?**

When I install libcap, I would expect to find its headers files in `$DEVBOX_PACKAGES_DIR/include/`

**Additional context**

I am compiling an Erlang project and I get this error:
```
...
c_src/exec.hpp:22:10: fatal error: sys/capability.h: No such file or directory
   22 | #include <sys/capability.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

I don't have that header file in my include dir

```
carloratm@localhost> find -L $DEVBOX_PACKAGES_DIR -iname capability.h
carloratm@localhost>
```

The file is present in the nix store

```
carloratm@localhost> find -L /nix/store/*libcap* -iname capability.h
/nix/store/n0r5z0w1j3m0z8980hgg2rjkh617v1md-libcap-2.66-dev/include/sys/capability.h
carloratm@localhost>
```

Any  idea?
Kind Regards

**Comment by carlotm** [comment]
Reading #1543 I suspect it is happening because libcap is a split package, but I am not sure

**Comment by Lagoja** [comment]
Per discussion on Discord -- this issue can be resolved by installing the `dev` output: 

```
devbox add flake:nixpkgs#libcap^out,dev
```
