### ISSUE TITLE
Devbox shell PATH should take precedence over existing binaries

### ISSUE THREAD

**Issue by methyl** [jetpack-io/devbox#17]
Hey!

Just been testing devbox and the experience so far is really smooth. I stumbled upon 3 things that confused me:
1. `devbox add package` failed with `Package not found` until I opened a new terminal. It's kind of documented, but maybe there is a way for a better error? Anyway, that's a nit.
2. `devbox shell` first run can take quite some time and there is no progress bar, but we already have https://github.com/jetpack-io/devbox/issues/7
3. Which is this issue really about.

It seems the initial run of `devbox shell` does not spawn the shell, instead it exists once it completes package initialization. Here's the terminal log that shows the issue:

```sh
lucjansuski@MacBook-Pro-3 ~ % cd /tmp
lucjansuski@MacBook-Pro-3 /tmp % mkdir test
lucjansuski@MacBook-Pro-3 /tmp % cd test
lucjansuski@MacBook-Pro-3 test % devbox init
lucjansuski@MacBook-Pro-3 test % devbox add python
lucjansuski@MacBook-Pro-3 test % devbox shell
this path will be fetched (7.93 MiB download, 49.47 MiB unpacked):
  /nix/store/3j1bsklak6p752nhys18n0p9i3grq1bz-python-2.7.18
copying path '/nix/store/3j1bsklak6p752nhys18n0p9i3grq1bz-python-2.7.18' from 'https://cache.nixos.org'...
Starting a devbox shell...
lucjansuski@MacBook-Pro-3 test % which python
/Users/lucjansuski/.asdf/shims/python
lucjansuski@MacBook-Pro-3 test % devbox shell
Starting a devbox shell...
MacBook-Pro-3:test lucjansuski$ which python
/nix/store/3j1bsklak6p752nhys18n0p9i3grq1bz-python-2.7.18/bin/python
MacBook-Pro-3:test lucjansuski$
```

I'm on `macOS Monterey 12.5`.

**Comment by loreto** [comment]
Looking at this in more detail. I think the shell did start on the first try, but there's "interferance" from `asdf` as @rdlu is suggesting. Basically, I think the `asdf` path is taking precedence over the `devbox` path – I'm going to see if we can ensure the PATH precedence is set up correctly whenever you call `devbox shell`

**Comment by raptium** [comment]
+1 I have the same issue with `pyenv`.

**Comment by rbudiharso** [comment]
Happens to me too, with 3 different version of ruby, devbox 0.14.0, `which ruby` returns path from asdf (`ruby --version` shows 3.4.1), devbox installed ruby is 3.3.6 but it's on different path (`.devbox/nix/profile/default/bin/ruby`) while `devbox info ruby` set different path and show different ruby version (3.4.2) 🤯

![Image](https://github.com/user-attachments/assets/339d9db5-20cc-4885-b51d-d2e019e2c4dc)

![Image](https://github.com/user-attachments/assets/f12bd4ed-4b55-4568-acf2-1ed29dcfa089)
