### ISSUE TITLE
[Bug]: Nixhub is constantly reloading

### ISSUE THREAD

**Issue by ajitid** [jetpack-io/devbox#1704]
**Current Behavior (bug)**
[Nixhub](https://www.nixhub.io/) website is constantly reloading. Tried on Firefox and Chrome on Windows and Chrome on Android

**Expected Behavior (fix)**
Should load up normally

**Comment by savil** [comment]
Thanks for reporting. We're looking into this!

**Comment by savil** [comment]
It should be fixed now
