### ISSUE TITLE
[Bug]: empty redis log

### ISSUE THREAD

**Issue by greg0ire** [jetpack-io/devbox#1727]
**Current Behavior (bug)**
When running `devbox services up` with the redis plugin, I see no logs in the process-compose interface. There is a `redis.log` file, but it's empty. The service itself seems to be working fine though.

When I run `/nix/store/dl92rjch7rc01v3b4s9a1h5q035np6bl-redis-6.2.6/bin/redis-server 127.0.0.1:6379`, I see logs

**Expected Behavior (fix)**
I would expect either a non-empty redis.log file, and/or logs in the process-compose UI 

**Additional context**
Please include the output of `devbox version -v` and
a copy of your `devbox.json` file.

```
$ devbox version -v
Version:     0.8.5
Platform:    linux_amd64
Commit:      34c5f3551a6534a52bbf4112a040a8427e20fe9b
Commit Time: 2023-12-21T00:52:48Z
Go Version:  go1.21.5
Launcher:    0.2.1
```

```json
{
  "packages": [
    "go_1_21@latest",
    "redis@6.2",
    "minio@2023-11-01T18-37-25Z"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

**Comment by gcurtis** [comment]
Hi @greg0ire, by default Devbox configures redis to put logs in `.devbox/virtenv/redis/redis.log`. You can edit `devbox.d/redis/redis.conf` and comment out the `logfile redis.log` line to get logs to go to standard out. That should let process compose capture them.

That said, I don't think Devbox's default behavior here makes much sense. It might predate the process compose integration. I'll leave this open and see about making logs default to stdout.
