### ISSUE TITLE
[Feature]: RSS feed for the DevLog

### ISSUE THREAD

**Issue by mmartinortiz** [jetpack-io/devbox#1739]
While browsing through the Jetpack.io website I realised that there is a [devlog](https://www.jetpack.io/blog/devlog/) with regular updates about the development of devbox. There is an option for subscribing to a newsletter, but I would prefer to consume this kind of content via RSS.

Is there an RDD Feed available for the devlog? Could be one be integrated in the website?

**Comment by Lagoja** [comment]
You can find feeds at: 

Devlog: https://www.jetpack.io/blog/devlog/rss/
Blog: https://www.jetpack.io/blog/rss/

**Comment by mmartinortiz** [comment]
Thanks, I completely forgot to try with `/rss` in the URL.
