### ISSUE TITLE
[Feature]: Allow rolling back / downgrading devbox

### ISSUE THREAD

**Issue by jay-aye-see-kay** [jetpack-io/devbox#1746]
**Is your feature request related to a problem you're trying to solve? Please describe.**
Version `0.8.6` had a bug impacting `fish` users. This was fixed quickly but it would be very helpful to be able to temporarily rollback the installed devbox version if similar issues happen again.

**Describe the solution you'd like**
Be able to install a specified previous version of devbox without resorting to `nix profile install nixpkgs/dd5621df6dcb90122b50da5ec31c411a0de3e538#devbox`.

Something like `export DEVBOX_VERSION=0.8.5 devbox version update` is what I tried first. This would be my preferred way to access the feature.

**Describe alternatives you've considered**
- A command line flag as well as (or instead of) an env variable would be fine too. That may make it more discoverable, which I'm not sure if that's a good or bad thing - it's not a common workflow, just a rare escape hatch.
- Have the installer script respect the `DEVBOX_VERSION` env variable again, harder to use, but would be okay if that's easier to implement.

**Additional context**
- [description of the issue](https://github.com/jetpack-io/devbox/issues/1744)
- [the fix](https://github.com/jetpack-io/devbox/commit/51c8829f53223d094df4a296b11c2a9e056866b0)

**Comment by savil** [comment]
@jay-aye-see-kay The installer script should respect `DEVBOX_USE_VERSION=0.8.5`. Does that work for you? 

@Lagoja We could add DEVBOX_USE_VERSION to the Devbox FAQ https://www.jetpack.io/devbox/docs/faq/

**Comment by savil** [comment]
Just to clarify usage:
```
export DEVBOX_USE_VERSION=0.8.5
```
will pin that version of Devbox for all devbox commands.

unsetting it will use the latest Devbox version

**Comment by jay-aye-see-kay** [comment]
Oh fantastic I had the variable name wrong. I had a memory of using it but couldn't find it documented anywhere, so assumed it had been removed.

Confirming that both of these appear to work for me:
```bash
export DEVBOX_USE_VERSION=0.8.5; curl -fsSL https://get.jetpack.io/devbox | bash
export DEVBOX_USE_VERSION=0.8.5; devbox version update
```

If you could add it to the FAQ that would be awesome

**Comment by Lagoja** [comment]
This has now been updated in the FAQ, and in our Installation docs: 

https://www.jetpack.io/devbox/docs/faq/
https://www.jetpack.io/devbox/docs/installing_devbox/
