### ISSUE TITLE
[Question]: Can devbox support GNU Guix as a backend store instead of Nix?

### ISSUE THREAD

**Issue by TxGVNN** [jetpack-io/devbox#1758]
Hi Devbox team,

I recently came across devbox and decided to give it a try. I'm curious to know if it's possible to use devbox to install packages from Guix instead of Nix. Since I'm already using Guix and I would prefer not to install Nix alongside because of lack of disk, you know it :(

This is just a question, but it would be great if devbox could eventually support multiple backend stores, allowing users to choose their preferred option.

Thanks!

**Comment by TxGVNN** [comment]
Thank you very much. I will research more.
Have a nice day, @mohsenari

**Comment by matzeeable** [comment]
> But we're working on allowing installation of github repositories as packages even if they're not a nix package.

@mohsenari perhaps https://github.com/aquaproj/aqua is something you could add as "registry" backend.
