### ISSUE TITLE
[Bug]: Issue with Poetry shell using devcontainer or Docker image

### ISSUE THREAD

**Issue by spawnrider** [jetpack-io/devbox#1762]
**Current Behavior (bug)**
I'm currently using Devbox and Poetry to setup a tiny Python project.
```
{
  "packages": ["python@3.10", "poetry"],
  "env": {
    "POWERLEVEL9K_INSTANT_PROMPT": "off"
  } ,
  "shell": {
    "init_hook": "poetry shell -vvv",
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

I'm using devbox generate devcontainer to generate the .devcontainer and the associated Dockerfile.
When I'm launching the devcontainer using VSCode, I'm facing this issue : 
```Poetry could not find a pyproject.toml file in /code or its parents```

I saw that the Dockerfile having reference to the **code** folder but I don't have it and the Poetry setup is working perfectly my local environment as you can see below : 
<img width="933" alt="image" src="https://github.com/jetpack-io/devbox/assets/107427/8852f082-6eda-4202-8459-6f416c858f8b">

I can duplicate the pyproject.toml file but ... i think it's not the right way to override this issue...

**Expected Behavior (fix)**
The Devcontainer must start and initialize devbox and poetry shell as well.

**Additional context**
```
devbox version -v                                                                        1 err  17:45:43
Version:     0.8.7
Platform:    darwin_arm64
Commit:      525bb17ed665bb3066fbd3fb9bccec0aa961ecb7
Commit Time: 2024-01-23T19:15:31Z
Go Version:  go1.21.5
Launcher:    0.2.1
```

**Comment by spawnrider** [comment]
I just found the solution. The issue was that I forgot to add the PyProject.toml file to the generated Dockerfile.
It works perfectly now.

**Comment by mohsenari** [comment]
@spawnrider glad you found the solution. Apologies for that. I have made a [PR](https://github.com/jetpack-io/devbox/pull/1779) to update our docs and generated dockerfile to notify that you should add your project files and directories.
