### ISSUE TITLE
Failing to add packages due to Go unmarshalling error

### ISSUE THREAD

**Issue by emanguy** [jetpack-io/devbox#1767]
### What happened?

After running `devbox init`, I attempt to add any package to it via `devbox add` but it fails with an unmarshalling error. Presumably it's trying to deserialize some JSON but Nix updated the format or something? I had Nix installed on my machine already, so maybe it's an incompatible version or something.

### Steps to reproduce

1. Install Nix on MacOS using their official installer: https://nixos.org/download#nix-install-macos
2. Install devbox via the official script: https://www.jetpack.io/devbox/docs/quickstart/
3. Run `devbox init` to start a `devbox.json`
4. Run `devbox add go` to add the go package to `devbox.json`

### Command

add

### devbox.json

```jsonc
{
  "packages": [],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.8.7

### Nix version

2.20.1

### What system does this bug occur on?

macOS (Intel)

### Debug logs

I've edited the output to mask some file names, but semantically it's the same.

2024/01/31 15:59:37 findProjectDir: path is
2024/01/31 15:59:37 finding devbox config in dir: /Users/erittenhouse/Desktop/PROJECT/FOLDER/GIT_REPO
2024/01/31 15:59:37 findProjectDir: path is
2024/01/31 15:59:37 finding devbox config in dir: /Users/erittenhouse/Desktop/PROJECT/FOLDER/GIT_REPO
2024/01/31 15:59:38 findProjectDir: path is
2024/01/31 15:59:38 finding devbox config in dir: /Users/erittenhouse/Desktop/PROJECT/FOLDER/GIT_REPO
Info: Adding package "go@latest" to devbox.json

Error: There was an error installing nix packages
source: json: cannot unmarshal object into Go struct field ProfileListOutput.elements of type []nixprofile.ProfileListElement

2024/01/31 15:59:38
ExecutionID:1e390847f87b4708b43062a4736f5eed
<nil>
2024/01/31 15:59:38 findProjectDir: path is
2024/01/31 15:59:38 finding devbox config in dir: /Users/erittenhouse/Desktop/PROJECT/FOLDER/GIT_REPO

**Comment by savil** [comment]
Thanks for filing this. Looks like the latest nix version changed how the nix profile output is represented:

From the [release notes](https://nixos.org/manual/nix/stable/release-notes/rl-2.20):
> nix profile now allows referring to elements by human-readable names [#8678](https://github.com/NixOS/nix/pull/8678)

> [nix profile](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile) now uses names to refer to installed packages when running [list](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-list), [remove](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-remove) or [upgrade](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-upgrade) as opposed to indices. Profile element names are generated when a package is installed and remain the same until the package is removed.

> Warning: The manifest.nix file used to record the contents of profiles has changed. Nix will automatically upgrade profiles to the new version when you modify the profile. After that, the profile can no longer be used by older versions of Nix.

We'll need to update Devbox and ship a release...
