### ISSUE TITLE
Ruby 2.7 throws the error `GLIBC_2.38' not found

### ISSUE THREAD

**Issue by jamesgecko** [jetpack-io/devbox#1772]
### What happened?

When running Rails with Ruby 2.7, I get the following stack trace:

```
bundler: failed to load command: rails (/home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/bin/rails)
LoadError: /nix/store/jxjy8r4k8pf7v0hasi37qgva9va81kj2-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/date-3.3.4/lib/date_core.so) - /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/date-3.3.4/lib/date_core.so
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/date-3.3.4/lib/date.rb:4:in `require'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/date-3.3.4/lib/date.rb:4:in `<top (required)>'
  /nix/store/vs52hm8jbwgx19plicg02dzz2vmvbyy5-ruby-2.7.8/lib/ruby/2.7.0/time.rb:3:in `require'
  /nix/store/vs52hm8jbwgx19plicg02dzz2vmvbyy5-ruby-2.7.8/lib/ruby/2.7.0/time.rb:3:in `<top (required)>'
  /nix/store/vs52hm8jbwgx19plicg02dzz2vmvbyy5-ruby-2.7.8/lib/ruby/2.7.0/open-uri.rb:4:in `require'
  /nix/store/vs52hm8jbwgx19plicg02dzz2vmvbyy5-ruby-2.7.8/lib/ruby/2.7.0/open-uri.rb:4:in `<top (required)>'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/generators/app_base.rb:6:in `require'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/generators/app_base.rb:6:in `<top (required)>'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/generators/rails/app/app_generator.rb:3:in `require'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/generators/rails/app/app_generator.rb:3:in `<top (required)>'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/commands/application/application_command.rb:4:in `require'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/commands/application/application_command.rb:4:in `<top (required)>'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/command/behavior.rb:44:in `require'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/command/behavior.rb:40:in `each'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/command/behavior.rb:40:in `block in lookup'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/command/behavior.rb:39:in `each'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/command/behavior.rb:39:in `lookup'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/command.rb:74:in `find_by_namespace'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/command.rb:46:in `invoke'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/lib/rails/cli.rb:18:in `<top (required)>'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/exe/rails:10:in `require'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/gems/railties-6.1.7.6/exe/rails:10:in `<top (required)>'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/bin/rails:25:in `load'
  /home/james/src/rails-crash/.devbox/virtenv/ruby_2_7/bin/rails:25:in `<top (required)>'
```

I'm running Devbox on NixOS unstable (aarch64) in an OrbStack VM on macOS 14.2.1 on an M1 MacBook Pro.

### Steps to reproduce

- Clone this gist - https://gist.github.com/jamesgecko/9283718f3f2598d4286b633d58ace0a6
- Run `bundle install`
- Run `bundle exec rails`

### devbox.json

```jsonc
{
  "packages": [
    "ruby_2_7@latest",
    "postgresql_15@latest",
    "shared-mime-info@latest",
    "flake:nixpkgs#zlib^out,dev",
    "flake:nixpkgs#libpng^out,dev",
    "flake:nixpkgs#libsndfile^out,dev"
  ],
  "include": [
    "plugin:postgresql",
    "plugin:ruby_2_7",
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null",
      "export FREEDESKTOP_MIME_TYPES_PATH=$DEVBOX_PACKAGES_DIR/share/mime/packages/freedesktop.org.xml",
      "unset LD_LIBRARY_PATH"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.8.5

### Nix version

nix (Nix) 2.18.1

### What system does this bug occur on?

Linux (ARM64)

**Comment by gcurtis** [comment]
@jamesgecko I can't seem to reproduce this issue from a clean ARM64 Linux VM. Couple of followup questions:

1. Were you ever using a different version of Ruby in this project before switching to `ruby@2.7`?
2. Were there any other packages that had been in the devbox.json that you've since removed?
3. Did you already try deleting `.devbox/virtenv/ruby_2_7/` and then re-running `bundle install && bundle exec rails`?

I'm wondering if there was a package that put a newer version of gcc/glibc in `$DEVBOX_PACKAGES_DIR/lib` at one point. This would've caused bundler to compile/link the gems with GLIBC 2.38. But if that package got removed later, then the newer GLIBC would no longer be available.

**Comment by jamesgecko** [comment]
To create the reproduction, I started a brand new devbox project and copy/pasted the `devbox.json` file from my original project into it. There was no preexisting `.devbox` for this project.

In the original project directory, I tried all sorts of different stuff in `devbox.json`. In this stack trace it's a date gem crashing. In the original project it was a postgresql gem crashing.

Is it possible there's something in [my host NixOS setup](https://gist.github.com/jamesgecko/9e4aed0ae44d5493fdd15d41ff3aa304) that is problematic with the devbox environment? I thought that `programs.nix-ld.enable = true;` (used for remotely connecting with VSCode) might be problematic, but I disabled it. ran `sudo nixos-rebuild switch`, rebooted the vm, deleted `.devbox`, and things are still broken.

I'm wondering if there's something getting cached in my home directory that could be causing this? But another Rails devbox project I have that uses Ruby 3.1.3 is fine.

**Comment by gcurtis** [comment]
I upgraded my NixOS and now I'm able to reproduce it. I think I know why this is happening. When bundler installs the gems, it's using the stdenv's gcc which is linking against glibc 2.38. However, the ruby interpreter itself is linked against glibc 2.37.

I'm going to try out a couple potential fixes and see if something works.

**Comment by Lagoja** [comment]
This seems to be working in 0.10.1, and I confirmed on a Linux machine that running `devbox add ruby_2_7@latest --patch-glibc` will patch the ruby runtime to use a newer glibc (2.38). 

If you encounter this error again, see if re-adding ruby with `--patch-glibc` can fix it for you.

**Comment by jamesgecko** [comment]
Does the patching extend to gems installed by `bundle install` after opening the devbox shell? I'm still seeing a similar error, this time with the `sassc-rails-2.1.2` gem.

**Comment by skopsejak** [comment]
Using patch: always causes the derivation to fail. Anyone else getting this?
