### ISSUE TITLE
Support non-root setup

### ISSUE THREAD

**Issue by frafra** [jetpack-io/devbox#1783]
### What problem are you trying to solve?

I use nix-portable since I cannot use sudo/su on my work system due to security policy. devbox tries to install on /usr/local/bin, which requires root access. It also tries to install nix as root if the nix command is not available.

Even when `nix` is available via `nix-portable`, some functionalities do not seem to work as expected, such as `devbox shell --pure`:
```
Error: could not find any nix executable in PATH. Make sure Nix is installed and in PATH, then try again
```
`nix` is available as binary in PATH, so the message is wrong, and the problem has been triggered by a different issue, probably.

### What solution would you like?

I modified the setup script to target ~/.local/bin and linked nix-portable to nix. It would be nice to be able to specify a different installation path and use sudo only whenever it is needed. Giving proper documentation on how to install devbox with nix-portable would be a plus.

**Comment by frafra** [comment]
`devbox shell --pure` fails because:
1. it does not look if `nix` is available to determine if `nix` is available, but it looks for known paths inside `PATH`
2. It assumes that the store PATH is under `/nix/store`

**Comment by kadaan** [comment]
Any reason to not use `exec.LookPath('nix')` to determine the path containing nix?  Why reinvent the wheel?

**Comment by kadaan** [comment]
@savil @frafra On my end, changing `pure_shell.go` to the following makes it work for `devbox shell` and `devbox shell --pure` 
```go
func findNixInPATH() (string, error) {
	path, err := exec.LookPath("nix")
	if err != nil {
		if errors.Is(err, exec.ErrDot) {
			err = nil
			workingDirectory, err := os.Getwd()
			if err != nil {
				return "", errors.New("could not find any nix executable in PATH. Make sure Nix is installed and in PATH, then try again")
			}
			path = workingDirectory
		}
		if err != nil {
			return "", errors.New("could not find any nix executable in PATH. Make sure Nix is installed and in PATH, then try again")
		}
	} else {
		path = filepath.Dir(path)
	}

	debug.Log("found nix in PATH: %s", path)
	return path, nil
}
```
