### ISSUE TITLE
Conflicting Python recommendations

### ISSUE THREAD

**Issue by frafra** [jetpack-io/devbox#1788]
### What happened?

```
We detected extra packages you may need. To install them, run `devbox add python3 python310 poetry`
```

This is not a good suggestion, since python3 and python310 conflict: `error: An existing package already provides the following file: [...]`

### Steps to reproduce

1. Run `devbox init` in a Python project?

### Command

init

### Devbox version

0.9.0

### Nix version

2.18.0

### What system does this bug occur on?

Linux (x86-64)

**Comment by Lagoja** [comment]
I think most of these recommendations are out of date, and the detection logic isn't very good. We should probably remove them
