### ISSUE TITLE
Podman support and installation is not simple, easy, or predictable

### ISSUE THREAD

**Issue by AddictArts** [jetpack-io/devbox#181]
Please consider Podman, should be a drop in, supports all the docker cli. However this alone is not enough to get going at least for me.

The Nix install failed for me and I think the docs here understate the complexity of this install, really unfortunate.

The irony of a tool to have easy predictable shells and yet installation is not easy or predictable itself is not lost on me.

**Comment by savil** [comment]
@AddictArts thanks for raising these issues.

On Podman, that's a good suggestion. I'll look into it.

We also similarly feel that the nix install requirement is burdensome. We're actively exploring ways to mitigate this - stay tuned!

**Comment by loreto** [comment]
@AddictArts What sorts of errors are you seeing in the nix install? While we don't maintain that project, if we understand the errors we might be able to mitigate them or improve them in the context of a devbox install.

**Comment by ipince** [comment]
Let's focus this issue on just the nix installation difficulties, and continue discussion on podman support on #18 .

Note that you can run `devbox build --engine=podman`, as mentioned in:
https://github.com/jetpack-io/devbox/issues/18#issuecomment-1236120304

But please give it a show and do let us know if you encounter any issues!

**Comment by AddictArts** [comment]
Thanks @loreto and @ipince 

I did stumble on that, so if I can ever get passed the nix install then I'll give it a go. Although it looks like the nix install is a bust. MacOS is just not viable for nix and Windows requires WSL2, which basically means devbox will be a linux land utility only. While some may have it working on MacOS or Windows it is not first class like linux and other alternatives should be used if possible. Sorry nix fans, but this is the reality.

The error is mounting the volume, it fails to mount, filed an issue with nix.

**Comment by Lagoja** [comment]
Closing this issue out, as we have deprecated `devbox build`. Developers can now generate a Dockerfile for their project using `devbox generate dockerfile`, and build the container with the tool of their choice

For nix installation -- if the default Nix installer does not work, we recommend either allowing Devbox to install Nix for you (via `devbox setup nix`), or using the Determinate Systems Nix Installer (https://determinate.systems/posts/determinate-nix-installer)
