### ISSUE TITLE
[Request] add sql-migrate

### ISSUE THREAD

**Issue by ksthiele** [jetpack-io/devbox#1834]
Hi, I'm using sql-migrate and it would be nice to have it in Nix:

https://github.com/rubenv/sql-migrate

**Comment by mikeland73** [comment]
There's a few ways you can package sql-migrate to work with devbox. Not all require nix, but they all require a bit of work outside of devbox:

* You could package it with a flake (See https://github.com/F1bonacc1/process-compose for an example). This allows devbox to install it using a flake reference (e.g. `github:F1bonacc1/process-compose"`)
* If sql-migrate publishes released binaries you can use `runx` (see https://github.com/jetpack-io/devbox/blob/main/devbox.json#L6-L7 for example)
* You could add it to nixpkgs (https://github.com/nixos/nixpkgs) and devbox search would pick it up (roughly a day after it gets merged).

An alternative would be to modify devbox to be able to build go projects independent of nix, but we currently don't support this. I can look into what that would entail, but the approaches above are likelier to be much faster routes.

**Comment by ksthiele** [comment]
Hi, thanks for the quick response!

I will look into your options, I'm relatively new to devbox and currently figuring it out, to eventually (if it fits our needs) introduce it to my team
