### ISSUE TITLE
Plugins from the same repo share the same state directories

### ISSUE THREAD

**Issue by jay-aye-see-kay** [jetpack-io/devbox#1848]
### What happened?

We have two plugins in a public but for internal use repo here https://github.com/cultureamp/devbox-extras/tree/main/plugins and noticed that their value of `{{ .Virtenv }}` is the same.

So if both of our two plugins are installed the `corepack-bin/` from one and `data/`+`process-compose.yaml` from the other are both in `.devbox/virtenv/cultureamp-devbox-extras/`. I'm not sure what happens if they both try to create a file/dir with the same name.

### Steps to reproduce

1. create a temp devbox project with the `devbox.json` defined below
2. run `ls .devbox/virtenv/cultureamp-devbox-extras/` and see their files are all together in the same dir

### devbox.json

```jsonc
{
  "packages": [
    "nodejs_18@latest",
    "github:cultureamp/devbox-extras#dynamodb_local"
  ],
  "include": [
    "github:cultureamp/devbox-extras?dir=plugins/corepack",
    "github:cultureamp/devbox-extras?dir=plugins/dynamodb_local"
  ]
}
```

### Devbox version

0.9.1

### Nix version

.devbox/virtenv/cultureamp-devbox-extras/

### What system does this bug occur on?

macOS (Apple Silicon)

**Comment by jay-aye-see-kay** [comment]
Suggested fix: update `{{ .DevboxDir }}` and `{{ .Virtenv }}` variables to include the plugin name as well as the repo it comes from.

**Comment by savil** [comment]
thanks for the bug report!
@mikeland73 assigning to you since this is an area you're working on
