### ISSUE TITLE
Feature request: Subfolder search of the devbox.json

### ISSUE THREAD

**Issue by QuentinN42** [jetpack-io/devbox#185]
Hello,
I'm using devbox inside a monorepo and I want to exec `devbox shell` while I'm in a nested folder.

```
.
├── a
│   └── content
├── b
│   └── content
└── devbox.json
```

While I'm inside `a` or `b`, running `devbox shell` result in `Error: open devbox.json: no such file or directory` and I want devbox to lookup if there is some parent folders that uses devbox.

**Comment by savil** [comment]
@QuentinN42 when inside `a` or `b`, could you try running `devbox shell ../` and see if that works for you?

**Comment by QuentinN42** [comment]
Yes it works but for example using git I don't need to give the absolute path to the base repo to make it works...

I think this line can be changed  to return a null value.
https://github.com/jetpack-io/devbox/blob/930867bf4e84f370b4c42a9797a7ee85821f8483/boxcli/args.go#L24

Then in this folder if the `path` is null, recursively test `devbox.Open(path)` from current folder to root folder.
https://github.com/jetpack-io/devbox/blob/930867bf4e84f370b4c42a9797a7ee85821f8483/boxcli/shell.go#L31-L35

I've found others issues  about the `devbox.json` file like https://github.com/jetpack-io/devbox/issues/109 or https://github.com/jetpack-io/devbox/issues/24 so I think this is the best way to implement this feature without adding too much technical depth...
