### ISSUE TITLE
Error running devbox

### ISSUE THREAD

**Issue by olimart** [jetpack-io/devbox#186]
Following #164 I wanted to give ruby a try but can't make it work (although does not seem to be related to ruby at all).
No idea what to check so pasting everything I did. Any idea?

`devbox.json`

```json
{
  "packages": [
    "ruby_3_1"
  ],
  "shell": {
    "init_hook": null
  }
}
```

then running devbox returns

```bash
devbox shell
Installing nix packages. This may take a while...
Starting a devbox shell...
bash: command substitution: line 46: syntax error near unexpected token `newline'
bash: command substitution: line 46: `			$NIX_STORE/*'

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(devbox) bash-3.2$ ruby -v
bash: ruby: command not found
```

**Comment by ipince** [comment]
hmm, that's odd (and does seem unrelated to ruby).

my guess is the shell is trying to load some `.bash_profile` script or something like that, and failing.

but i'm also curious if some other planner is affecting things. what's the output of `devbox plan`?

**Comment by olimart** [comment]
```
$ devbox plan
{
  "dev_packages": [
    "ruby_3_1"
  ],
  "runtime_packages": [
    "ruby_3_1"
  ],
  "install_stage": {
    "command": ""
  },
  "build_stage": {
    "command": ""
  },
  "start_stage": {
    "command": ""
  }
}
```

**Comment by ipince** [comment]
Hmm ok that's as expected.

Does the problem still happen before trying it with ruby?

What's your OS? do you have any profile scripts, and if so, does the problem persist if you disable them? does the problem happen with different shells? looks like bash 3.2 is kinda old (from 2006... latest is 5.2)--is there any reason why you're using such an old shell?

**Comment by olimart** [comment]
same error with python example, so I guess related to my shell.

> is there any reason why you're using such an old shell?

haha. am using what Mac OS provides on my good old trusty iMac. I'll try again on most recent laptop if not supported.
