### ISSUE TITLE
Should a `/nix/store/...bash/bin` entry be added to PATH when installing packages globally?

### ISSUE THREAD

**Issue by realfresh** [jetpack-io/devbox#1883]
When I install packages globally, running `eval "$(devbox global shellenv --init-hook -r)"` results in a PATH entry such as `/nix/store/087167dfxal194pm54cmcbbxsfy3cjgn-bash-5.2p26/bin` being added above entries such as `/usr/bin`.

As a resulting running `bash` in the terminal actually invokes `/nix/store/087167dfxal194pm54cmcbbxsfy3cjgn-bash-5.2p26/bin/bash`.

As you can imagine, this ends up causing issues with other programs since the nix `bash` program is being used over the default `bash` program.

Is this by design, or is this a bug? 

Just seems strange that this would be the case, especially since I haven't installed `bash` via Devbox.

PS: Devbox is freaking awesome!

**Comment by gcurtis** [comment]
Hey @realfresh, a few packages like bash and clang do get implicitly added to the environment as build dependencies, which isn't really desired for a "global" environment. This is something we should fix.

I'm going to close this and group it in with #1509. And thank you for the kind words!
