### ISSUE TITLE
Update `devbox-install-action` version in documentation

### ISSUE THREAD

**Issue by altano** [jetpack-io/devbox#1884]
### Package name

devbox-install-action

### What changes are you requesting?

The documentation for devbox-install-action (https://www.jetpack.io/devbox/docs/continuous_integration/github_action) hard-codes v0.6.0 but the action is on version v0.8.0 (https://github.com/marketplace/actions/devbox-installer). You might want to update the link.

Sorry, I know this template wasn't the right choice but I wasn't sure where else to put it.

**Comment by altano** [comment]
FWIW it is up to date in source, which is why I didn't just submit a PR: https://github.com/jetpack-io/devbox/blob/fbeceabd544295043714f71152ebfb394633acd4/docs/app/docs/continuous_integration/github_action.md?plain=1#L17

**Comment by Lagoja** [comment]
Docs have been redeployed and updated. Thanks for reporting!
