### ISSUE TITLE
Plugins are overwriting files inside devbox.d/

### ISSUE THREAD

**Issue by t-monaghan** [jetpack-io/devbox#1909]
### What happened?

When a newly cloned repository with devbox v0.10.1 is opened, plugins will overwrite the existing files in `devbox.d/{plugin-dir}` during the package installation phase.

This is an issue as the repository can already contain files in this directory, and this overwrite breaks the expected configuration of packages.

#### setup a devbox project with mongo and it's plugin
cd $(mktemp -d)
devbox init
devbox add github:cultureamp/devbox-extras#mongodb-6_0 jq
mv devbox.json devbox.json.bak
jq '. + { "include": ["github:jetpack-io/devbox-plugins?dir=mongodb"] }' devbox.json.bak > devbox.json
devbox install

#### add some config to mongod.confg (we need it to run on a custom port)
export MONGOD_CONF="devbox.d/jetpack-io.devbox-plugins.mongodb/mongod.conf"
echo "" >> $MONGOD_CONF
echo "net:" >> $MONGOD_CONF
echo "  port: 1234" >> $MONGOD_CONF

echo "---"
echo "updated $MONGOD_CONF file:"
cat $MONGOD_CONF

#### simulate the next person pulling and setting up, delete the .devbox dir and reinstall
rm -rf .devbox/
devbox install

#### see that $MONGOD_CONF has been reverted to it's original state
echo "---"
echo "overwritten $MONGOD_CONF file:"
cat $MONGOD_CONF

### devbox.json

```jsonc
{
  "packages": {
    "github:cultureamp/devbox-extras#mongodb-6_0"
  },
  "include": [
    "github:jetpack-io/devbox-plugins?dir=mongodb"
  ],
}
```

### Devbox version

0.10.1

### Nix version

nix (Nix) 2.18.1

### What system does this bug occur on?

macOS (Apple Silicon)

**Comment by t-monaghan** [comment]
The issue seems to be stemming from this line. It is checking if the filepath contains the string ".devbox". However the plugin file is being placed in the directory "devbox.d/jetpack-io.devbox-plugins.{PLUGIN}/..." The issue is the directory "jetpack-io.devbox-plugins.{PLUGIN}" contains the substring.

https://github.com/jetpack-io/devbox/blob/eed56cd6e516bb86577c9abcaf421fe88c714296/internal/plugin/plugin.go#L220-L222

**Comment by Lagoja** [comment]
@mikeland73 looks like a bug in plugins v2 for 0.10.1 -- we're overwriting existing files when applying plugins
