### ISSUE TITLE
nodejs reference hashes are not unique

### ISSUE THREAD

**Issue by ben-redvanworkshop** [jetpack-io/devbox#1942]
### What happened?

When you navigate to https://www.nixhub.io/packages/nodejs search for the hash `a3ed7406349a9335cb4c2a71369b697cecd9d351` using your browser.  You'll see the hash is in use for versions 18.19.1, 20.11.1, 21.7.1 just as an example

**Comment by savil** [comment]
@ben-redvanworkshop IIUC that means that these versions of nodejs are from the "nix derivations" that are defined in the same nixpkgs commit-hash i.e. https://github.com/nixOS/nixpkgs/commit/a3ed7406349a9335cb4c2a71369b697cecd9d351

cc @gcurtis in case I'm misrepresenting this.
