### ISSUE TITLE
Feature Request: Multiple terminals in parallel

### ISSUE THREAD

**Issue by mikenikles** [jetpack-io/devbox#214]
Disclaimer upfront: This is a bit of a moonshot, but hear me out 😄.

## Current situation

In `devbox.json`, I can configure a `shell.init_hook` array:

```json
{
  "shell": {
    "init_hook": ["echo 'One'", "echo 'Two'"]
  }
}
```

These commands run in sequence and each has to terminate.

## Future

In most of my projects, I need to spin up a few services in parallel. For example:
* A database
* An API server
* A web app

Each runs in its own terminal and prints its logs to the corresponding terminal tab/window.

It'd be great if shell `init_hook` commands ran in their own terminal and could be non-terminating. With that, anyone could open a devbox shell and have all necessary services up and running. All they have to do is write code. You could even fire up a test suite in watch-mode in one of the terminals and have instant feedback whether you're breaking tests as you develop code.

**Comment by Lagoja** [comment]
Added a feature that can replicate this behavior in Devbox 0.1.1. See scripts + `devbox run`!

**Comment by mikenikles** [comment]
Love it and already use it 😜
