### ISSUE TITLE
Feature Request: devbox install

### ISSUE THREAD

**Issue by loreto** [jetpack-io/devbox#22]
Make it possible to install packages without starting a shell.

**Comment by loreto** [comment]
@morey-tech That'd be great.

I think that's right, although instead of `shell.nix` you should use `default.nix` (same file used by the Dockerfile). If you send the PR, keep the install command as a "hidden" command (see the generate command for an example of a hidden command), as we'll want to do some additional testing before turning it on for everyone.

**Comment by Lagoja** [comment]
linking this to the ticket and discussion at #246. Also addresses installing packages without running the shell
