### ISSUE TITLE
Feature Request: ability to turn off autodetection languages/stacks

### ISSUE THREAD

**Issue by Satont** [jetpack-io/devbox#224]
Yesterday I found myself in a situation where autodetection was preventing me from installing the right version of nodejs. I managed to set `18.7.0` even though the releases already have `18.9.1` and it is available for installation via nix.

It would be useful to be able to manage versions more flexibly, without `engines` field in `package.json`.

**Comment by Satont** [comment]
Wait, is it done in https://github.com/jetpack-io/devbox/pull/222?

**Comment by Lagoja** [comment]
Hey @Satont! We're working on turning this on for an upcoming release, so that developers can manage the version directly in their `devbox.json`. I think this will be out in the next release.

**Comment by Lagoja** [comment]
This should be addressed in #227

**Comment by Lagoja** [comment]
Closed with #227
