### ISSUE TITLE
VSCode extension doesn't entering shell (WSL)

### ISSUE THREAD

**Issue by Satont** [jetpack-io/devbox#238]
WSL: `0.70.0.0`
VSCode: `1.72.2`
Extension: `0.0.1`
WSL Distro: `Arch`

Opened devtools in VSC via `ctrl+shift+I`, there is no errors.

Please tell me how i can help to reproduce problem.

**Comment by Lagoja** [comment]
Can you share a rough outline of the project structure you are opening in VSCode (e.g., folders, where the `devbox.json` is stored)? This will help us replicate with a similar project

**Comment by Lagoja** [comment]
CC'ing Mohsen to take a look

**Comment by Satont** [comment]
> Can you share a rough outline of the project structure you are opening in VSCode (e.g., folders, where the `devbox.json` is stored)? This will help us replicate with a similar project

`devbox.json` in the root of project.

**Comment by Satont** [comment]
I'm opening project via `code ~/projectName`

**Comment by mohsenari** [comment]
@Satont I just installed WSL and tried to recreate this in my windows machine. But the terminal correctly goes to devbox shell.
Does your terminal window open when you press `ctrl+shift+I` ? in newer version of VSCode the keyboard shortcut has changed to 
```
ctrl+shift+`
```

**Comment by Satont** [comment]
Testing on the ubuntu wsl, it works. Might be bug on not officially supported wsl distro. Closing now, sorry.
