### ISSUE TITLE
Let users choose a specific revision of nixpkgs for installing their packages

### ISSUE THREAD

**Issue by Lagoja** [jetpack-io/devbox#248]
## Problem

Devbox is currently pinned to a specific commit of the unstable channel of nixpkgs. This ensures that everyone who uses Devbox gets the same packages (ensuring their environments are reproducible), but it limits which versions of different packages are available with Devbox

## Solution

As a temporary means of addressing this issue, we will allow users to provide a different revision SHA that devbox will use for installing packages. This will let developers pull older or newer versions of packages that may not be available in Devbox's default revision. 

To find the revision with the package they want, developers can use tools like https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable to find a revision with the package they need. 

## Future Work

Long term, we want to provide a way for developers to get the right package by specifying the version of the package they need, similar to what is described in #102

**Comment by Lagoja** [comment]
Merged and shipped in release 0.1.1 with Nixpkg Commit Pinning

**Comment by sophiabrandt** [comment]
Hello, I'm not familiar with NixOS/Nix, so all my knowledge comes from following the instructions in this README.

Could you clarify how to install a specific version with this workaround? What is the command that I need to run?

Thank you.

**Comment by brokenpip3** [comment]
@sophiabrandt https://www.jetpack.io/devbox/docs/guides/pinning_packages/#look-up-a-commit-hash-for-a-specific-package
