### ISSUE TITLE
 Newbie question: WSL2 / Ubuntu 20.04: "devbox add python310" fails with "Error: Package python310 not found"

### ISSUE THREAD

**Issue by hamidk** [jetpack-io/devbox#26]

**Comment by LucilleH** [comment]
@hamidk Did you install Nix?

**Comment by hgezim** [comment]
I'm seeing the same issue, except with node:

```
> devbox init
✓ Downloading version 0.0.3... [DONE]
✓ Verifying checksum... [DONE]
✓ Unpacking binary... [DONE]

> devbox add nodejs-16_x
Error: Package nodejs-16_x not found.
> devbox add nodejs
Error: Package nodejs not found.
```

I'm using fish shell by default.

**Comment by hamidk** [comment]
I did install Nix.
But, when I went to see the Nix install log, I realized that I overlooked to do
" . /home/ahk/.nix-profile/etc/profile.d/nix.sh" to setup the Nix environment. I just did it and now "devbox add pyhthon310" works. Thanks
