### ISSUE TITLE
Does removing files/dir from initialized devbox suffice?

### ISSUE THREAD

**Issue by jaeyson** [jetpack-io/devbox#27]
Hi! noob question: I've followed the instructions with setting up nix and docker and initialized it (`devbox init`). Does removing `.devbox/` dir and `devbox.json` suffice?

**Comment by loreto** [comment]
Hi @jaeyson 

If you're just trying to revert your project to it's pre-devbox state, then yes, that's all you need to delete and your project/directory is no longer using devbox.

If you're trying to completely uninstall devbox from your machine, then you also need to uninstall nix which adds a few things to your system including `/nix/store`.

Which of the two cases are you dealing with?

**Comment by jaeyson** [comment]
Hi @loreto thanks for helping me out. You've answered my question with reverting to pre-devbox state. If we're talking about completely removing nix package manager, this ref https://nixos.org/manual/nix/stable/installation/installing-binary.html#uninstalling and your advice:

> If you're trying to completely uninstall devbox from your machine, then you also need to uninstall nix which adds a few things to your system including /nix/store.

is enough right?

**Comment by loreto** [comment]
Yes, correct – follow those instructions and you'll remove nix too.
