### ISSUE TITLE
Installing python packages in devbox

### ISSUE THREAD

**Issue by wei-ann-Github** [jetpack-io/devbox#30]
Hi,

Following the quickstart, I have installed python 3.10 in the devbox environment. However, how do I install python packages in the environment? A `pip install` tells me that the package is already installed. But that installation actually belongs to the installation in my WSL environment itself, and not in the devbox environment.
```
(base) weiann@Surface-Laptop:/mnt/c/Users/wei-a/Documents/code/github/devbox/quickstart$ python --version
Python 3.8.8
(base) weiann@Surface-Laptop:/mnt/c/Users/wei-a/Documents/code/github/devbox/quickstart$ devbox shell
Installing nix packages. This may take a while...
Starting a devbox shell...
(base) weiann@Surface-Laptop:/mnt/c/Users/wei-a/Documents/code/github/devbox/quickstart$ python --version
Python 3.10.5
(base) weiann@Surface-Laptop:/mnt/c/Users/wei-a/Documents/code/github/devbox/quickstart$ pip install pandas
Requirement already satisfied: pandas in /home/weiann/anaconda3/lib/python3.8/site-packages (1.2.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/weiann/anaconda3/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /home/weiann/anaconda3/lib/python3.8/site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.16.5 in /home/weiann/anaconda3/lib/python3.8/site-packages (from pandas) (1.20.1)
Requirement already satisfied: six>=1.5 in /home/weiann/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
```

**Comment by loreto** [comment]
Hey @wei-ann-Github,

My guess is that you haven't installed `pip` in your devbox shell, so when you call `pip` you end up still calling the one outside of devbox. You can verify this by calling `which pip` – if it's a devbox one it should start with a `/nix/store` prefix like so: `/nix/store/mylr4gvdb65bv30cjmp4h8fkfnd943qp-python3.10-pip-22.1.2/bin/pip`

I just tried this myself really quickly and I had to do: `devbox add python310Full python310Packages.pip` (notice the second package in the list is the one that adds `pip`)

If you do the above, does it work for you?

**Comment by codethief** [comment]
> so when you call pip you end up still calling the one outside of devbox

This seems very dangerous. Is there no way to tell devbox not to resort to the outside shell environment in order to prevent such issues?

**Comment by wei-ann-Github** [comment]
> Hey @wei-ann-Github,
> 
> My guess is that you haven't installed `pip` in your devbox shell, so when you call `pip` you end up still calling the one outside of devbox. You can verify this by calling `which pip` – if it's a devbox one it should start with a `/nix/store` prefix like so: `/nix/store/mylr4gvdb65bv30cjmp4h8fkfnd943qp-python3.10-pip-22.1.2/bin/pip`
> 
> I just tried this myself really quickly and I had to do: `devbox add python310Full python310Packages.pip` (notice the second package in the list is the one that adds `pip`)
> 
> If you do the above, does it work for you?

Hi @loreto,

Thank you. this does work in install pip in devbox. However, installing python packages is still a challenge with this error
```
FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/bin/pip'
```

which pip shows:
```
/nix/store/m5618dhmkqvmkm1bf04q6lc43zax6zi9-python3.10-pip-22.1.2/bin/pip
```

**Comment by loreto** [comment]
> > so when you call pip you end up still calling the one outside of devbox
> 
> This seems rather dangerous. Is there no way to tell devbox not to resort to the outside shell environment in order to prevent such issues?

I'm thinking of adding a `--pure` or `--isolated` flag to `devbox shell` that would prevent the shell from having that access. That said; it's a bit tricky to know what the right default behavior should be. On the one hand, for tools like `pip` we almost never want to use something in your laptop. But for tools like `git` or `grep`, you kind of expect them to be available (if we're strict about them, you would have to declare that whole set of tools in your `devbox.json` too ... which feels like a lot to declare)

**Comment by loreto** [comment]
> > Hey @wei-ann-Github,
> > My guess is that you haven't installed `pip` in your devbox shell, so when you call `pip` you end up still calling the one outside of devbox. You can verify this by calling `which pip` – if it's a devbox one it should start with a `/nix/store` prefix like so: `/nix/store/mylr4gvdb65bv30cjmp4h8fkfnd943qp-python3.10-pip-22.1.2/bin/pip`
> > I just tried this myself really quickly and I had to do: `devbox add python310Full python310Packages.pip` (notice the second package in the list is the one that adds `pip`)
> > If you do the above, does it work for you?
> 
> Hi @loreto,
> 
> Thank you. this does work in install pip in devbox. However, installing python packages is still a challenge with this error returned
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5/bin/pip'
> ```
> 
> which pip shows:
> 
> ```
> /nix/store/m5618dhmkqvmkm1bf04q6lc43zax6zi9-python3.10-pip-22.1.2/bin/pip
> ```

Hey @wei-ann-Github,

The short version is that we recommend using either `poetry` (https://python-poetry.org/) or  coupling `pip` with `venv` (https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/) for your python dependency management.

The reason you're seeing that error is this: `nix` and `pip` are conflicting with each other. `pip` installs packages globally by default. `nix` on the other hand doesn't want anyone to modify it's store, because it wants every package to be "immutable" and nothing should be added to an existing nix store directory. So when `pip` tries to install packages in the `nix` store, it fails.

We do wish `nix` had better "out-of-the-box" support for `pip`. We think that if you install `pip`, and run it, "it should just work". But alas, `nix` doesn't work that way, and to solve that, we might have to build something custom on top.

In the meantime, `poetry` and `venv` are great solutions. We use `poetry` ourselves, and think it brings additional benefits.

**Comment by loreto** [comment]
Re-reading this: the pip error you're seeing is something else (you should still go with poetry or venv to the reasons I outlined), but let me see if I can replicate the error you're seeing in case there's something else wrong.

**Comment by codethief** [comment]
> But for tools like git or grep, you kind of expect them to be available (if we're strict about them, you would have to declare that whole set of tools in your devbox.json too ... which feels like a lot to declare)

True. How about having devbox add certain binaries (e.g. all coreutils and maybe some others) to the devbox automatically? (At least by default. One should probably have the option of overriding this behavior / adjusting the list of binaries.)

**Comment by Lagoja** [comment]
Hey everyone, pip install is now supported in shell and build starting in version 0.0.7! When using pip, we'll create a virtualenv that lets you install your packages in an isolated manner. You can learn more from our docs here: https://www.jetpack.io/devbox/docs/language_support/python/

**Comment by AJM10565** [comment]
https://www.jetpack.io/devbox/docs/language_support/python/ is a dead link. What is the preferred way to setup pip installs?

**Comment by giulianopz** [comment]
> https://www.jetpack.io/devbox/docs/language_support/python/ is a dead link. What is the preferred way to setup pip installs?

Probably this one: https://www.jetify.com/devbox/templates/python-pip
