### ISSUE TITLE
Feature Request: support for older version of PHPs

### ISSUE THREAD

**Issue by LeslieLeung** [jetpack-io/devbox#32]
The older versions of PHPs is not supported by nix(see https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/aliases.nix) , so when I use `devbox add php73`, it promts `Error: Package php73 not found.`.

However there are some workarounds, for example [fossar/nix-phps](https://github.com/fossar/nix-phps) . Is it possible for devbox to support such kind of workarounds?

**Comment by Lagoja** [comment]
We'll look into this! We're evaluating how to let users configure alternative Nix repositories and package sources for Devbox.

**Comment by Lagoja** [comment]
As of 0.4.7, we've released support for Nix Flakes in your package list.  This means you can now install PHP versions from the fossar/nix-phps repo by adding the following to your packages list: 


```json
{
    "packages" : [
        "github:fossar/nix-phps#php73"
    ]
}
```

For more details, see https://www.jetpack.io/devbox/docs/guides/using_flakes/
