### ISSUE TITLE
Execute devbox run with error 

### ISSUE THREAD

**Issue by vkbaba** [jetpack-io/devbox#402]
I executed "devbox run" according to the documentation below, hit the following error.
https://www.jetpack.io/devbox/docs/guides/scripts/

```
[root@localhost devbox-tutorial]# devbox run echo_once
Installing nix packages. This may take a while... done.
Starting a devbox shell...
bash: run_script: command not found...
```
devbox.json : 
```json
{
  "packages": [],
  "shell": {
    "init_hook": "echo \"Hello \"",
    "scripts": {
        "echo_once": "echo \"World\"", 
        "echo_twice": [
            "echo \"World\"",
            "echo \"Again\""
        ]
    }
  },
  "nixpkgs": {
    "commit": "52e3e80afff4b16ccb7c52e9f0f5220552f03d04"
  }
}
```

**Comment by loreto** [comment]
@vkbaba Thanks for reporting. We'll take a look as soon as we can. The majority of the team is out for the holiday break, so we might not get to it until first week of Jan, but we'll definitely address it by that week.

**Comment by loreto** [comment]
@vkbaba Thanks for reporting. We'll take a look as soon as we can. The majority of the team is out for the holiday break, so we might not get to it until first week of Jan, but we'll definitely address it by that week.

**Comment by loreto** [comment]
@vkbaba Thanks for reporting. We'll take a look as soon as we can. The majority of the team is out for the holiday break, so we might not get to it until first week of Jan, but we'll definitely address it by that week.

**Comment by ipince** [comment]
Hi @vkbaba ,

I've been trying but unable to reproduce. Can you share a bit more about the system you're running on (OS, shell), and the devbox version you're running?

Thanks!
