### ISSUE TITLE
Feature request: easy switching between stable/unstable nixpkgs

### ISSUE THREAD

**Issue by worldofgeese** [jetpack-io/devbox#404]
This could be implemented e.g. as `devbox switch unstable/stable` with some mechanism of updating packages to the latest stable/unstable e.g. `devbox pull/update`.

**Comment by worldofgeese** [comment]
Unstale

**Comment by Lagoja** [comment]
This should be easier to do now that we have Flakes + a lockfile through flakes, but would require a few changes to the config + CLI. This would probably entail: 

1. A field in the `devbox.json` that can set which channel the project should use
2. A lockfile (or a commit hash in the JSON) that pins the channel to a specific commit
3. A command in the CLI that can update the pinned hash/lockfile, and re-install the packages for that channel

**Comment by ctran** [comment]
An alternative would be to support a tag value inside `devbox.json` (currently only allows SHA1).

**Comment by Lagoja** [comment]
Closing this issue since we now support directly tagging package versions.
