### ISSUE TITLE
Nix installed to WSL2 doesn't source `.profile` 

### ISSUE THREAD

**Issue by worldofgeese** [jetpack-io/devbox#405]
When Devbox detects a user doesn't have Nix installed, it will offer to install it for the user. If a user allows this action, then terminates their shell and opens a new one, the Nix binary is still unavailable. Nix's install script adds its path to .profile but no shell startup scripts are run when VS Code Remote is started in WSL: https://code.visualstudio.com/docs/remote/wsl#_advanced-environment-setup-script

As a result, the auto shell feature of the VS Code Devbox extension also doesn't work giving `Error: We found a /nix directory but nix binary is not in your PATH. Try restarting your terminal and running devbox again. If after restarting you still get this message it's possible nix setup is missing from your shell rc file. See https://github.com/NixOS/nix/issues/3616#issuecomment-903869569 for more details.`

Workaround is to manually source a user's `.profile` first. This is not with Fish 🙂 it's my work machine running Windows 11 and a brand new WSL2 distro launched otherwise untouched (shell is bash) apart from installing Devbox with the curl method and adding its VS Code extension.

**Comment by Lagoja** [comment]
Thanks for reporting! Just to check how the environment loading works -- does Devbox work correctly if the correct lines are added to your `[bash|zsh|*sh]rc` file?

**Comment by Lagoja** [comment]
@worldofgeese we've dug into this and a few related problems -- we think the best option is for Devbox to call and use the nix binaries directly, instead of expecting to find them in $PATH. We have some work on this and we're expecting it for the 0.2.1 milestone. Will update once it's finished!

**Comment by Lagoja** [comment]
Tested and validated this improvement with 0.2.1, which we just released today! This version no longer relies on $PATH to locate the nix binaries, so it should work much better on WSL. Please let me know if this fixes the issue!

**Comment by mikeland86** [comment]
@Lagoja safe to close?

**Comment by worldofgeese** [comment]
Apologies for the long delay, I confirm this is now fixed in my WSL2 distro of choice 🎊
