### ISSUE TITLE
Feature request: quiet mode

### ISSUE THREAD

**Issue by aacebedo** [jetpack-io/devbox#406]
Devbox is great and can be used with vscode easily. However the lack of a quiet mode triggers problems when you configure it with vscode (for instance for the formatter). In this case the log printed by devbox when the shell command is called appears in the formatted file.

It would be great if devbox featured a quiet mode in which it will not log anything else the output of the command it executed.
The quiet mode would be a simple `-q` flag to append to any devbox command and will remove the devbox logs.

**Comment by mohsenari** [comment]
#414

**Comment by mohsenari** [comment]
@aacebedo the pull request regarding this issue is merged. You'll have the ability to put `--quiet` or `-q` to devbox shell, devbox run, and devbox init commands in the next release which will likely be next week.
