### ISSUE TITLE
Feature request: add support for ".env" files

### ISSUE THREAD

**Issue by nbish11** [jetpack-io/devbox#407]
I really love this library and would like to know what your thoughts are on automatically importing environment variables defined an a ".env" file. I know you can already define them manually in the devbox.json file, but it would be super convenient that the same ".env" file I use for my docker deployments and production server is the same one I also use for local development.

**Comment by Lagoja** [comment]
Hey @nbish11, thanks for trying Jetpack and thanks for the feedback! This definitely seems like it would help interoperability, especially for developers who already have .env files. We'll discuss this for an upcoming sprint.

**Comment by philcruz** [comment]
I think this would be a good feature.

**Comment by jenisys** [comment]
@nbish11 
Is this functionality not already supported if you are using `direnv` and its `.envrc` config-file in the project-directory?

EXAMPLE:

```bash
# -- FILE: .envrc
dotenv_if_exists .env
```

SEE ALSO:
* [direnv: Support for dotenv](https://direnv.net/man/direnv-stdlib.1.html#codedotenv-ltdotenvpathgtcode)

**Comment by nbish11** [comment]
@jenisys What if you aren't using direnv? I don't want to keep devbox files and direnv files in my project just to load up a test environment. Especially since devbox supports configuration of environment variables in its own config, it should also make sense to support .env files. Just my 2 cents.

**Comment by Lagoja** [comment]
We just merged in #1353 which allows developers to use environment variables with a `--env` or `--env-file` flag. It should be available in our next release: 

```
devbox run -e FOO=BAR echo \$FOO
devbox services up -e HTTPD_PORT=8083
```

**Comment by apgrucza** [comment]
#1353 looks like a useful enhancement. But to close off this particular issue I think the ".env" file needs to be able to be referenced from `devbox.json`, so that this functionality can be used when running `devbox shell` without arguments or with the VS Code extension.

When referencing a ".env" file in `devbox.json`, we should (optionally) suppress an error if the file does not exist. Generally, the referenced ".env" file would not be under source control so it would not exist in a freshly cloned repository.

**Comment by Lagoja** [comment]
Going to create a new issue for tracking `.env` support in the VSCode extension. We'll also evaluate whether this should go into the `devbox.json` schema as part of that issue

See #1478

**Comment by dimas-cyriaco** [comment]
> But to close off this particular issue I think the ".env" file needs to be able to be referenced from devbox.json
Is there an issue tracking this?
