### ISSUE TITLE
[Plugin Request]: mysql80

### ISSUE THREAD

**Issue by calvinbaart** [jetpack-io/devbox#410]
** What is the name of the package(s) you are requesting a plugin for?**
mysql80

**Does the package work today?**
Yes, it works fine now.

**[Optional] What configuration would you propose for this plugin?**
Similar to the mariadb plugin we would need a service, environment variables and some way to create the initial database.

**Additional context**

**Comment by Lagoja** [comment]
@mikeland86 I think this would require support for aliases/scripts in plugins

**Comment by calvinbaart** [comment]
This issue is still relevant

**Comment by httpete** [comment]
definitely still relevant. This is the first blocker I hit in trying out devbox for us.

**Comment by Lagoja** [comment]
A MySQL plugin is now available as of 0.5.6! Documentation for the plugin can be found here, and is available automatically whenever you add `mysql80` or `mysql57`

https://www.jetpack.io/devbox/docs/devbox_examples/databases/mysql/
