### ISSUE TITLE
[Plugin Request]: redis

### ISSUE THREAD

**Issue by calvinbaart** [jetpack-io/devbox#411]
** What is the name of the package(s) you are requesting a plugin for?**
redis

**Does the package work today?**
Yes

**[Optional] What configuration would you propose for this plugin?**
I think a service is primary, but some environment variables to configure the port etc. would be nice.

**Additional context**
-

**Comment by Lagoja** [comment]
Hello @calvinbaart, have a work-in-progress plugin on branch `jl/redis-plugin`. Once I get it pulled into a pre-release I'll let you know how to try it out
