### ISSUE TITLE
Feature request: Am I in a shell? a nested shell?

### ISSUE THREAD

**Issue by robrich** [jetpack-io/devbox#44]
Add a discover-inception command.  e.g. `devbox which` or `devbox whereami` outputs if I'm in a shell, and if that's in a shell and if that's in a shell recursively.  Perhaps add a `-v` that outputs the packages / env vars defined in that shell at each level.  If you're not in a shell it notes that too.

**Comment by loreto** [comment]
We prohibited "shell-inception" in the `0.0.3` release.
We're planning to implement https://github.com/jetpack-io/devbox/issues/25

Do you still feel we should have a `which` or `whereami` command once we've done those two things?
