### ISSUE TITLE
Shell is not overridden on MacOS

### ISSUE THREAD

**Issue by TheGlenn88** [jetpack-io/devbox#46]
Hi,

I've install Nix, followed by Devbox, upon trying to do a `devbox add nodejs-18_x` followed by a `devbox shell` - I get dropped into a new zsh shell but has no access to node 18, it has access to node 16 from my main env.

Have I missed something or have I stumbled upon a bug? is there anything I can do to debug?

disclaimer: I had previously installed nix about a year back and didn't do too much with it.

Thanks

**Comment by Lagoja** [comment]
Hey @TheGlenn88, we've noticed that in some cases, the Devbox path is not taking precedence over the user's path. We're working to fix this in an upcoming release

**Comment by loreto** [comment]
@gcurtis merged a fixed. It's going out on the next release. Closing.

**Comment by gcurtis** [comment]
@TheGlenn88 this fix is now available in [the most recent 0.0.4 release][1]. If you installed devbox with the install script, then it should auto-update to the new version the next time that you run it.

Thanks for taking the time to report this bug, and feel free to reopen this issue if you're still seeing the wrong version of Node after updating.

[1]: https://github.com/jetpack-io/devbox/releases/tag/0.0.4

**Comment by TheGlenn88** [comment]
Thanks @gcurtis

I’ll test again tomorrow and report my findings. :)

**Comment by TheGlenn88** [comment]
I’ve just managed to test actually and it worked perfectly.

Hats off to the smooth experience as well by the way, no messing around. Good job.
