### ISSUE TITLE
Feature Request: Set nixpkgs.config values in devbox.json

### ISSUE THREAD

**Issue by Lagoja** [jetpack-io/devbox#462]
Based on a request in #409 -- have a general way to set the global `nixpkgs.config` options via devbox.json. This would let users explicitly set options like `allowUnfree` or `allowBroken` based on their preference, instead of relying on our default choices. 

From @calvinbaart's suggestion, we could do something like the following: 

```json
{
  "packages": [
    "php",
    "php81Extensions.blackfire",
    "php81Packages.composer"
  ],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "7a3f450e4af7c015a78d5d182499c8c6170418e5",
    "config": {
      "allowUnfree": true,
      "allowUnfreePredicate": [ "php.blackfire" ],
      "otherOptions" ...
    }
  }
}
```

We'd need to confirm which options we want to expose, or if we want to pass through to the underlying

**Comment by savil** [comment]
keep open

**Comment by Lagoja** [comment]
We now support `--allow-unfree` by default and `--allow-insecure` via the CLI w/ `devbox add`. Closing this for the moment, but will open a new issue if we decide to add support for more options
