### ISSUE TITLE
[Bug]: `devbox add ruby` fails with older version of nixpkgs

### ISSUE THREAD

**Issue by loreto** [jetpack-io/devbox#478]
**Current Behavior (bug)**
1. Set your nixpkgs hash to a previous one. In this particular case trying to set to a hash that would install `ruby 2.6.6`. Here is the devbox.json:
```
{
  "packages": [],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "c92ca95afb5043bc6faa0d526460584eccff2277"
  }
}
```

2. Run `devbox add ruby`. You get this output:
```
devbox add ruby

Error: ruby: package not found

To search for packages use https://search.nixos.org/packages
```

**Expected Behavior (fix)**
Instead, ruby should install correctly. Here's the output when using a recent nixpkgs hash:
```
devbox add ruby
Installing nix packages. This may take a while... done.

This plugin sets the following environment variables:
* RUBY_CONFDIR=/Users/daniel/Code/playground/repro-devbox/.devbox/virtenv/ruby
* GEMRC=/Users/daniel/Code/playground/repro-devbox/.devbox/virtenv/ruby/.gemrc
* GEM_HOME=/Users/daniel/Code/playground/repro-devbox/.devbox/virtenv/ruby

To show this information, run `devbox info ruby`

ruby (ruby-2.7.6) is now installed.
```

**Additional context**
```
devbox version -v
Version:     0.2.2
Platform:    darwin_arm64
Commit:      c7d47b13f9b749f0ae5c9b29edbbb4be16b6cca6
Commit Time: 2023-01-13T19:04:12Z
Go Version:  go1.19.4
```

**Comment by ipince** [comment]
FWIW, looks like the `ruby` pkg is indeed defined in the nixpkgs repo at that commit, and it's in the same path/location as it is today:
https://github.com/NixOS/nixpkgs/blob/c92ca95afb5043bc6faa0d526460584eccff2277/pkgs/development/interpreters/ruby/default.nix

**Comment by ipince** [comment]
Does `devbox` support _any_ commit, no matter how far back in history it is?  It looks like there's been roughly 160k commits since `c92ca9`

**Comment by savil** [comment]
this appears to be a limitation of M1 macs. In contrast, when I try with my intel mac it does work fine...

**Comment by loreto** [comment]
The working hypothesis is:
- This particular commit is from before M1s even existed
- As a result the evaluated nix expression does *not* contain the attribute `legacyPackages.aarch64-darwin` but it does contain `legacyPackages.x86_64-darwin`
- On an M1/M2 nix is therefore unable to find anything.

In fact, running nix directly returns:
```
nix search --extra-experimental-features "nix-command flakes" nixpkgs/c92ca95afb5043bc6faa0d526460584eccff2277#ruby
error: no results for the given search term(s)!
```

**Comment by loreto** [comment]
Closing as this is really caused by nix not having the package defined instead of behavior on our end.
