### ISSUE TITLE
devbox shell wrapper fails when mktemp is installed in nix profile

### ISSUE THREAD

**Issue by bketelsen** [jetpack-io/devbox#5]
On an M1 mac with nix, my nix profile already has `mktemp` installed. The devbox shell wrapper is assuming the non-gnu version of `mktemp`, and fails with the cryptic error:

```
❯ devbox init
mktemp: too few X's in template ‘devbox’
→ Downloading version 0.0.2...
✘ Command failed (exit code 23): curl --fail --silent --location --output /devbox_0.0.2_darwin_arm64.tar.gz https://github.com/jetpack-io/devbox/releases/download/0.0.2/devbox_0.0.2_darwin_arm64.tar.gz
```
Google led me to a [stackexchange answer](https://apple.stackexchange.com/questions/387136/updatedb-error-mktemp-too-few-xs-in-template-updatedb) that seems to be relevant.

I messed with the devbox shell script to try to force it to use the mac mktemp but didn't get far. Wanted to report this in case others had similar troubles.

**Comment by loreto** [comment]
Thanks @bketelsen, looking into it. Will report when fixed!

**Comment by bketelsen** [comment]
sweet! can't wait to ease some of the nix pain with a helpful wrapper.

**Comment by vladkosarev** [comment]
I got a similar error in Void Linux running in WSL2
```
$ devbox init
/usr/local/bin/devbox: line 225: arch: readonly variable
mktemp: too few X's in template ‘devbox’
→ Downloading version 0.0.2...
✘ Command failed (exit code 22): curl --fail --silent --location --output /devbox_0.0.2_linux_.tar.gz https://github.com/jetpack-io/devbox/releases/download/0.0.2/devbox_0.0.2_linux_.tar.gz

**Comment by loreto** [comment]
@bketelsen @vladkosarev I believe this should be fixed now. Could you try re-installing with:

```
curl -fsSL https://get.jetpack.io/devbox | bash
```

And seeing if it works now?

**Comment by loreto** [comment]
Closing since it's now working for other users that reported similar issues, but feel free to reopen if you run into it again.

**Comment by bketelsen** [comment]
works as advertised, thanks for the super quick fix!
