### ISSUE TITLE
[Bug]: Direnv integration ignores init_hook changes

### ISSUE THREAD

**Issue by mohsenari** [jetpack-io/devbox#557]
**Current Behavior (bug)**
When using direnv integration. Adding `export FOO=bar` to init_hook won't be included in direnv load.

**Expected Behavior (fix)**
direnv loading should include `init_hook` changes as well. 

**Additional context**
generated `.envrc` file uses `use nix .devbox/gen/shell.nix` to compute the environment. But it should use `print-dev-env` feature of nix and make sure `init_hook` commands run as well (?)

**Comment by Lagoja** [comment]
Released in 0.4.7 for `.envrc` and local project init_hooks
