### ISSUE TITLE
Language Request: Ruby

### ISSUE THREAD

**Issue by olimart** [jetpack-io/devbox#56]

**Comment by ipince** [comment]
Btw, Ruby is already supported (see #164), with Rails support added in #183.

I'll update the docs next. Let me know if you see any issues when trying it out!

**Comment by Lagoja** [comment]
Hello @olimart, we have updated docs for our Ruby integration here: https://www.jetpack.io/devbox/docs/language_support/ruby/

Please let us know if you test them out! We'd also love to hear your feedback on [Discord](https://discord.gg/jetpack-io)

**Comment by olimart** [comment]
Thanks @Lagoja working fine indeed. Next step is to give Rails a try.
