### ISSUE TITLE
[Cloud] Feature request - Set git user & email

### ISSUE THREAD

**Issue by mikenikles** [jetpack-io/devbox#579]
It would be nice to have the `user.name` and `user.email` git config values set automatically when I connect to Devbox Cloud.

Currently, I have to manually set them before I can commit changes. It's not a big deal thanks to automated text expansion tools, but it's an extra step.

**Comment by ipince** [comment]
Thanks for the feedback @mikenikles. This is done in the latest version of Devbox Cloud. Let us know if you find any issues with it!
