### ISSUE TITLE
[Cloud] Feature request - Source `git-completion.bash`

### ISSUE THREAD

**Issue by mikenikles** [jetpack-io/devbox#580]
A nice-to-have request for Devbox Cloud to automatically source https://github.com/git/git/blob/master/contrib/completion/git-completion.bash so git commands auto-complete in the terminal.

The workaround is the following `devbox.json`:

```json
{
  "packages": [
    "curl"
  ],
  "shell": {
    "init_hook": [
      "(cd .. && curl -O https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash && source git-completion.bash)"
    ]
  }
}
```

**Comment by ipince** [comment]
Hi @mikenikles . git commands should be auto-completing on the VS code terminal now. Please let us if that's not working for you. Thanks!

**Comment by mikenikles** [comment]
Works like a charm 🎉!
