### ISSUE TITLE
[Feature Request] Install packages globally with Devbox

### ISSUE THREAD

**Issue by Lagoja** [jetpack-io/devbox#587]
## What use case are we trying to solve?

There are packages that I want to install and configure to use across all my Devbox projects and shells. For example: 

- I want to install and configure an editor, like Emacs, Vim, or VSCode and use it to work on all my devbox projects. I want the configuration and plugins to be the same across all my projects, regardless of whether I run the editor locally or in Devbox Cloud
- I want to configure administration tools like the AWS CLI, setup my configuration + credentials once, and then use them across multiple projects. I don't want to install and setup the credentials separately for each project I'm working on. 

## Current Problem

It is currently not possible to share a single set of packages across multiple projects. 
* Devbox does not support nested Devbox shells. This is by design, to avoid unexpected behavior from nested shells
* We also do not have a way to configure a global set of packages or configuration that is included in every project, meaning IDEs and tools have to be configured separately for each project
* It's possible to hack around these restrictions using our `direnv` integration, but won't work when a user tries to run their setup in Devbox Cloud, since only the local project configuration will be applied

## Proposed Solution  

A proposed solution would have the following properties

- Users should have a way to define global packages and configuration using Devbox ("devbox profile")
- The "devbox profile" should be available whenever a developer starts a Devbox Shell for a local project
- The "devbox profile" should be defined in a `devbox.json` file, so I can share my setup with other developers or sync it across machines
- Whenever I start a `devbox cloud shell`, I should be able to use my "devbox profile" as well as the configuration from my local project.

**Comment by Lagoja** [comment]
Example problem statement from our Discord Channel:

>  I created a project "cli-tools" and it has a bunch of, well, cli tools like awscli2, kubectl, etc. I have this working like a "global configuration" in that when I launch iTerm, it does the "send text at start" to launch the devbox shell so I have those tools available wherever I am (not necessarily in a project). [...]  My issue is if I want to work in another project that uses devbox, I will either have to duplicate the packages in the the other project or I won't have those tools available.

**Comment by Lagoja** [comment]
Released as `devbox global` in 0.4.0

**Comment by rbhanot4739** [comment]
Sorry to hijack this thread, but how can I use the global `devbox.json` located under `~/.local/share/devbox/global/default` to install all the listed packages. For example if I want to move my setup from one machine to another, how do I do this. Currently I do not see any option/flag  to `devbox global add` command to supply the path to `devbox.json` and install all packages automatically.,

**Comment by rbhanot4739** [comment]
@Lagoja Sorry to hijack this thread, but how can I install packages from `~/.local/share/devbox/global/default/devbox.json` when moving from one machine to another. I could see the `devbox global install` but it doesn't do anything for global packages nor I could find an option to provide the `devbox.json` path to it to install from.
