### ISSUE TITLE
docs fix idea: example of devbox.json

### ISSUE THREAD

**Issue by knuckolls** [jetpack-io/devbox#6]
Just spent time reviewing this. I expected to be able to see what a devbox.json file looks like.

I found this:
> Initialize Devbox:
> devbox init
> This creates devbox.json. You should commit this file.

I can do this, but it seems like the docs should have an example devbox.json front and center since that's the artifact people work with.

Hope this helps! Cool idea. :)

**Comment by loreto** [comment]
@knuckolls Thanks for the suggestion. Agreed! I'll have the README updated by tomorrow.

**Comment by loreto** [comment]
Example `devbox.json` now included in the README!
