### ISSUE TITLE
Devbox Add API Error

### ISSUE THREAD

**Issue by gfleetwood** [jetpack-io/devbox#60]
Hello. Anytime I run `devbox add PACKAGE` I get this error:

```
segment 2022/09/03 12:09:56 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp: lookup api.segment.io on 100.64.0.7:53: no such host
segment 2022/09/03 12:09:56 ERROR: 1 messages dropped because they failed to be sent and the client was closed
```

But the package is still added to the json file. It only started today (2022-09-03). I first installed and tried out devbox earlier this week and didn't see that message. I'm on Ubuntu 20.04.

**Comment by loreto** [comment]
I'll take a look today. Thanks for reporting!

**Comment by loreto** [comment]
We think the add command is still working properly and these are just some spurious errors. We'll fix so that it stops printing the errors, but you should still be able to use devbox.

**Comment by gfleetwood** [comment]
Great. What is segment being used for in devbox?

**Comment by Lagoja** [comment]
We're using segment to collect some anonymized metrics on usage, platforms, and errors that will help us improve the product. We have a page explaining how we collect and use the data here: [Telemetry](https://www.jetpack.io/devbox/docs/telemetry/). We do not collect any identifiable information using Segment.

If you want to disable this telemetry, you can set `DO_NOT_TRACK=1` in your environment to opt out. You can also view how we use Segment in our code here: [telemetry.go](https://github.com/jetpack-io/devbox/blob/650e8feb1e76386594bcb2443b3fbc8c07943281/boxcli/midcobra/telemetry.go)

**Comment by gfleetwood** [comment]
Thanks for the info.
