### ISSUE TITLE
[Bug]: `devbox shell` very slow (on slow internet?)

### ISSUE THREAD

**Issue by altano** [jetpack-io/devbox#602]
**Current Behavior (bug)**
I'm currently on a very slow internet connection and `devbox shell` is noticeably _much_ slower. My best guess is that this is connection related. I measured:

`devbox shell` and immediately exiting takes 7.325s
`devbox shell -- echo hello` takes 2.806s

I sometimes see this message when launching a shell:
> direnv: ([/opt/homebrew/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.

**Expected Behavior (fix)**
`devbox shell` should launch <1s.

**Additional context**
```
devbox version -v:
Version:     0.3.3
Platform:    darwin_arm64
Commit:      98bd57ad38c82d1cdced4dde48da1786c821b4b5
Commit Time: 2023-02-03T18:41:12Z
Go Version:  go1.19.5
```

devbox.json:
```
{
  "packages": [
    "nodejs",
    "git",
    "git-branchless"
  ],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
```

**Comment by Lagoja** [comment]
Hey @altano, thanks for reporting this. Agreed those times are much slower than desired. 

> direnv: ([/opt/homebrew/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.

Do you have a .envrc in your project directory? If so and if you can share the contents, we can try to reproduce this.

**Comment by altano** [comment]
Hey @Lagoja thanks for taking a look.

I do have a .envrc but it's just the one devbox creates:

```
# Automatically sets up your devbox environment whenever you cd into this
# directory via our direnv integration:

use_devbox() {
    watch_file devbox.json
    if [ -f .devbox/gen/shell.nix ]; then
        DEVBOX_SHELL_ENABLED_BACKUP=$DEVBOX_SHELL_ENABLED
        use nix .devbox/gen/shell.nix
        eval $(devbox shell --print-env)
        export DEVBOX_SHELL_ENABLED=$DEVBOX_SHELL_ENABLED_BACKUP
    fi
}
use devbox

# check out https://www.jetpack.io/devbox/docs/ide_configuration/direnv/
# for more details
```

**Comment by Lagoja** [comment]
Hey @altano, tested this on some simulated networks, and I reproduced your performance issues. We've discussed internally and are planning on a fix to reduce/minimize network + update calls so that we can improve the performance. 

Thank you again for reporting this!

**Comment by altano** [comment]
Awesome, thank you @Lagoja.

**Comment by Lagoja** [comment]
Hey @altano, we made some updates to our launcher that should fix this. You may need to reinstall the launcher by re-running `curl -fsSL https://get.jetpack.io/devbox | bash` to get the improvement. 

If you give that a try, could you let us know if that improves your startup times?
