### ISSUE TITLE
[Feature Request] Allow adding a package from file system

### ISSUE THREAD

**Issue by amok** [jetpack-io/devbox#668]
It'd be nice to be able to install packages from `nix` files from local FS.

F.i.:

```sh
devbox add /path/to/default.nix
devbox add path/to/package
```
---

**Usecases**

1)
Let say you have a small dev proxy server `my-development-proxy-server` written in `node` and It's not part of the  main app.  `my-development-proxy-server/default.nix` would be something like

```nix
# This is a minimal `default.nix` by yarn-plugin-nixify. You can customize it
# as needed, it will not be overwritten by the plugin.

{ pkgs ? import <nixpkgs> { } }:

pkgs.callPackage ./yarn-project.nix { } { src = ./.; }
```

Then `shell.nix` would look something like

```nix
let
  pkgs = import <nixpkgs> { };
  myDevelopemntProxyServer = import ./my-development-proxy-server;
  python = pkgs.python38;
  .....
in
pkgs.mkShell {
  packages = [
		python
		myDevelopemntProxyServer
		....
  ];
}
```

For the time being as far as I know it's not possible to `devbox add ./my-development-proxy-server`

2)
Another use case is overriding package attrs. Is there a way to implement the following with `devbox`?:

```nix
let
  pkgs = import <nixpkgs> { };
  nginx = pkgs.nginx.override { modules = [ pkgs.nginxModules.njs ]; };
  nodejs = pkgs.nodejs-slim-14_x;
  yarn = pkgs.yarn.override { inherit nodejs; };
  ...
```

As an option, we could have `yarn.nix` like:

```nix
let
  pkgs = import <nixpkgs> { };
  nodejs = pkgs.nodejs-slim-14_x;
in
pkgs.yarn.override { inherit nodejs; }
```

and do `devbox add ./yarn.nix`

---

Unfortunately, this blocks me switching from "raw" nix to `devbox` (the tool looks very exciting)
Let me please know if I am missing something. 

**Similar issues**: #267 #117 #21 

**PS** Thank you for the awesome tool

**Comment by Lagoja** [comment]
Hey @amok, thanks for filing this issue. We really love the idea and have been discussing it within our team, since this could be a great bridge for existing nix projects to take advantage of Devbox. 

We're reviewing the idea internally to see if we can slot it for an upcoming release.

**Comment by Lagoja** [comment]
See #866, which will allow developers to add local flakes as a source. Would be great to get your thoughts on what else to include.
