### ISSUE TITLE
Should devbox work without sudo?

### ISSUE THREAD

**Issue by korjavin** [jetpack-io/devbox#67]
```
 devbox shell
error: getting status of /nix/var/nix/daemon-socket/socket: Permission denied
```

**Comment by morey-tech** [comment]
That error seems to indicate that `sudo` is required to use `nix` on your system. This is likely a result of how `nix` was installed and unrelated to `devbox`. You could check this by running `nix-env --version` and see if you need `sudo`. 

A potential solution is to grant your user access to the socket [as described in the docs here](https://nixos.org/manual/nix/stable/installation/multi-user.html#restricting-access). But I can say in my case this wasn't necessary when using [the install script on Linux](https://nix.dev/tutorials/install-nix#linux).

**Comment by korjavin** [comment]
It worked, thank you!

**Comment by mentos1386** [comment]
For arch users https://wiki.archlinux.org/title/Nix#Permission_denied
