### ISSUE TITLE
Language Detection: Nim

### ISSUE THREAD

**Issue by sergiosouzalima** [jetpack-io/devbox#68]
https://nim-lang.org

**Comment by Lagoja** [comment]
Definitely a language we'll look into once we release a Planner Framework to improve language support. See #95 for discussion and more details

**Comment by Lagoja** [comment]
Basic Nim-lang support can be found here: https://www.jetpack.io/devbox/docs/devbox_examples/languages/nim/

Since we deprecated build, we will no longer ship the Planner detection for it.
