### ISSUE TITLE
[Bug]: Adding anything to a new empty project will fail

### ISSUE THREAD

**Issue by Nymuxyzo** [jetpack-io/devbox#693]
**Current Behavior (bug)**
andre /d/p/officebox> `DEVBOX_DEBUG=1 devbox add ruby_3_1`
[DEBUG] 2023/02/26 00:48:44 /home/runner/work/devbox/devbox/internal/boxcli/midcobra/debug.go:49: Debug mode enabled.
[DEBUG] 2023/02/26 00:48:44 /home/runner/work/devbox/devbox/internal/impl/config.go:139: findProjectDir: path is 
[DEBUG] 2023/02/26 00:48:44 /home/runner/work/devbox/devbox/internal/impl/config.go:181: finding devbox.json in dir: /devenv/projects/officebox
Error: /bin/sh: line 1: /home/andre/.nix-profile/etc/profile.d/nix.sh: No such file or directory
: exit status 1

[DEBUG] 2023/02/26 00:48:44 /home/runner/work/devbox/devbox/internal/boxcli/midcobra/debug.go:69: Command stderr: 
[DEBUG] 2023/02/26 00:48:44 /home/runner/work/devbox/devbox/internal/boxcli/midcobra/debug.go:71: 
ExecutionID:3e87e4f10ba9499885c1c2e4a5b038d1

go.jetpack.io/devbox/internal/nix.SourceNixEnv
	/home/runner/work/devbox/devbox/internal/nix/source.go:51
go.jetpack.io/devbox/internal/boxcli.ensureNixInstalled
	/home/runner/work/devbox/devbox/internal/boxcli/setup.go:56
github.com/spf13/cobra.(*Command).execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:901
github.com/spf13/cobra.(*Command).ExecuteC
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
go.jetpack.io/devbox/internal/boxcli/midcobra.(*midcobraExecutable).Execute
	/home/runner/work/devbox/devbox/internal/boxcli/midcobra/midcobra.go:66
go.jetpack.io/devbox/internal/boxcli.Execute
	/home/runner/work/devbox/devbox/internal/boxcli/root.go:70
go.jetpack.io/devbox/internal/boxcli.Main
	/home/runner/work/devbox/devbox/internal/boxcli/root.go:79
main.main
	/home/runner/work/devbox/devbox/cmd/devbox/main.go:11
runtime.main
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/proc.go:250
runtime.goexit
	/opt/hostedtoolcache/go/1.19.6/x64/src/runtime/asm_amd64.s:1594

**Additional context**
Please include the output of `devbox version -v`:
Version:     0.4.1
Platform:    linux_amd64
Commit:      c4de4dc021d7790d61866ff2af474354c72e21ed
Commit Time: 2023-02-25T21:25:13Z
Go Version:  go1.19.6

and a copy of your `devbox.json` file:
It is empty, because I want to add ruby_3_1

```
{
  "packages": [],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
```

**Comment by Lagoja** [comment]
Hey @andre-gitdev Thanks for reporting. Looks like the nix shell script is missing. To help debug, can you share the contents of your ~/.nix_profile/etc folder?

Additionally, did you have Nix installed prior to installing Devbox?

**Comment by Lagoja** [comment]
@andre-gitdev It looks like the nix-installer may be putting the binaries in a location that we aren't checking. Can you see if `ls $XDG_DATA_HOME/nix/profile` returns anything?

**Comment by Lagoja** [comment]
Hey @andre-gitdev, did you happen to install devbox as the root user on your machine? This can sometimes cause issues where the nix binaries, scripts, and profiles are not accessible to other users.

**Comment by Lagoja** [comment]
Hey @andre-gitdev, sorry for the issues you've been having. We think there were some bugs in the official Nix Install script that may have caused some problems that should be resolved now: 

To uninstall Nix on Linux, you need to run the following commands: 

```
rm -rf $HOME/{.nix-channels,.nix-defexpr,.nix-profile,.config/nixpkgs}
sudo rm -rf /nix
```

You'll also need to remove the `. "$HOME/.nix-profile/etc/profile.d/nix.sh"`

Once you've done this, you can try re-installing nix by running `devbox setup nix`. This should work in 0.4.2, but if not the steps above will work to remove Nix from your systems.

To remove devbox itself, try: 

```
rm -rf $HOME/.cache/devbox
sudo rm /usr/local/bin/devbox
```

**Comment by kiwicopple** [comment]
@Lagoja  - just want to say thanks for your [comment](https://github.com/jetify-com/devbox/issues/693#issuecomment-1454030406), it helped with debugging
