### ISSUE TITLE
First call to `devbox shell` can take a while

### ISSUE THREAD

**Issue by loreto** [jetpack-io/devbox#7]
And there's no progress bar or other indication of progress which makes users think it's stuck.

**Comment by datashaman** [comment]
I've tried installing various tools. As you say, it just hangs there. Is it doing anything? There are no options for debugging or logging on the CLI. It _appears_ not to work at all.

**Comment by loreto** [comment]
It is installing, and it will complete... the first time nix run takes a while because it installs a bunch of dependencies for the first time. 

We'll address by giving an idea of progress in the terminal.

**Comment by adrianhopebailie** [comment]
What about a command to explicitly install dependancies without spawning the shell?

`devbox install`

**Comment by carlthome** [comment]
This was pretty confusing UX to me too in my test spin unfortunately. At least with `nix build` and `nix shell` I'm getting a lot of helpful progress bars for binary cache downloads and compiling. Staring at a `devbox shell` having no insight into how long it will take or if it's even doing anything is a pretty bad onboarding experience TBH.

**Comment by acheong08** [comment]
How long should `devbox shell` be running for? I have extremely slow internet and it's been running for two hours already...

**Comment by loreto** [comment]
> How long should `devbox shell` be running for? I have extremely slow internet and it's been running for two hours already...

Wow, that's definitely too long. This is the top issue we're working on – I'll circle back with an update later today.

**Comment by loreto** [comment]
OK, folks, we just released a new version of `devbox` that should address some of these concerns. If you installed via our install script, you should get the new version automatically next time you run the binary.

We did two changes:
1. We now fetch nix packages via a tarball, which is faster than the previous git-based approach.
2. We now print to the console explaining we are setting up nix. For now it's just a single line that we print, but over-time we'll make it a more sophisticated progress bar.

**Comment by loreto** [comment]
OK, I'm closing this issue because I think we addressed the most important bottlenecks. But feel free to open a new issue if you're seeing other problems related to speed.

@adrianhopebailie I opened this issue: https://github.com/jetpack-io/devbox/issues/22 to track your idea of having a `devbox install`
