### ISSUE TITLE
[Bug]: Devbox 0.42 error on fish shell. (Error: execute shellrc template: shellrc_fish)

### ISSUE THREAD

**Issue by duckduckio** [jetpack-io/devbox#719]
**Current Behavior (bug)**
`devbox shell` doesn't work when the default shell is set to `fish`, but it works fine when the default shell is set to `bash`. I tried to uninstall and reinstall, but it doesn't work.

The error output:

> `~ devbox shell`
> Ensuring packages are installed.
> Starting a devbox shell...
> Error: execute shellrc template: template: shellrc_fish:20:7: executing "shellrc_fish" at <.UnifiedEnv>: > can't evaluate field UnifiedEnv in type struct { ProjectDir string; OriginalInit string; OriginalInitPath string; UserHook string; PluginInitHook string; PathPrepend string; ScriptCommand string; ShellStartTime string; HistoryFile string; ExportEnv string }

**Expected Behavior (fix)**

**Additional context**
> `devbox version -v`

```text
Version:     0.4.2
Platform:    linux_amd64
Commit:      c249fa1da3a24eb686220da378bc9dcdc6d49680
Commit Time: 2023-03-02T21:16:52Z
Go Version:  go1.19.6
```

> *`devbox.json`*

```text
{
  "packages": [],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
```

**Comment by gcurtis** [comment]
Hi @duckduckio thanks for reporting this. This does look like a bug in Devbox with fish shells. I'll take a look at getting a fix out this week.
