### ISSUE TITLE
Language Detection: node.js

### ISSUE THREAD

**Issue by ebauger** [jetpack-io/devbox#72]
fetch node version information from package.json, .nvmrc or .node-version : https://render.com/docs/node-version

**Comment by LucilleH** [comment]
@ebauger in the latest main we added version detection, but only by looking at the `package.json` file. Would that satisfy your use case? 

The current Node version detection logic will go out in the next release.

**Comment by ebauger** [comment]
Yes for me, but some older project will use the file method depending of the node version.
