### ISSUE TITLE
devbox setting PS1 breaks shell themes like powerlevel10k

### ISSUE THREAD

**Issue by kmaris** [jetpack-io/devbox#74]
As per here: https://github.com/jetpack-io/devbox/blob/6f39e906cd5f58219618dcb1b3b50fb3520cd065/nix/nix.go#L59

Blindly setting PS1 can mess with custom themes for folks' shell prompts. I personally found it enough just to have the environment variable but I know others asked for it. Perhaps tweaking the shell can be optional?

**Comment by Lagoja** [comment]
Thanks for the feedback. Some ideas to address this:

- Make it an option during installation ("Do you want Jetpack to add an indicator to your prompt?")

- Provide users with a snippet that they can add to their shell profile

- Add an Env variable that toggles off the default indicator (so developers can configure their own using the environment variable).

**Comment by kmaris** [comment]
Personally, the third option seems best. If folks are running custom themes, chances are they're comfortable with environment tweaking (and perhaps the theme itself) to address toggling the behavior.

If you did the first option, would folks have to re-install to change the behavior? Across workstations? That could get tiring.

And the second option works but I think environment vars are more accessible and portable across shells and OS'es.

My 2 cents anyhow :) Thanks for considering this!

**Comment by gcurtis** [comment]
I agree that controlling the prompt customization with an env var is the best bet. We could...

- Check if `DEVBOX_NO_PROMPT` is set. If it is, don't change `PS1` in the post-init hook.
- Introduce a `DEVBOX_PROMPT` env var.
	- If left unset, we default to the current behavior of updating the prompt.
	- If set to empty, we leave the prompt alone.
	- If set to anything else, we change the prompt to its value.

I'm not sure if `DEVBOX_PROMPT` would be more convenient than having users add `if [ -n "$DEVBOX_SHELL_ENABLED" ]; then export PS1=foo; fi` to their shell rc.

**Comment by gcurtis** [comment]
Just wanted to give an update here on how we're planning to fix this for the next release.

Now that devbox supports setting shell hooks in `devbox.json`, we're going to remove the builtin logic that sets the prompt entirely. Instead, `devbox init` will generate a `devbox.json` that sets a prompt by default with something like:

```json
{
  "shell": {
    "init_hook": "export PS1='(devbox)$ '"
  }
}
```

That way the prompt can be disabled by simply removing or changing the hook.

**Comment by kmaris** [comment]
Sounds reasonable to me! Are you still planning to export `DEVBOX_SHELL_ENABLED`?

**Comment by gcurtis** [comment]
Yep! `DEVBOX_SHELL_ENABLED` will still be there.
