### ISSUE TITLE
[Feature Request] Add completion for scripts

### ISSUE THREAD

**Issue by hezhizhen** [jetpack-io/devbox#765]
When I hit tab after `devbox run `, it can provide all the script names (just like Makefile).

**Comment by savil** [comment]
this would be great to enable

**Comment by mikeland86** [comment]
@hezhizhen that's a really good idea. Is this something you can take on? Happy to brainstorm approaches if needed

**Comment by hezhizhen** [comment]
> @hezhizhen that's a really good idea. Is this something you can take on? Happy to brainstorm approaches if needed

Sure, I can try it. But I have no idea how completion works. Does it rely on shell completions?

**Comment by hezhizhen** [comment]
I can add scripts to `devbox run` command as cobra commands and their names can be autocompleted. But it requires devbox to build itself every time users add or remove scripts.

**Comment by hezhizhen** [comment]
> I can add scripts to `devbox run` command as cobra commands and their names can be autocompleted. But it requires devbox to build itself every time users add or remove scripts.

See https://github.com/jetpack-io/devbox/pull/774

**Comment by hezhizhen** [comment]
> I've noticed that cobra command has field `ValidArgs` and `ValidArgsFunction`. Maybe I can use them.

See https://github.com/jetpack-io/devbox/pull/775 . I think this solution is better.

**Comment by gcurtis** [comment]
Thanks again @hezhizhen for taking the time to implement this.

Closed by #775.
