### ISSUE TITLE
Feature Request: support building containers for nodejs apps

### ISSUE THREAD

**Issue by crisdosyago** [jetpack-io/devbox#8]
Just a question. Understand if you're not planning this. 

Cool looking project!

**Comment by robrich** [comment]
You can add [nodejs](https://search.nixos.org/packages?query=nodejs) package to your Devbox shell, and then dotnet run inside Devbox. We do need to build the Node.js detection when you generate an image though. Thanks for the feature request.

**Comment by loreto** [comment]
As @robrich mentioned:
+ For the shell functionality, we already support nodejs – and you can install [any of the versions listed here](https://github.com/jetpack-io/devbox/issues/8).
+ For the container support, we are planning to add nodejs pretty soon. I'll repurpose this ticket to track the container support and we'll let you know as soon as we add it.

**Comment by MasterOdin** [comment]
@loreto It looks like the link you put just links back to this ticket?

**Comment by loreto** [comment]
Sorry!

Here's the right link: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=nodejs
