### ISSUE TITLE
devbox shell changes locale `LC_CTYPE` to `C`

### ISSUE THREAD

**Issue by lucasrla** [jetpack-io/devbox#80]
Thanks for creating Devbox. It's got potential!

While testing it out, I ran into the following issue: on macOS Monterey `devbox shell` changes my `LC_CTYPE` from `"UTF-8"` to `"C"`. This is causing me trouble with code that has Unicode (non-ASCII) characters.

It looks like that @rdlu [#17 (comment)](https://github.com/jetpack-io/devbox/issues/17#issuecomment-1228444054) already ran into a very similar issue:

> When I check locale from my shell it's indeed showing en_US.UTF-8 (my "real" shell), but when I run the iex (similar to ipython or irb), I see that the locale is not really UTF8. This is potentially another issue for my code.

It would be great if, instead of setting locale env vars to `C`, devbox shell could automatically "import" my current vars into it.

An alternative, temporary workaround are shell hooks ([#42](https://github.com/jetpack-io/devbox/issues/42), [#45](https://github.com/jetpack-io/devbox/pull/45)). That would at least make setting env variables easier (e.g. `export LC_CTYPE=UTF-8` on init).

***

The issue:

```sh
$ devbox version
0.0.4

$ devbox shell
...

# the error I originally ran into:
$ bundle install

[!] There was an error while loading `example.gemspec`: invalid byte sequence in US-ASCII. Bundler cannot continue.
...

# this fixes the error:
$ LC_CTYPE=UTF-8 bundle install
...
```

My `locale` on zsh (outside devbox shell) is:

```sh
$ locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

# the above most likely is the default on macOS
# I am not changing/exporting anything related to locale in `.zshrc`, `.zprofile`, etc
# see also: https://swi-prolog.discourse.group/t/default-locale-and-encoding-settings-on-macos/4974
```

On a devbox shell:

```sh
$ locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by loreto** [comment]
Thanks for reporting. Looking into it.

**Comment by NSilv** [comment]
Tuning in cause I have the exact same problem: the issue seems to be that the nix-shell '--pure' option doesn't carry over the LOCALE (source: https://github.com/NixOS/nix/issues/318). For iex, prepending LANG=C.UTF-8 to iex removed the warning, but I haven't tested if unicode works properly yet. Another way I've been able to make it work is adding `export LANG=C.UTF-8` to shell.nix, then running it manually rather than with devbox (devbox resets the shell.nix file every time).
