### ISSUE TITLE
[Bug]: prompt hint from devbox mess up my multi line prompt in fish

### ISSUE THREAD

**Issue by paletteOvO** [jetpack-io/devbox#845]
**Current Behavior (bug)**
![image](https://user-images.githubusercontent.com/16734391/228701971-a79e7637-1d1e-49f0-a75f-71d93854468f.png)

**Expected Behavior (fix)**
Maybe some kind like that?
![image](https://user-images.githubusercontent.com/16734391/228704116-7fd39d1b-a26a-4e7e-9252-d708ab9e02cc.png)

Actually, I would prefer just to disable the built-in hint since I have my prompt theme. An [issue](https://github.com/jetpack-io/devbox/issues/108) about that has been opened before. It seems to be discussed in the [issue](https://github.com/jetpack-io/devbox/issues/74) but the relevant [pull request](https://github.com/jetpack-io/devbox/pull/145) was closed and seems no any new and the code is still [here](https://github.com/jetpack-io/devbox/blob/f8d286d9095571554eeb0e62987f4f36c547377e/internal/impl/shellrc.tmpl#L41) and [here](https://github.com/jetpack-io/devbox/blob/f8d286d9095571554eeb0e62987f4f36c547377e/internal/impl/shellrc_fish.tmpl#L43)

**Additional context**
Please include the output of `devbox version -v` and
a copy of your `devbox.json` file.
```
Version:     0.4.5
Platform:    linux_amd64
Commit:      64d31f597940166ba55efa9cacf8bd6ceca392c5
Commit Time: 2023-03-27T21:50:28Z
Go Version:  go1.19.7
```
```
{
  "packages": [],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
```

**Comment by paletteOvO** [comment]
> Thanks for the report, @paletteOvO ! Could you share your fish prompt code, and/or the theme so that we can more easily repro?

Sure
```
#!/usr/bin/fish

~/.cargo/bin/starship init fish | source
```
[starship.toml.txt](https://github.com/jetpack-io/devbox/files/11113797/starship.toml.txt)

**Comment by shousper** [comment]
FYI, same problem using starship + zsh 👍🏻 Would be good if there is an option to opt-out of the prompt change applied by devbox 🙏🏻

**Comment by dcd-arnold** [comment]
Getting my prompt messed up makes me edgy every time I am in a devbox. @paletteOvO thank you for searching for the linked issues.

**Comment by amrox** [comment]
This issue is affecting me as well, using `zsh` + `starship`.

```
❯ devbox shell
Starting a devbox shell...
(devbox)
~/devbox-test via ❄️  impure (nix-shell-env)
```

Interestingly, I don't get the same behavior in `bash` + `starship` on another machine

```
❯ devbox shell
Starting a devbox shell...

~/devbox-test via ❄️  impure (nix-shell-env)
❯
```

Another vote for more control over prompt injection / `PS1` from me 😄
