### ISSUE TITLE
[Bug]: "$(pwd)" syntax not supported in fish < 3.4

### ISSUE THREAD

**Issue by sgentle** [jetpack-io/devbox#850]
**Current Behavior (bug)**
```
/var/folders/dp/hwmtf9bs5hn9z2mm2t8g38z80000gn/T/devbox2349844254/config.fish (line 146): $(...) is not supported. In fish, please use '(pwd)'.
set workingDir "$(pwd)"
                ^
from sourcing file /var/folders/dp/hwmtf9bs5hn9z2mm2t8g38z80000gn/T/devbox2349844254/config.fish
```

**Expected Behavior (fix)**
```
```

**Additional context**
The offending line is [/internal/impl/shellrc_fish.tmpl:55](https://github.com/jetpack-io/devbox/blob/f8d286d9095571554eeb0e62987f4f36c547377e/internal/impl/shellrc_fish.tmpl#L55) though I believe line 85 would have a similar issue.

I'm running devbox 0.4.5 and fish 3.3 (not for any particular reason, just haven't upgraded) and I'm assuming this is an accidental incompatibility.

You may not need the quotes anyway – fish doesn't split command substitution on spaces, so this works:
```
/tmp > mkdir 'hello world'
/tmp > cd 'hello world'
/tmp/hello world > set foo (pwd)
/tmp/hello world > cd ..
/tmp > cd $foo
/tmp/hello world >
```

**Comment by savil** [comment]
@sgentle thanks for reporting this bug. I can repro it. Will submit a PR soon (a bit new to fish so want to orient myself more).
