### ISSUE TITLE
[Bug]: devbox shell startup occassionally ~20-30s 

### ISSUE THREAD

**Issue by altano** [jetpack-io/devbox#881]
**Current Behavior (bug)**
I frequently get `devbox shell` times of 20-30s. MOST of the time startup is very short, e.g. I just ran  `time devbox run echo hello` and got 0.1s. But occasionally, usually after not using my computer for a day or two, my first `devbox shell` will take a really long time.

```
➜  devbox shell
Ensuring packages are installed.
Starting a devbox shell...
dockedirenv: loading ~/src/docker/.envrc
direnv: using devbox
direnv: using nix .devbox/gen/shell.nix
r compose up -d --build
direnv: ([/opt/homebrew/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
```
... ~20-30 second pause ...

```
direnv: export +NIX_BUILD_TOP +TEMP +TEMPDIR +TMP ~LD_LIBRARY_PATH ~LIBRARY_PATH ~TMPDIR ~buildPhase
direnv: loading ~/src/docker/everace/.envrc
direnv: export +DOCKER_CONTEXT +DOCKER_HOST
```

**Expected Behavior (fix)**
<1s shell startup, consistently

**Additional context**
```
(devbox) ➜  devbox version -v
Version:     0.4.6
Platform:    darwin_arm64
Commit:      2ddf1856034dd544c5ff966e20e7bef1f3897fbb
Commit Time: 2023-03-31T19:14:57Z
Go Version:  go1.19.7
```
devbox.json
```
{
  "packages": ["docker-client"],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
```

.envrc
```
# Automatically sets up your devbox environment whenever you cd into this
# directory via our direnv integration:

use_devbox() {
    watch_file devbox.json
    if [ -f .devbox/gen/shell.nix ]; then
        DEVBOX_SHELL_ENABLED_BACKUP=$DEVBOX_SHELL_ENABLED
        use nix .devbox/gen/shell.nix
        eval $(devbox shell --print-env)
        export DEVBOX_SHELL_ENABLED=$DEVBOX_SHELL_ENABLED_BACKUP
    fi
}
use devbox

# check out https://www.jetpack.io/devbox/docs/ide_configuration/direnv/
# for more details
```

**Comment by savil** [comment]
@altano thanks for the bug report. Discussing internally and will follow up.

**Comment by altano** [comment]
Sounds good, thanks. And let me know if there are any diagnostic steps I can take. I’m happy to be a guinea pig.

**Comment by savil** [comment]
@altano let me circle back on whether the debug logging would help.

From the output you pasted above, something I don't quite understand: 
why does doing `devbox shell` print the `direnv: ....` output? I would expect that doing `cd <directory of devbox project>` would print the `direnv: ...` output.


We also made a few changes today that should come out in the next release that I think will help the `.envrc` run faster. 

Specifically:
1. https://github.com/jetpack-io/devbox/pull/898 will speed up the `devbox shell --print-env` time. It'll be instantaneous, except when devbox.json changes are made.
2. https://github.com/jetpack-io/devbox/pull/902 removes the `use nix shell.nix` line, which is no longer needed. This should half the time.

**Comment by savil** [comment]
🤔 I ran into a direnv slowdown when using it on a new repository. I think it may have been downloading nix packages in the background. 

@altano this is unlikely, but thought I'd double check whether you have some job which periodically runs the nix garbage-collector in the background? That may explain the delay in your case.

**Comment by altano** [comment]
Sorry for the delay in replying!

> From the output you pasted above, something I don't quite understand:
why does doing devbox shell print the direnv: .... output? I would expect that doing cd <directory of devbox project> would print the direnv: ... output.

I'm opening these shells in VS Code w/ the devbox extension (that makes new terminals start a devbox shell) so I guess that's all happening at the same time?

When it's fast it looks like this

<img width="1277" alt="image" src="https://github.com/jetpack-io/devbox/assets/1009/05b5003e-57c2-4c2a-970f-bddd54f40f9a">

Note that I didn't type `devbox shell`, that was done by the extension.

> @altano this is unlikely, but thought I'd double check whether you have some job which periodically runs the nix garbage-collector in the background? That may explain the delay in your case.

Not one I've manually setup. I'm using the [Determinate Systems nix installer](https://github.com/DeterminateSystems/nix-installer) (upon recommendations from the devbox team in another github issue). Perhaps it comes with some automatic gc they don't prominently advertise on their front page?

**Comment by savil** [comment]
Thanks for the update. Let me look into the installer's default settings...

**Comment by altano** [comment]
I am reporting back with more clues. I haven't touched my personal machine in many days, came back, hit an indefinite hang in devbox (still have no shell after 20+ minutes). I noticed Activity Monitor was very unresponsive and using a ton of CPU when I opened it, which was very suspect. I checked how many devbox processes I have and this is what I see:

```
➜  src ps ax | grep devbox | wc -l
    4562
```

It looks like I have 4,562 devbox processes, evenly split between these two:

```
➜  src ps ax | grep devbox | head -n 100
16709 s002  S+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox devbox
  134 s005  S+     0:00.00 /bin/bash /Users/alan/src/alan.norbauer.com/.devbox/virtenv/.wrappers/bin/git -C /Users/alan/src/alan.norbauer.com/.devbox/gen/flake init
  135 s005  S+     0:00.05 /Users/alan/.cache/devbox/bin/0.5.2_darwin_arm64/devbox shellenv --use-cached-print-dev-env
  193 s005  S+     0:00.00 /bin/bash /Users/alan/src/alan.norbauer.com/.devbox/virtenv/.wrappers/bin/git -C /Users/alan/src/alan.norbauer.com/.devbox/gen/flake init
  194 s005  S+     0:00.05 /Users/alan/.cache/devbox/bin/0.5.2_darwin_arm64/devbox shellenv --use-cached-print-dev-env
  252 s005  S+     0:00.00 /bin/bash /Users/alan/src/alan.norbauer.com/.devbox/virtenv/.wrappers/bin/git -C /Users/alan/src/alan.norbauer.com/.devbox/gen/flake init
  253 s005  S+     0:00.05 /Users/alan/.cache/devbox/bin/0.5.2_darwin_arm64/devbox shellenv --use-cached-print-dev-env
  331 s005  S+     0:00.00 /bin/bash /Users/alan/src/alan.norbauer.com/.devbox/virtenv/.wrappers/bin/git -C /Users/alan/src/alan.norbauer.com/.devbox/gen/flake init
  340 s005  S+     0:00.05 /Users/alan/.cache/devbox/bin/0.5.2_darwin_arm64/devbox shellenv --use-cached-print-dev-env
  445 s005  S+     0:00.00 /bin/bash /Users/alan/src/alan.norbauer.com/.devbox/virtenv/.wrappers/bin/git -C /Users/alan/src/alan.norbauer.com/.devbox/gen/flake init
...
```

This number is slowly shrinking: I waited a couple minutes and it was down to 4,454 processes, ~100 fewer than earlier.

**Comment by altano** [comment]
Also, in case this is worth noting:
- this project had the old style .envrc. I just force updated it to the `eval "$(devbox generate direnv --print-envrc)"` style.
- I'm on devbox 0.5.2:
```
Version:     0.5.2
Platform:    darwin_arm64
Commit:      8f579b2c45c730742cbf9b7c400f247abf902775
Commit Time: 2023-05-18T16:18:52Z
Go Version:  go1.20.4
Launcher:    0.2.0
```

**Comment by savil** [comment]
@altano sorry to hear about this experience. Thanks for sharing the detailed output. That did help. 

Discussing internally, we're thinking there is a form of infinite loop happening with how we derive the shell environment from the `virtenv/.wrappers/bin/git` binary wrapper.

To confirm this theory, could you try the following steps:
- `cd` outside the devbox-project directory
- delete `<devbox-project-dir>/.devbox/local.lock` and `<devbox-project-dir>/.devbox/.nix-print-dev-env-cache`
- `cd` into the direnv-enabled devbox-project directory

If this does again lead to a lot of `devbox` processes being spawned, then it would confirm this theory.

**Comment by savil** [comment]
Also, is `/Users/alan/src/alan.norbauer.com/` the path to your devbox-project that has `git` and `docker-client` as packages? If not, is there some situation of nested devbox-projects involved here?

**Comment by altano** [comment]
> Discussing internally, we're thinking there is a form of infinite loop happening with how we derive the shell environment from the `virtenv/.wrappers/bin/git` binary wrapper.
> 
> To confirm this theory, could you try the following steps:

Those steps didn't trigger the problem. I went back to the old .envrc (which I was using when I hit the issue yesterday) to see if it triggered the problem, but it actually does nothing when I delete the .devbox dir because of the `if [ -f .devbox/gen/shell.nix ]; then` line.

> Also, is /Users/alan/src/alan.norbauer.com/ the path to your devbox-project that has git and docker-client as packages? If not, is there some situation of nested devbox-projects involved here?

Sorry, I've been pasting output from different projects. The `~/src/alan.norbauer.com` project is NOT nested in the docker one and has a very simple devbox.json:

```json
{
  "packages": ["nodejs", "git", "git-branchless"],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
```

Interestingly, you mentioned a git wrapper: I'm using `git-branchless`, I have it in my devbox, and in ~/.zshrc I have this:

`alias git='git-branchless wrap --'`

In my devbox shell, `git` is that alias:

```
➜  which git
git: aliased to git-branchless wrap --
```

I wonder if double-wrapping git is causing the issue?

**Comment by mikeland86** [comment]
@altano yeah, I think the git wrapping may be the issue (exposing an existing devbox bug). Devbox creates wrappers for binaries to ensure nix setup hooks run (and any other environment that needs to be setup).

This [PR](https://github.com/jetpack-io/devbox/pull/1067) addresses a bug in the wrappers but I don't think it caused your issue.

The devbox bin wrappers are only needed when the environment doesn't match. In that case they call `eval "$(devbox shellenv)"` to compute the correct environment. The problem is that if that call uses any devbox wrapped binaries, we may get stuck in an infinite loop. I'm not entirely sure where the infinite loop was triggered in your setup,  but it's definitely theoretically possible to trigger one.


One relatively simple fix is prevent shellenv-ception via environment variables. We're trying to understand the implications of doing this since it could prevent binaries from running in the expected environment.

**Comment by altano** [comment]
Sounds good. Thank you for investigating.

And just let me know how I can help. I can guinea pig PRs or test potential ways of reproducing the issue or whatever.

**Comment by ckoehn** [comment]
I'm experience a similar problem after installing `coreutils` with `devbox global add coreutils`. The installation actually never finished and when I open a new terminal it hangs until I use `Ctrl + c`. At the same time I can see a lot of devbox processes:

```
ckoehn           55021   1.2  0.0 408627440   2128 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54996   1.2  0.0 408627440   2128 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54971   1.2  0.0 408627440   2128 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54946   1.2  0.0 408627440   2096 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           55046   0.9  0.0 408627440   2144 s001  R+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           55045   0.8  0.0 408627648   2992 s001  S+   10:43PM   0:00.00 /nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash /Users/ckoehn/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/bin/tr [:lower:] [:upper:]
ckoehn           55020   0.8  0.0 408627648   2992 s001  S+   10:43PM   0:00.00 /nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash /Users/ckoehn/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/bin/tr [:lower:] [:upper:]
ckoehn           54995   0.8  0.0 408627648   2992 s001  S+   10:43PM   0:00.00 /nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash /Users/ckoehn/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/bin/tr [:lower:] [:upper:]
ckoehn           54921   0.8  0.0 408627440   2128 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54970   0.8  0.0 408627648   2992 s001  S+   10:43PM   0:00.00 /nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash /Users/ckoehn/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/bin/tr [:lower:] [:upper:]
ckoehn           54945   0.8  0.0 408627648   2992 s001  S+   10:43PM   0:00.00 /nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash /Users/ckoehn/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/bin/tr [:lower:] [:upper:]
ckoehn           54871   0.7  0.0 408627440   2128 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54896   0.7  0.0 408627440   2096 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54821   0.7  0.0 408627440   2128 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54846   0.7  0.0 408627440   2096 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54920   0.4  0.0 408627648   2992 s001  S+   10:43PM   0:00.00 /nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash /Users/ckoehn/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/bin/tr [:lower:] [:upper:]
ckoehn           54771   0.4  0.0 408627440   2096 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54746   0.4  0.0 408627440   2096 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54895   0.4  0.0 408627648   2992 s001  S+   10:43PM   0:00.00 /nix/store/mxvgjwzdvrl81plvgqnzbrqb14ccnji6-bash-5.2-p15/bin/bash /Users/ckoehn/.local/share/devbox/global/default/.devbox/virtenv/.wrappers/bin/tr [:lower:] [:upper:]
ckoehn           54721   0.4  0.0 408627440   2096 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
ckoehn           54696   0.4  0.0 408627440   2128 s001  S+   10:43PM   0:00.00 /bin/bash /usr/local/bin/devbox shellenv only-path-without-wrappers
...
```

I'm not exactly sure if this is related, but I'm happy to create a separate report if necessary.

devbox version: 0.5.6
Operating system: Mac OSX Ventura 13.4.1

**Comment by mohsenari** [comment]
@ckoehn thanks for reporting this. There is a known issue with `coreutils` package on macos getting stuck in this loop. As a workaround while we fix this, you can try installing `uutil-coreutils` package instead which is an alternative to `coreutils`.

**Comment by altano** [comment]
FWIW I haven’t hit this issue in at least many weeks. It’s been totally smooth sailing for me.

I have upgraded both devbox and the direnv script in all my active projects so I assume something got fixed and I’m now benefiting from it.

thank you all for your hard work on this great project

**Comment by ckoehn** [comment]
@mohsenari Do you have any advice how I get `devbox` in a usable state again until the fix has been released?

**Comment by mohsenari** [comment]
@ckoehn There are a couple of things you can do to make devbox work:
1. The easier thing to do is that, in your devbox.json replace `coreutils@latest` with `uutil-coreutils@latest`. Then delete your `.devbox/` sub-directory inside your project directory. And run `devbox shell`
2. The more difficult one is to replicate what my [PR](https://github.com/jetpack-io/devbox/pull/1260) does but manually:
   1. Find the executable devbox binary in your `.cache/`. It should be in `~/.cache/devbox/bin/0.5.6_darwin_arm64/devbox` (for you the `_darwin_arm64` might be different depending on your cpu architecture).
   2. in your project directory edit these files: `.devbox/virtenv/.wrappers/bin/echo` and `.devbox/virtenv/.wrappers/bin/tr` and replace `devbox` in `devbox shellenv` at lines 5 and 8 with the path you copied from the step above. The files should look similar to below:
```bash
#!/bin/bash

if [[ 
"$__DEVBOX_SHELLENV_HASH_abcdefgh" != "abcdefgh" ]] && [[ -z "$__DEVBOX_SHELLENV_HASH_abcdefgh_GUARD" ]]; then
export 
__DEVBOX_SHELLENV_HASH_abcdefgh_GUARD=true
   eval "$(DO_NOT_TRACK=1 /Users/mohsenansari/.cache/devbox/bin/0.5.6_darwin_arm64/devbox shellenv -c /Users/mohsenansari/code/jetpack/go.jetpack.io/examples/discord/cooperlooper)"
fi

eval "$(DO_NOT_TRACK=1 /Users/mohsenansari/.cache/devbox/bin/0.5.6_darwin_arm64/devbox shellenv only-path-without-wrappers)"

exec /nix/store/abcdefgh-coreutils-9.3/bin/tr "$@"

```

**Comment by mohsenari** [comment]
@ckoehn Just letting you know that the new release of devbox (v0.5.7) has this fix. So no need for following the steps on my comment above anymore.

**Comment by ckoehn** [comment]
@mohsenari Thanks for the reminder 👍🏻

**Comment by altano** [comment]
Reporting in: it's been a LONG time since I've seen this problem. Thanks, devbox team!

Any objections to my closing this issue?

**Comment by mstruebing** [comment]
I've noticed that `coreutils` is slowing down my startup time too.
I've tried installing `uutil-coreutils` but I can not find that package `devbox search uutil-coreutils` doesn't yield any results as well as nixhub.io doesn't yield any.

**Comment by altano** [comment]
Closing since I’m not hearing anyone wanting me to leave this open. Thanks again!

**Comment by savil** [comment]
@altano thanks! Glad it is working fine now.

@mstruebing lets track slow coreutils package in https://github.com/jetpack-io/devbox/issues/1350
