### ISSUE TITLE
How to add a custom proprietary PHP extension .so file?

### ISSUE THREAD

**Issue by JoyceBabu** [jetpack-io/devbox#894]
I have the .so file for a proprietary PHP extension. How can I add it to my environment?

**Comment by Lagoja** [comment]
Hey @JoyceBabu, thanks for your patience while I tested this.

This should be doable with 0.4.7, using a Flake to modify the default PHP to include your extension. You'll need to do the following: 

1. Create a subdirectory in your project (say, `my-php-flake`)
2. Copy the .so file into that subdirectory
3. Create the a flake.nix file in the subdirectory with the following: 

```nix
{
  description =
    "A flake that outputs PHP with memcached and ds extension and hello pkg.";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system};
      in {
        packages = {
          # Customize and export the PHP package with some extra config
          php = pkgs.php.buildEnv {
            # extraConfig will add the line below to our php.ini
            # ${self} is a variable representing the current flake
            extraConfig = ''
              extension=${self}/skeleton.so 
            '';
          };
        };
      });
}
```
4. In your `devbox.json`, replace the `php` reference with a reference to the PHP exported by your flake: 

```json
{
    "packages": [
        "path:my-php-flake#php"
    ]
}
```

**Comment by JoyceBabu** [comment]
@Lagoja Thank you for the response. I tried setting up as you suggested, and it worked.

But replacing `php81` with `path:my-php-flake#php` in devbox.json, also removed the `php` service from `devbox services`. How can I enable the service with the flake?

**Comment by Lagoja** [comment]
Hey @JoyceBabu, it looks like our plugins won't activate when you install the php package from a flake. I've created an issue to allow users to explicitly activate plugins, so you can use the customized package and use the service as well

**Comment by JoyceBabu** [comment]
It would be nice to have an option to create custom plugins/add custom services to the process manager.

**Comment by Lagoja** [comment]
Hey @JoyceBabu, this has been updated in recent versions and it should work with plugins. You can explicitly declare a plugin using `include` section in the devbox.json: 

```json
{
    "packages": [
        "path:my-php-flake"
    ],
    "shell": {
        "init_hook": null
    },
    "include": [
        "plugin:php"
    ],
    "nixpkgs": {
        "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
    }
}
```

**Comment by ipince** [comment]
> Is the devbox.d directory managed by the project, or by devbox? To be more specific, are we allowed to add / modify files within the devbox.d directory, or should we ignore the entire directory from version control?

The devbox.d is used for configuration files that are ok to be committed (and probably should be) to version control. See more info here:
https://www.jetpack.io/devbox/docs/guides/plugins/#helper-files
