### ISSUE TITLE
[Bug]: Not able to use postgis extension with PostgreSQL

### ISSUE THREAD

**Issue by marcelocbf** [jetpack-io/devbox#912]
**Current Behavior (bug)**
- Not able to use postgis extension with PostgreSQL database service plugin

**Expected Behavior (fix)**
- To be able to run CREATE EXTENSION postgis; without a problem

**Additional context**
- Trying to run "CREATE EXTENSION postgis;" sql statement gives me the error below
`
[ERROR] error: could not open extension control file "/nix/store/y2dfv0jf61pgwgkc9rfq7kjabshpwqra-postgresql-14.6/share/postgresql/extension/postgis.control": No such file or directory
    at Parser.parseErrorMessage (/Users/XXXX/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/XXXX/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/XXXX/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/XXXX/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
`

devbox.json
`
{
  "packages": [
    "nodejs",
    "postgresql",
    "postgresql14Packages.postgis"
  ],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
`
devbox version: 0.4.6

I'm able to find a postgis package under /nix/store/XXXXXX-postgis-3.3.2 .... and also under .devbox/virtenv/.wrappers/share/postgresql/extension path but it seems that Postgres is only looking in their installation directory

**Comment by Lagoja** [comment]
Hey @marcelocbf, I was able to reproduce this issue and I'm digging into it now. I think this might be related to the Nix issue here: https://github.com/NixOS/nixpkgs/issues/38369. I'm looking into how we can resolve it with Devbox

**Comment by marcelocbf** [comment]
Thanks @Lagoja for pointing to the Nix issue. It will be great to be able to have it working on devbox...

**Comment by Lagoja** [comment]
Hey @marcelocbf: I was able to create a postgresql package with the extension installed using our flake support, but doing this will fail to trigger our postgres plugin (which sets up a bunch of environment variables + services for postgres). I'll post the Flake below, and then update this issue once we've added support for activating plugins explicitly (see #938)

Here's a gist with the flake + devbox.json. If you use this, you'll need to create the database with `initdb <path>`, and start the server with `pg_ctl -D <path> start`

https://gist.github.com/Lagoja/a54975e22912d02df60590ab10de9c0a

**Comment by Lagoja** [comment]
Hey @marcelocbf, wanted to update that this should be fully resolved in the latest releases of Devbox. You can use our Flake support + the `include` section of the devbox.json to activate our plugin. See the gist above for a full example. The devbox.json should look something like: 

```json
{
  "packages": [
    "path:postgres#postgresql"
  ],
  "shell": {
    "init_hook": null
  },
  "include":[
    "plugin:postgresql"
  ]
}
```

and the postgres/flake.nix file should look like: 

```nix
{
  description =
    "A flake that adds the postgis extension to Postgresql";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = nixpkgs.legacyPackages.${system};
      in {
        packages = {
          # Return postgrsql with the postgis extension include.
          postgresql = pkgs.postgresql_14.withPackages (p: [ p.postgis ]);
        };

        defaultPackage = self.packages.postgresql;
      });
}
```
