### ISSUE TITLE
[Bug]: /bin/bash does not exist

### ISSUE THREAD

**Issue by ragingpastry** [jetpack-io/devbox#949]
**Current Behavior (bug)**
While using devbox on NixOS I receive an error message whenever I try to run any wrapped commands inside of a devbox shell.

```sh
devbox init
devbox add python310
devbox shell
(devbox) ╭─crepe@polis /tmp/testing 
╰─$ python --version
zsh: /tmp/testing/.devbox/virtenv/.wrappers/bin/python: bad interpreter: /bin/bash: no such file or directory
```

**Expected Behavior (fix)**
I expect the devbox wrappers to inherit the location of my current $SHELL instead of hardcoding `/bin/bash`

I believe all we have to do is modify https://github.com/jetpack-io/devbox/blob/main/internal/wrapnix/wrapper.sh.tmpl#L1 to use an environment variable

**Additional context**

devbox.json
```json
{
  "packages": [
    "python310"
  ],
  "shell": {
    "init_hook": null
  },
  "nixpkgs": {
    "commit": "f80ac848e3d6f0c12c52758c0f25c10c97ca3b62"
  }
}
```

```sh
(devbox) ╭─crepe@polis /tmp/testing 
╰─$ devbox version -v
Version:     0.4.6
Platform:    linux_amd64
Commit:      none
Commit Time: unknown
Go Version:  go1.20.3
```

**Comment by savil** [comment]
@ragingpastry thanks for reporting. Will fix!

**Comment by ragingpastry** [comment]
Pushed up a MR for this. Feel free to close if its not going in the right direction! 

https://github.com/jetpack-io/devbox/pull/950
